-- generated by KeySteam
-- update time: 2025-03-20
-- app_name: Dual Discovery: Unite Challenge 寻踪觅影：合二为一

addappid(3251750)

addappid(3251751,0,"0ae8c86572a67b2671a2fe5d361d2eeeec07d3079de727fb3158a33db460f770")
