-- generated by KeySteam
-- update time: 2025-09-11
-- app_name: FantasyHearts

addappid(3258090)

addappid(3258091,0,"52294579CE38B044A5EB60317878BCC58A4EBB8B1692E62E0AAEA2ED65C9B7E9")

-- DLC: 2/2

addappid(3505290)
addappid(3505300)