-- generated by KeySteam
-- update time: 2026-01-24
-- app_name: Arcane Rivals

addappid(4037090)

addappid(4037091,0,"856b432230e94d0bfcf7e74f1fdcd8048490f413711f603f8c27853cea821c8f")
addappid(4037092,0,"4395c9eac121c2813db7bc8234dc4dc5edc4ca22eadd3b5ae6ac43c81aef0139")
