-- generated by KeySteam
-- update time: 2018-11-08
-- app_name: 962080

addappid(962080)

addtoken(962080,"16765377136185556803")

addappid(962081,0,"fd8e3dba37fff26dc0e59d12b7ad637f2663cc0563b0a695c83d5442d928b230")
