-- generated by KeySteam
-- update time: 2018-11-10
-- app_name: 963080

addappid(963080)

addtoken(963080,"9001457716306404990")

addappid(963081,0,"a209c1b14a508346dc8a82e5fccdb191fcd45f1dcfba99ae65048c1815aba60e")
