-- generated by KeySteam
-- update time: 2018-11-01
-- app_name: Pirate Survival Fantasy Shooter

addappid(963150)

addappid(963151,0,"3f40d6d1632714733f909b9fb2b5031f0a515dd3be34a1183465a3e27b898ce2")
