-- generated by KeySteam
-- update time: 2025-05-28
-- app_name: 特里诺兰

addappid(965010)

addappid(965011,0,"b52e727da2f1b0e967c6a17f180b1d8f3fd2049663c71d7d5d2fb15f15bbdb21")
addappid(965012,0,"782a7e4fbee43da0017c7b5a6abd588bec9c17a9871d5304fae68b570594c53e")
