-- generated by KeySteam
-- update time: 2022-06-16
-- app_name: Walking Zombie 2

addappid(965200)

addappid(965201,0,"dd1564f6aded063eadd8c74d43664256d930cc3195f97c4a4e9eef7b3c4af0c6")

-- DLC: 1/1

addappid(1221700)