-- generated by KeySteam
-- update time: 2018-11-29
-- app_name: Jump Jumpz

addappid(968200)

addappid(968201,0,"aa393a7ef8fdcd9cfdf6d523932d9651ffcf24bfc654b022e14f1a35c4c1a716")
addappid(968202,0,"064f12fbc2793682c7895b03d6be3ae14f020669c406ae518cdbed7601be929a")
