-- generated by KeySteam
-- update time: 2018-11-09
-- app_name: The Lost Soul

addappid(969130)

addappid(969131,0,"6043591b8df4297b1044173fef5f0fd9ae2c24bd84e59a7504fed0e17bdd273e")
addappid(969132,0,"ae7b8dd806ea3ee25d9cd6142ac39de7aa6bc575c88616274bfa216fb18d76e7")
