-- generated by KeySteam
-- update time: 2018-11-08
-- app_name: stepbystep

addappid(972940)

addappid(972941,0,"c252d6e479e18a0379fbbe342ec18092319dfc5de0e1ca5359520e0aadfcf93b")
addappid(972944,0,"5126981485ba7a80080f8de7328be57bd6f072ff13de6db923c4d262a901a06e")
