-- generated by KeySteam
-- update time: 2018-10-30
-- app_name: 974490

addappid(974490)

addtoken(974490,"13593563874552131515")

addappid(974491,0,"7aafc8d42fec9231848cd63fa9f53c9c1b25d472c5d5a2760cdddc79bd11d312")
