-- generated by KeySteam
-- update time: 2018-11-07
-- app_name: Spaceguy: Red Space

addappid(976240)

addappid(976241,0,"b85405a2d20fc1738d7f6984451ea605cabd966a01442756406f6ebc454f8577")

-- DLC: 0/1
-- missing DLC: 977820
