-- generated by KeySteam
-- update time: 2018-11-22
-- app_name: Trafic Road Rush

addappid(976850)

addtoken(976850,"13120483349982340469")

addappid(976851,0,"aa50c466d17651e0d97efc1d44fc4f3aae73e777f65437e14c29f9f350fe90f5")
