-- generated by KeySteam
-- update time: 2018-12-03
-- app_name: Heart of Moon : The Mask of Seasons

addappid(976960)

addappid(976961,0,"9426945ca3360d661fbf33fcfb335cfb49a7c3c42b3c64e1c9b9e0ecb9a67147")
