-- generated by KeySteam
-- update time: 2019-02-04
-- app_name: バインドを解除する(unbind)

addappid(977590)

addappid(977591,0,"886df2bb52466ff51608ecf9c2101f853b83232964026fe41569be7dae59afd7")
addappid(993410,0,"892ce4cca6df4a7fbe339824a2d9232132b224f69e25f025f3631af9a8f08715")

-- DLC: 1/2
-- missing DLC: 3305850

addappid(993410)