-- generated by KeySteam
-- update time: 2023-03-10
-- app_name: Christmas Clicker: Idle Gift Builder

addappid(978670)

addappid(978671,0,"e0da563c7d6a30c954cb0fe5a95dbbac6cf651db7cb0e1a73c0891c94b43937f")
