-- generated by KeySteam
-- update time: 2026-04-12
-- app_name: Section Gamma

addappid(2381290)

addappid(2381291,0,"B9CCABFCBC2D7DDF8A69BAED381CCDE6D9F0A0DE6FED128641BC21B3B92F4712")

-- DLC: 2/2

addappid(2469100)
addappid(2469101)