-- generated by KeySteam
-- update time: 2023-04-14
-- app_name: Vacuum cleaner robot simulator: pile sos edition

addappid(2383850)

addappid(2383851,0,"70749174c310acb373d939645ea5c977e7af5ee22ea1d2086c2f0ddb89312ba3")
