-- generated by KeySteam
-- update time: 2023-05-25
-- app_name: Idle Dragon Clicker

addappid(2384780)

addappid(2384781,0,"dbf6aa79236a39abce0499c36f6fbe7f9a3debe1e8b108e141910a62a4e6a1e1")

-- DLC: 0/3
-- missing DLC: 2441770, 2443690, 2451690
