-- generated by KeySteam
-- update time: 2023-06-06
-- app_name: 2386660

addappid(2386660)

addtoken(2386660,"17784750226443267112")

addappid(2386661,0,"482d6de1454a2e3602fc046e3c93795d62102ca7b9ab2e4559ffc109a1d16cd3")
