-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: 閃攻機人アスラ - ASURA THE STRIKER -

addappid(2389830)

addappid(2389831,0,"87d35476e1ed17a5daca4f08275c3201f5899a67f078687df4939c4179238acd")
