-- generated by KeySteam
-- update time: 2026-03-17
-- app_name: Melody Mania

addappid(2394070,0,"8b182eb88a56ad4de63bb7912f6acc06749d33e3b43543c55455205561be850c")

addappid(2394071,0,"1fdf45dcfd05ab8bb2dbe8a5a4523600137e4914eb130a034f05845fa8d2320f")
