-- generated by KeySteam
-- update time: 2019-11-22
-- app_name: Crest

addappid(341710)

addappid(341711,0,"ebd1f80afe8fd97a0cd45fe7aacc7e73e6f8f797a5ea71addeab2dc47b8434a2")
addappid(341714,0,"45f962bdf5d16c918fef753179e012b630d5f6735c4f3eca551b6a0a8b0d50fe")
addappid(386570,0,"3cb0ae26c22a8b45da7038dcb16756f076e1990bfb83341ec3ffef219e8128f2")
addappid(386580,0,"8c980023154167a959f15e9f70814f89ff2def88cb7d949d631a2d2a1ade6557")

-- DLC: 1/1

addappid(386580)