-- generated by KeySteam
-- update time: 
-- app_name: Shadowrun: Hong Kong - Extended Edition

addappid(346940)

addappid(346941,0,"27059c95e2ea0fcddfff3d8e3e10403cc677af265451e7c3a857103f1a82fe8d")
addappid(395260,0,"8361c13537643f3e20e1aeb1883b0bfdc2ffca9189dec5f535b080c0408a0c2c")

addappid(395260)