-- generated by KeySteam
-- update time: 2026-03-24
-- app_name: DROD: The Second Sky

addappid(351320)

addappid(351322,0,"9b96b4ec77d9acdb4422c1d53303cc479ec43e8feb4e738fee02180f41f80041")
addappid(351323,0,"6a4f30e7132eddec65f5e43bc8ec67ca3b019ac39d38cd01922f5cf1298569da")
addappid(351326,0,"ef6f815c93ed09659467324f7b8e130a057fd3e5d0a2ea952f061d752ff67bff")
