-- generated by KeySteam
-- update time: 2017-05-10
-- app_name: Apple Jack 1&2

addappid(351690)

addappid(351691,0,"f601d49a401c52b98d81a86ab1a9cce88f6d248b459a0c5956d6acf9d001aaa0")

-- DLC: 0/1
-- missing DLC: 629470
