-- generated by KeySteam
-- update time: 2024-07-30
-- app_name: The Adventures of Tree

addappid(354860)

addappid(354861,0,"f5b71dadeebf1d2a25dde422e92dbfc8d479e4c24f27d5f0b69b05ac0c86ce9c")
addappid(354862,0,"51a30e491703ffadcbce7a18ff2fc999bb995a9344f8685727661e0071a2e2df")

-- DLC: 0/1
-- missing DLC: 2121700
