-- generated by KeySteam
-- update time: 2017-12-11
-- app_name: The Reject Demon: Toko Chapter 0 - Prelude

addappid(358770)

addappid(358771,0,"4adaeb04f3418e2bf219e1dba49a60460e0d4c6300f7ef9108f4dd7982b9fc17")

addappid(369340)
addappid(762140)