-- generated by KeySteam
-- update time: 2026-04-30
-- app_name: 昏迷3：血脉

addappid(3885590)

addappid(3885591,0,"7462789e82b8d5bfd1826e778373fec8ee0ce31a257685828ec1cd26143df489")

-- DLC: 8/9
-- missing DLC: 4279430

addappid(4279340)
addappid(4279350)
addappid(4279360)
addappid(4279370)
addappid(4279380)
addappid(4279390)
addappid(4279400)
addappid(4279410)