-- generated by KeySteam
-- update time: 2024-05-18
-- app_name: Broken Lands - Tower Defense

addappid(2734140)

addappid(2734141,0,"f56985971cbdff4872eea391a869257410060dc95234cae95922744f419e7c10")
