-- generated by KeySteam
-- update time: 2026-03-22
-- app_name: Milliopoly - Language Quiz and Learning

addappid(1822010)

addappid(1822012,0,"cc3a5916779785743f934bb49700e4da024fda8ca352cc42de9334bf2d473c9a")
