-- generated by KeySteam
-- update time: 2023-07-05
-- app_name: シオリノコトハ ～ Dark Reflections ～

addappid(1826030)

addappid(1826031,0,"26b05283f5b34de65296321ffc8feb312259a6b7d65c346dae8ceebe6b9cf7c7")
