-- generated by KeySteam
-- update time: 2021-12-03
-- app_name: 古墓探险

addappid(1829060)

addtoken(1829060,"17525704011699568350")

addappid(1829061,0,"864d70e9fc9e0272b51a6bda6cb8c6bc8ccef930357f4cc84a9d18dd00548ca1")
