-- generated by KeySteam
-- update time: 2022-06-04
-- app_name: LIP! Lewd Idol Project Vol. 1 - Hot Springs and Beach Episodes

addappid(1831050)

addappid(1831051,0,"8acb956313b90ec9d71e8f7a6c009d2f3d42a0c9ac0133a11ff7134acb7060da")
