-- generated by KeySteam
-- update time: 2022-06-23
-- app_name: 1831630

addappid(1831630)

addtoken(1831630,"6164050953752826218")

addappid(1831631,0,"d7e0df3eaa889971f36c22ed8c618e157c82cbcdbfdf519844bbd33013518571")
