-- generated by KeySteam
-- update time: 2021-11-29
-- app_name: Fantasy Memory - Sexy Mermaids

addappid(1832300)

addappid(1832301,0,"33bf08f6d07bf53421d0e29b788751f8599f68203e33bdf2fbcfdc15603895d4")
addappid(1832770,0,"32f2e29465c5b0f0077ac35c67170e84efe3771d5a816f558e39554892195ad6")

addappid(1832770)