-- generated by KeySteam
-- update time: 2021-12-09
-- app_name: 欲望忍者

addappid(1834390)

addappid(1834391,0,"15b6037e70184121ebc268a18752f18752ef8c6bb55ef1874b27efca1af62000")
addappid(1834392,0,"b30a9e34ae3fa79c12370d49c4cf0bc97d212a7221cde8ee6c3f8122049d4203")
addappid(1834393,0,"5c01cdb5002dbc9575c2eb5a747de1637eb63c7f40c073c49d8f9eb3eee3d3d2")

-- DLC: 0/1
-- missing DLC: 1835100
