-- generated by KeySteam
-- update time: 2021-12-09
-- app_name: ILLUMI-NAUGHTY ;) - Remastered

addappid(1835220)

addappid(1835221,0,"12390be7cf3e997e152292f1d029802159de85f0104ccc08af1470b5289993b4")
