-- generated by KeySteam
-- update time: 2024-01-24
-- app_name: Beyond the Board - DTDA Games

addappid(1837800)

addappid(1837801,0,"34918e29771c93b332492af883065c4ffad8a52bbeeb66b6a50c955180652e77")
