-- generated by KeySteam
-- update time: 2026-01-06
-- app_name: Life of a Space Force Captain

addappid(1838820)

addappid(1838821,0,"04ef79892983834d2fda8d95fe4b81ace0dcdb97ff973309ac4f337442305dd8")
