-- generated by KeySteam
-- update time: 2025-12-15
-- app_name: 江山北望

addappid(3831120)

addtoken(3831120,"7390236893300162594")

addappid(3831121,0,"9dbcd6e3623fd391c2dd9f7a389d82710a063351a504bc5653bcf9a690cbf784")
addappid(3831124,0,"90f46fb691c6ef16289cfa4b2253ef65800d41a7401310a2acba28fe6caf0c7e")
