-- generated by KeySteam
-- update time: 2025-12-05
-- app_name: 3837830

addappid(3837830)

addtoken(3837830,"9903769425121266403")

addappid(3837831,0,"ba76a670f64d4e545ddd5a4d5230c70a8b1f21a16c343b96960b2a0ff79d9fd9")
