-- generated by KeySteam
-- update time: 2026-02-16
-- app_name: 万神之城 Citadelum

addappid(2603020,0,"90db1e7501c77271ccce4298595fb51406b571c86d11f3827532135a1e6702c3")

addappid(2603021,0,"7524dec83e20cc12831a547d7fec9d1b84f8541f334acf468d7e044f132d6e09")

-- DLC: 4/4

addappid(3358500)
addappid(3450060)
addappid(3480880)
addappid(3896670)