-- generated by KeySteam
-- update time: 2026-03-06
-- app_name: Travellin Cats in China

addappid(2608040)

addappid(2608041,0,"da86d90aa41712b5a21971a2df725471a6c3c9d16b576903c6919dedf96db730")
addappid(2915740,0,"b01e1fe66d6b397bb8bad83b1c9f1adba52c6cdad24de2568b0694c2d8f28293")

addappid(2915740)