-- generated by KeySteam
-- update time: 2025-05-14
-- app_name: BattleCore Arena

addappid(2613870)

addappid(1716751,0,"84780b728a23b1dabbe8b064807ccd3dbd40c67139ed569101104a418c581675")
addappid(2613871,0,"b454bcd390881d775e002c4d6f73c7868711813dcd444e6fb1f1cf534b97fd69")

addappid(2781410)
addappid(2826340)
addappid(2826350)
addappid(2826360)
addappid(2826370)
addappid(2842220)
addappid(2842230)