-- generated by KeySteam
-- update time: 2026-03-20
-- app_name: Wizard Warfare 2: Cephalopod Wars

addappid(2613780)

addappid(2613781,0,"d070f6393639e1b121558caf32abaeddab034f518ab3b659683f3bfc2540fc06")
