-- generated by KeySteam
-- update time: 2023-11-16
-- app_name: CHIN CHINNY CHIN MOUSE CHEESE CHIN TOES

addappid(2615200)

addappid(2615201,0,"725390a324d1309946f0ec1ae3e95c5f9c760651e633b71f59ee0cf7381d7c14")
