-- generated by KeySteam
-- update time: 2018-08-30
-- app_name: Freedom Planet

addappid(248310)

addappid(248311,0,"676450a8c66959e587ba4808925c90ec02e095b30320716bd11034aab94f146c")
addappid(316560,0,"3d55381188ba9e4ce1fa1aa3ea958ef01f665e52939fee876914182f83db42c8")

addappid(316560)