-- generated by KeySteam
-- update time: 2022-09-22
-- app_name: The Legend of Heroes: Trails in the Sky

addappid(251150)

addappid(251151,0,"d3199057bf8105926a20079128863995cc7b73c3dd89cc2f808d92033f19f71d")
