-- generated by KeySteam
-- update time: 2026-04-01
-- app_name: 7 Days to Die

addappid(251570,0,"e53177a4e7b3979bb3284352de1dbcf65f8d3b1b57d5d63971906f5b75c53c86")

addappid(251571,0,"2787b64cd24c9e42a114df4d2559813dc0f63405faa2f7e41cc77e6c3cc67bd0")
addappid(251576,0,"525d3fda8d2195cf5a8bd10c0c158513d9f870f99a036830287c1465c73c6979")

addappid(3314750)
addappid(3486400)
addappid(3635260)
addappid(4206290)
addappid(4234560)
addappid(4234570)
addappid(4234580)
addappid(4234590)