-- generated by KeySteam
-- update time: 2019-01-26
-- app_name: Lacuna Passage

addappid(252090)

addappid(252091,0,"27bdb69057e0c9a26ae27ea17959c0f97241da891fa6546bde8eebbbdc274a10")
addappid(252092,0,"469b3f7347fcfeded540d5b5a19dd7eb38b3dec5f2ea7c4be67437352aeb8e57")
