-- generated by KeySteam
-- update time: 2025-12-04
-- app_name: A Hat in Time

addappid(253230,0,"e90e92ac4b9d0da966362c6621f91906e85cd8fb2c707ea81ed45815c0c422d2")

addappid(253231,0,"bad6cfa1002a435782d44a7814659ee3c3621b2c2fafc625c5d17cd7e621f11b")
addappid(253232,0,"f15a83ed51eec3d6335d9bea61d26d27c28baecc34c2f3c1f2815ec8382d53d3")
addappid(1072430,0,"d87ead7e6dacbeb528482d239ef60f3cc36e31ca816dc1bc64a7740be574b18f")

-- DLC: 10/10

addappid(356830)
addappid(787340)
addappid(924490)
addappid(940220)
addappid(1072430)
addappid(1545960)
addappid(1550140)
addappid(1550141)
addappid(1550142)
addappid(1738980)