-- generated by KeySteam
-- update time: 
-- app_name: Fester Mudd: Curse of the Gold - Episode 1

addappid(253310)

addappid(253311,0,"fc5247da76dc251031452fe09aab085696270487ae767456c72293e15a7c2be3")
