-- generated by KeySteam
-- update time: 2025-12-08
-- app_name: Lootun

addappid(1960270,0,"34c44e535955b8fd360f7f4cd531efc01566eb70b2eda854494ce887d58fdeea")

addappid(1960271,0,"b5d5f1bd784dea43a9d929ebcc65b50f78f389fc736a77bc6c6a3be00cda669a")
