-- generated by KeySteam
-- update time: 2024-09-12
-- app_name: Quantum Tripper

addappid(1965970)

addappid(1965971,0,"d9cc56a3de485ca2444f94512aefd5d518767eef325bf6f47f648d865c2b2c98")

-- DLC: 9/9

addappid(1971840)
addappid(1971841)
addappid(1971842)
addappid(1971843)
addappid(2166110)
addappid(2166111)
addappid(2554830)
addappid(2839490)
addappid(3164580)