-- generated by KeySteam
-- update time: 2026-04-28
-- app_name: Aphelion

addappid(1966410)

addappid(1966411,0,"84087eecad930dfa8ba61a10bf538e498019b634f785baf7e8a71b90d4aeb063")
addappid(4252780,0,"81a863c0992146422b10a657cc1bc57004e375c1623fe21b5c61e82babd4213a")

-- DLC: 1/1

addappid(4252780)