-- generated by KeySteam
-- update time: 2022-09-18
-- app_name: 武儒绘卷 - 天地奇缘

addappid(1967830)

addappid(1967831,0,"d031c6e7ce3ca715d29ceddd8a99fe5d1dfc65927b341fc4f96377d56e7d853f")

addappid(2062040)
addappid(2083550)
addappid(2092310)