-- generated by KeySteam
-- update time: 2025-10-04
-- app_name: 拾光物语 Border Town

addappid(1967820)

addtoken(1967820,"7687562562835165712")

addappid(1967821,0,"631e707a73378d4f77ae16909b3dfd15cae9c1edd074e78added4f63331fe912")
