-- generated by KeySteam
-- update time: 2024-09-14
-- app_name: 和平缔造者：光辉王女

addappid(1977070)

addappid(1977071,0,"460f9931bd85aa79a1e9b74ec74c227a472d39425139ffd1e449159f16302e1a")

addappid(2963690)