-- generated by KeySteam
-- update time: 2025-11-25
-- app_name: 《圣诞怪杰：圣诞大冒险》

addappid(1978210)

addappid(1978211,0,"f5321f47ddc16c376743aac65457034d4c27eb8242cac9d34e524ed2ce6d6bef")

addappid(3694440)