-- generated by KeySteam
-- update time: 
-- app_name: Theatre of War 3: Korea

addappid(63960)

addappid(63961,0,"424de56ec177abe443b35a746afde4cfecfb0fe73b97a0ed0be21b7b883937a1")
addappid(63962,0,"c50c0b5cb2c5c057b4d6d334b236f5367bdb7fea18c9ef30a5ae4a87686ef7e8")
addappid(63963,0,"932ac7639523431c6370a9b19a9eaca61fe77aa65872df2a039a359f8295be35")
