-- generated by KeySteam
-- update time: 2017-08-09
-- app_name: 662640

addappid(662640)

addtoken(662640,"18076858585217256556")

addappid(662641,0,"01486d67f250789475e7ce11f34fcb7638aa7c53a439c6cdc10e1f61404597d6")
