-- generated by KeySteam
-- update time: 2019-11-28
-- app_name: Rift Coaster HD Remastered VR

addappid(663200)

addappid(663201,0,"91f629cd399c3bad1e00538f10bf9447d86aee226e3d33c425cf3ff2c713d33c")
