-- generated by KeySteam
-- update time: 2023-06-29
-- app_name: Mutilate-a-Doll 2

addappid(665370,0,"ab02358960294df8b96f73970b81d8b67eec8e28b2b685b42ca9e7a131ab096d")

addappid(665371,0,"9ae7f44a1e7248cd1d7fd7eab53ea9e26933f7139fba1f5948c45e99f402177f")
