-- generated by KeySteam
-- update time: 2017-07-04
-- app_name: 665600

addappid(665600)

addtoken(665600,"6976025695035528559")

addappid(665601,0,"24c7e18f22781c06f3f0b2663054ed58743070a696d6fea3fb2b2b3883155c07")
