-- generated by KeySteam
-- update time: 2017-06-24
-- app_name: 666070

addappid(666070)

addtoken(666070,"2129416698937496772")

addappid(666071,0,"fe6f031cd1b4148865b123075f1317a0213ea598311a58ad0ddad3259e05360d")
