-- generated by KeySteam
-- update time: 2019-01-04
-- app_name: 668070

addappid(668070)

addtoken(668070,"14891600216688034103")

addappid(668071,0,"649f9cfe2a89f9ff6f372e14a588dbc2b0a37f5f70211289eeeb2a98ff7da38b")
