-- generated by KeySteam
-- update time: 2019-04-02
-- app_name: Higurashi When They Cry Hou - Ch.6 Tsumihoroboshi

addappid(668350)

addappid(668351,0,"6c4a7f4c52841397f660157461442b31702f16850b728ef9c72b52b3fc6f6c5b")
