-- generated by KeySteam
-- update time: 2017-09-28
-- app_name: Hangry Bunnies From Mars

addappid(672910)

addappid(672911,0,"6f921ad09a9762e38771ed2ad9b136eb6e0188131b84d00986f885a4da754e37")

-- DLC: 0/1
-- missing DLC: 686070
