-- generated by KeySteam
-- update time: 2025-04-01
-- app_name: Frontier Pilot Simulator

addappid(673210,0,"cec3c622e71ab1f995191ab402c2d13ad168a0df91c668e837d8a5a4e36c6be7")

addappid(673211,0,"4209b5a22dd5f343b779a00aa63a2ccb94cff1e264a2152a1679448fe211d06c")
