-- generated by KeySteam
-- update time: 2017-10-26
-- app_name: Legendary Arcane

addappid(673550)

addappid(673552,0,"3aa284ee927eb93e148718f0869aa24e2c2f7ff6f7bac58d5f7a3a861cbb5a7f")
addappid(673553,0,"e14e659e8661287bc1fd5f7f34145eca1ed2101be12e7c2c5da636bb51dbffb5")
