-- generated by KeySteam
-- update time: 2025-10-06
-- app_name: Defend the Cake

addappid(674330)

addappid(674331,0,"130b7becbe9d031677c52538b3ef9602699b23f94e0c9a3b3343c25fd7ef75da")
addappid(674332,0,"7a7ec4d7c8b71a7f744624944f583d6958c26d9c3e541c24b8bf4675faf66b48")
