-- generated by KeySteam
-- update time: 2017-07-11
-- app_name: Fierce Tales: Marcus' Memory Collector's Edition

addappid(678420)

addappid(678421,0,"7717b9b301f45ac629bce9d4b90e32977cb55c03b084e536feb76533d9da113d")
