-- generated by KeySteam
-- update time: 2019-03-07
-- app_name: Solitaire Mystery: Stolen Power

addappid(679820)

addappid(679823,0,"b4ef8a4430b167b930a77f5d893657c6d93c54ad572069d02fb338eee7d5ba8f")
