-- generated by KeySteam
-- update time: 
-- app_name: PT Boats: Knights of the Sea

addappid(10250)

addappid(10251,0,"aacb83167571790993fec751edf4a5db365d4afae0a12d8587e73679eb2fc833")
addappid(10252,0,"960c25a7a28d1b4e346144db934532e22404a07937c443343c7decd267d737b7")
addappid(10253,0,"7443e47bfd5877cbac1bf2107e60e711d754c4ba8def3ffb97e550d23198ab1b")
