-- generated by KeySteam
-- update time: 2025-10-30
-- app_name: Zombie Panic! Source

addappid(17500,0,"d58d3fd9a217135e4edcb8a5561bf05195b40a5a9b2ec2c01be77e0d9b166435")

addappid(17501,0,"5541066063cc4e123fc86d0c899bf83da9454969e3dacfc1581e7bd3465c11b6")
addappid(17502,0,"20b7f29567bd45523e80c451dd7c6d0a3b99e5af101aff87867f9ab973e0d089")
