-- generated by KeySteam
-- update time: 
-- app_name: DeathSpank: Thongs Of Virtue

addappid(18050)

addappid(18051,0,"09ab6beddaef46992054dfc7889957e4c4f3f5b606bdc035b15a8380e2cdedc0")
addappid(18052,0,"a3f60a8b850c004dde4eb8fdf1cdc74e2ff0c2b1695e0208f03f5a196a6687b0")
addappid(18053,0,"11224cfe6ffd24ddfe9991d0c699a2744a3dd1e43b17e93015491fb2c3448134")
addappid(18054,0,"bd6e6f540330b272d66913653e96c1922d16ff3570f3014c898a2fbd6a265ec4")
addappid(18060,0,"1c7d2db1cffa30c068beb249628e7ad169b7926188423cc99bcae5c3741405c5")
addappid(18061,0,"6598c0e1bad35680233949c6c9b17da9e7fd09b048f35ac540d0a6a16a42dbd5")

addappid(18052)
addappid(18053)
addappid(18060)
addappid(18061)