-- generated by KeySteam
-- update time: 
-- app_name: Hitman 2: Silent Assassin

addappid(6850,0,"836886ff9b9b7d9909a0b5e6f11e4aeecce73ccffa055f1661ef8015a0fd551c")

addappid(6851,0,"f208fc795032e395aa6126f8b1a18ed8b33cbc5b6a78ef1469b0e3c957993169")
