-- generated by KeySteam
-- update time: 2024-08-02
-- app_name: Higurashi When They Cry Hou - Rei

addappid(1941110,0,"26cdd13c8cf9da9fc8e7a317b80e7a771913d3254b118257ced16aef50867be7")

addappid(1941111,0,"5ca0bd42a5fc7976a40740b737ee987291e62dbc0307b9a699a59f7ce22a0c58")
