-- generated by KeySteam
-- update time: 2026-03-02
-- app_name: 土豆兄弟(Brotato)

addappid(1942280,0,"bf5b1b4f28c4d1839b85a86e3bfdabc5435f8cc848ca968aec505c86c6ecb52e")

addappid(1942281,0,"414bbd1359869bcea73f5e7f3a911ba4a8f487dee2cf0290cd2409f9ae410582")
addappid(2868390,0,"d7b9838655889932b120a4bd3426b37af101b334e6602a5898a1d54e4dc8f0f8")

addappid(2868390)