-- generated by KeySteam
-- update time: 2022-04-27
-- app_name: 1001 Jigsaw. Castles And Palaces 3

addappid(1950700)

addappid(1950701,0,"e61051632cc5553bb9d99bfebd4f4103a7414153e8331dcace214a103c9db67a")
addappid(1950704,0,"b8b660a8634161d7c437ef23b546f31cf2990f9e607931b04adc4c05005467af")
