-- generated by KeySteam
-- update time: 2022-04-28
-- app_name: Sweet Solitaire. School Witch 2

addappid(1950610)

addappid(1950611,0,"4dc335b793f2b9e713518998591bd50921ed6fe6b3f467a7cb8ce71ac8c163fd")
addappid(1950614,0,"a4b7ee0deaf50cec535735c0bd103c0950c1f215af8209da9a32b18b15f9682a")
