-- generated by KeySteam
-- update time: 2026-02-02
-- app_name: 机器人特遣队

addappid(1952690)

addappid(1952691,0,"e9781974a45048deba65353c8cd3fe69f9f4d4507f4f987b90348edd2c0525e8")
addappid(1952692,0,"86b30e63a4b792431770a4ab0e5bdcb5c9dfa089ba5b2ac43ce6f41eed6d1936")

-- DLC: 2/2

addappid(3621820)
addappid(3907670)