-- generated by KeySteam
-- update time: 2026-04-24
-- app_name: 东方冰之勇者记

addappid(1955830)

addappid(1955831,0,"7c520a8442f3537e7006593708adc76ceb19a2a0bdb9ad6a1158ad9d5c570dad")
addappid(2302890,0,"e1e6947c89bdac7882e1d6de61a59d18e5e1fa13688dc9df74db057d89fab786")
addappid(3213970,0,"8aa8c519999b733e62801b312663af06939b9ca56e89c3fde921f995fc6f56a8")
addappid(3858250,0,"1b846efe1fb18615d3d59aded9675c77647f7fa67bf2f6ad90b1b0abecd46b88")

-- DLC: 3/3

addappid(2302890)
addappid(3213970)
addappid(3858250)