-- generated by KeySteam
-- update time: 2024-06-06
-- app_name: Drop Mahjong tiles

addappid(2809920,0,"9ef7493867cf013c850d2ca6be37f952a4e4216fedfb26ef9a81db4e06af9174")

addappid(2809921,0,"9d045ceb035639193bb332b2481f76d8d39ad387b419d5a20c54fd31637e6416")
