-- generated by KeySteam
-- update time: 2024-08-07
-- app_name: Project Spatial - Capture & share spatial videos

addappid(2818070)

addappid(2818071,0,"f6dce239f8699e1fdfb9a5e7e822ed8ee7e20ff7557e708861db216f45e9e6df")
