-- generated by KeySteam
-- update time: 2024-12-30
-- app_name: AoA Academy

addappid(2578530)

addtoken(2578530,"4120627532181160396")

addappid(2578531,0,"0ca261afa3b5a6bab9d6d908ca43c7b9bbf0eb6512bfba15c59670e493314873")
addappid(2578532,0,"517cd5284a25666d189bbaf019433a3145d454841e8452cbb8ebcef7f2614df8")
