-- generated by KeySteam
-- update time: 2017-05-01
-- app_name: Ancient Rus

addappid(562210)

addappid(562211,0,"5551512330bd45961d7763613f98ad9f85842d48e599c2b294a176bfd9a12e91")
addappid(625610,0,"01964edc6a6f324f42e0d4efef2a557a898b707d548bb78b3d119e1efe754cb6")

addappid(625610)