-- generated by KeySteam
-- update time: 2017-01-10
-- app_name: Western Adventure

addappid(562710)

addtoken(562710,"12754170133507709850")

addappid(562711,0,"901041ae54705fda30ab01a48d3295e7350f41ec301906e1b8199f5ff67384eb")
