-- generated by KeySteam
-- update time: 2018-01-28
-- app_name: Don't Touch The Zombies

addappid(563370)

addappid(563371,0,"28bc3d7bdc77c7c7cb61152aa495b0d7f1ab5a7677eef8eb3c1f1a49d467f2b3")
addappid(563372,0,"0ba905b328300fa3a15db7f11584baacb550cf3a540da90b434fcc67f2a42af5")
