-- generated by KeySteam
-- update time: 2025-11-07
-- app_name: 异形丛生：虫启天降 (Alien Swarm: Reactive Drop)

addappid(563560,0,"c15f22035eff2fca825bcf0cf9ded4f04376fb7f3d4a248447de874c685c9e7a")

addappid(563561,0,"fa5311e8473824241c7cb8ad6a5f5125b25d3f2ecfa963a7c880303106e9d469")
addappid(563562,0,"185b68d4e971f70783541e98d1bbf47f48585fec0b3e45ecde0a29b48eb247a9")
