-- generated by KeySteam
-- update time: 2019-07-01
-- app_name: Stern Pinball Arcade

addappid(564010)

addappid(564011,0,"ce8b309fab0f2c92aa07ae4f0dd9fefe1f06930b5ab67092759c5f532237b70c")

addappid(569240)
addappid(569241)
addappid(569242)
addappid(569243)
addappid(569244)
addappid(569245)
addappid(569246)
addappid(569247)
addappid(569248)
addappid(569249)
addappid(744380)