-- generated by KeySteam
-- update time: 2016-11-29
-- app_name: Whispered Secrets: The Story of Tideville Collector's Edition

addappid(564450)

addappid(564451,0,"8f8d250aed26896f1a414a8076af005dc34857d75703a6799a440a56d1f82622")
