-- generated by KeySteam
-- update time: 2018-10-09
-- app_name: Soda Dungeon

addappid(564710,0,"126e453fd5ca203a33abd4b0ffa414e6a9c9d53db21158ac2d20d2009494170c")

addappid(564711,0,"a97c39d15bec7c42e9acf538869fcc0be875350f3e7fa1a0428aecafb1b7e52a")
