-- generated by KeySteam
-- update time: 2026-04-02
-- app_name: 铁甲雄兵 Blood of Steel

addappid(567630)

addtoken(567630,"16988027702564698647")

addappid(567631,0,"467a0118cf9a28bd21e9c6b2974eda835512b4c9a8dd385e082d98ba9daeecce")
