-- generated by KeySteam
-- update time: 2023-05-10
-- app_name: DARK SOULS™: REMASTERED

addappid(570940)

addappid(570941,0,"e782efcd07a6c765e4393f9b7b6285c09819e62da5f1573e40f15b98303799fe")
addappid(570942,0,"74947c74eb866acac60dc108e9c8144e499da81f312f965cfe46ef6c280afaef")
addappid(570943,0,"b789ea361d9a3e2ff6beb324f2a264fa8db3a49e9ccf390e88332f3850ce5735")
