-- generated by KeySteam
-- update time: 2025-10-10
-- app_name: AWAY: Journey to the Unexpected

addappid(573110)

addappid(573111,0,"8677cbf46c1d4da0b6c94ac215f6bc6b5bfeb8757ea781ddc80965c18239541d")
