-- generated by KeySteam
-- update time: 2017-11-10
-- app_name: Island Tribe 4

addappid(573700)

addappid(573701,0,"9fb1b0fff79849417e9ad9e3c6c89c050d03d4612551511506f29591b499daa0")
addappid(573709,0,"5d3a4c6df0cd8f6d324e02f50ec5ab8f229d850be051b0f2e6bb72d7a694e302")
