-- generated by KeySteam
-- update time: 2017-02-01
-- app_name: 575740

addappid(575740)

addtoken(575740,"9875855538446795145")

addappid(575741,0,"2ec62ff9bfe4e6650c8c255fd5396d9d4b89286e9a31040d7f36eeaa89282575")
