-- generated by KeySteam
-- update time: 2024-08-04
-- app_name: Higurashi When They Cry Hou - Ch.5 Meakashi

addappid(577480)

addappid(577481,0,"fe1762b9b99a18e97b887c1fac577b40004216dba9bae110bba68d3b76bdace7")
