-- generated by KeySteam
-- update time: 2021-03-17
-- app_name: The Outer Worlds

addappid(578650)

addappid(578651,0,"a877c80b32c589baa437c2ed817cf77259a5af3619a9159ea1316e9f98f6eda7")

-- DLC: 4/4

addappid(1393110)
addappid(1393111)
addappid(1425450)
addappid(2170820)