-- generated by KeySteam
-- update time: 2022-08-15
-- app_name: Mystery Solitaire. Powerful Alchemist 2

addappid(1922120)

addappid(1922121,0,"acd5a713f3642f763c3d5957dcc13a519e0dc7c00a85d4db9ef0c01b87ef1d65")
addappid(1922124,0,"173dc1c14056376f54d023da66ca2b63c61ac4ad162f66541390d60f80905825")
