-- generated by KeySteam
-- update time: 2025-01-22
-- app_name: TT Isle Of Man: Ride on the Edge 3

addappid(1924170)

addappid(1924171,0,"dc2a2fa0a93a7767111124bf716ca6299a76f547234b46a62f20b4cf411ed62e")

addappid(2148840)
addappid(2157600)
addappid(2214700)