-- generated by KeySteam
-- update time: 2022-03-08
-- app_name: 1925170

addappid(1925170)

addtoken(1925170,"7744304769349688947")

addappid(1925171,0,"2ccbafdfce0b47e731c1bb6d40fab765ef54afa31616b261e2f063e65eedfa11")
