-- generated by KeySteam
-- update time: 2022-03-23
-- app_name: 1001 Jigsaw: Earth Chronicles 8

addappid(1930180)

addappid(1930181,0,"cce25cdd7f22aacf1ceccfa38bfa85b25e0fbac51e88ac3bb7e1fe6638b33fe3")
addappid(1930184,0,"1c8625f1e10c3ce6e6da55b48f0acd73cf230d9f49f08c1c2ca4bfaf15a01dd1")
