-- generated by KeySteam
-- update time: 2023-01-04
-- app_name: Demons Roots

addappid(1933660)

addappid(1933661,0,"6a72455adb090f5450df3153498406e6ffecbc4c18a79f3eac48edba3517b4fb")
addappid(1933662,0,"39d4c2545f8f64ed5d98a87a78ed5c41081b19ba05101ad5e24e5e6122612f89")
