-- generated by KeySteam
-- update time: 2022-04-04
-- app_name: Infinite Links

addappid(1934980)

addappid(1934981,0,"03099c9eb8e14679d688fca2b8006cdd580807a6ecffcd5746aa351014c14b90")

-- DLC: 3/3

addappid(1935060)
addappid(1935061)
addappid(1935062)