-- generated by KeySteam
-- update time: 2026-04-13
-- app_name: Armored Brigade II

addappid(1934300,0,"ff0f14872b1377af653ea2f95782665c3a379f7f89839ef259fdeb215d01129f")

addappid(1934301,0,"7ce31204842d3231f5bddfa9413eec7c56a2be2e1501715523f96f88c86e1588")
addappid(1934302,0,"417d89135739ceccddbbe3f41c93facb7c1d8b14e2931b69783da4ec59102d94")

-- DLC: 1/1

addappid(4042860)