-- generated by KeySteam
-- update time: 2025-08-05
-- app_name: Chocolate Factory Simulator: Prologue

addappid(2822380)

addappid(2822381,0,"9d2900eb7c5e9308e8c9270157dbe756d109b98b51074a9c05d31a93cf984270")
