-- generated by KeySteam
-- update time: 2025-06-09
-- app_name: 特里的其他游戏合集 Terry's Other Games

addappid(2824580)

addappid(2824581,0,"8a90e1e60596221ea975f5a494f919e4a8fd97e4926734dd5cdef51ec2769ab8")
