-- generated by KeySteam
-- update time: 2024-05-24
-- app_name: Retaliate

addappid(2828210)

addappid(2828211,0,"beee427e5188aa999e084225c171e4a1feb75463ee7de5a49a818104faadb3af")
addappid(2828212,0,"5ab61368b5089a62aaf02cbd7d9f8c1b41c204a98a4204d180509d2c9c04b04e")
