-- generated by KeySteam
-- update time: 2025-12-17
-- app_name: 风暴：深厚友谊的开始 重制版

addappid(2829790)

addappid(2829791,0,"f205e2369971a3648f4ecfa09318f96511a707f005a067f90384a8dedc8c1d34")

-- DLC: 1/1

addappid(3145870)