-- generated by KeySteam
-- update time: 2025-12-07
-- app_name: Revenant : In memory of the day

addappid(2230420)

addappid(2230421,0,"99384958f3a38715de53bd4844840c39147281c6c7c816e91747382adfe6a2ca")
