-- generated by KeySteam
-- update time: 2023-12-19
-- app_name: 佩露夏与魔法的迷宫塔 -阿拉伯夜喵篇-

addappid(2231870)

addappid(2231871,0,"d26b778b16544466d625912a19f9045b1b5d94f2c07f7525c0d00ce208fd9a6b")

addappid(2305540)