-- generated by KeySteam
-- update time: 2024-01-27
-- app_name: Backrooms Descent: Horror Game

addappid(2232180)

addappid(2232181,0,"6da7d9bb69c5e1c4f154422df859eb3fc101bea81210542ff050d1b85fc8f651")
