-- generated by KeySteam
-- update time: 2022-11-27
-- app_name: 2234280

addappid(2234280)

addtoken(2234280,"17765103019098921511")

addappid(2234281,0,"45222a227949e2f06c4fb246f22c266ce8457e3777a6f401f5c6d9e6ebad38c0")
