-- generated by KeySteam
-- update time: 2026-02-08
-- app_name: Breakout Epilepsia

addappid(3109440)

addappid(3109441,0,"73E9A30E4B396C9E04869132445FB4095A6FBFDE38AD0F62E44470551984A7AD")

-- DLC: 0/1
-- missing DLC: 3192890
