-- generated by KeySteam
-- update time: 2026-03-21
-- app_name: 微小生境：治愈放置

addappid(4276980)

addappid(4276981,0,"1363c737173dea2d7345f7e55c8eaeec8f74cb3f869ce4bd5f2b6bb58f5de772")

-- DLC: 1/1

addappid(4500180)