-- generated by KeySteam
-- update time: 2025-11-20
-- app_name: 100 Cats Lost in Italy Find & Color

addappid(3809600)

addappid(3809601,0,"98fc3486cbd426ac5d782b0c9f368af66f2037939cd567798d1b152cd6ca99fc")

-- DLC: 1/1

addappid(4045650)