-- generated by KeySteam
-- update time: 2023-10-30
-- app_name: Fears to Fathom - Ironbark Lookout

addappid(2506160)

addappid(2506161,0,"21ca9f80277ec51e1e063ad48d39eb22f37081c9034ab900704dde1986b4806e")
