-- generated by KeySteam
-- update time: 2023-08-08
-- app_name: The PenguinGame 2 -Lies of Penguin-

addappid(2513890)

addappid(2513891,0,"850823af1427a3490797f00ac19dbe87b8aa3b9203a0ea435937b57eba4a997a")

addappid(2520200)