-- generated by KeySteam
-- update time: 2019-06-18
-- app_name: 伊勢志摩ミステリー案内 偽りの黒真珠－ISESHIMA STORY

addappid(1100030)

addappid(1100031,0,"e5b740a342b547164559429b57eaae820446fcac4ca648759a19042ed3528361")
addappid(1102160,0,"77eb4f734cdb94b9b8dc65661fcbbe9d1b68ed42a5be9fa5b87555d5c349948e")

-- DLC: 1/1

addappid(1102160)