-- generated by KeySteam
-- update time: 2025-09-01
-- app_name: Learn Japanese RPG: Hiragana Forbidden Speech

addappid(1114950)

addappid(1114951,0,"96E40421B43BAAC062796C3BB9A194A26BB8EE893967D48CF6F21274109A7689")
