-- generated by KeySteam
-- update time: 2023-02-10
-- app_name: C64 & AMIGA Classix Remakes Sixpack 3

addappid(1115670)

addappid(1115671,0,"e6e02f89f596c7fcde5537ee8eb669385e24e5ec808e4f711292df63e55dab61")
