-- generated by KeySteam
-- update time: 2021-03-21
-- app_name: Learn Spanish! Easy Vocabulary

addappid(1117590)

addappid(1117591,0,"239e6dbbd45f75d9f8ab8a06879678948ecfb1d2bc6ee5095e9249ed11da28d2")
