-- generated by KeySteam
-- update time: 2024-02-03
-- app_name: Cruelty Squad

addappid(1388770,0,"cbe628d72a7adc70a2f0eb016f977e8f385c9bae90dac62b5e6a3f627eb20617")

addappid(1388771,0,"3cdfc9db282b7c09a51a2b71319178f5f099d61e8d80d76936ec2c3ef503541e")
addappid(1388772,0,"662089c7638eddd88c0944ef6d8a4bafa15aa4754e3898bad6c6719b2e117b8a")
