-- generated by KeySteam
-- update time: 2021-06-07
-- app_name: 人中之龙６　生命诗篇。

addappid(1388590)

addappid(1388591,0,"02a2c7298742e3092a66f1d6b2a6c2703b1d8452a110657633953890a89309b4")

addappid(1478720)