-- generated by KeySteam
-- update time: 2020-09-04
-- app_name: Winds Rhapsody

addappid(1390370)

addappid(1390371,0,"caa3679d1d2eaeab4568717c6779d91e4fe1fcb375989de778f7b3dfd0ef1d20")
addappid(1390372,0,"9754e07befc385cfc714191ce3888e331b765a2692a6c87ebc340f12c0c9b515")
