-- generated by KeySteam
-- update time: 2020-08-20
-- app_name: VR Time Machine Travelling in ancient civilizations: Mayan Kingdom, Inca Empire, Indians, and Aztecs before conquest A.D.1000

addappid(1399150)

addappid(1399151,0,"54ce7b0b192994a9ea244b830e900a28c661b44bd4b250c46abdf65993b5e79a")
