-- generated by KeySteam
-- update time: 2025-10-19
-- app_name: 炽澜号

addappid(3864530)

addappid(3864531,0,"6c907aa6b89ce94de692460ae4ca908f3ec0fba1db2d43dd90acad4571329e03")
addappid(4051390,0,"1fa613fd59c7eb0f2e594f4dfa3c7048a03109d865fc01d4708b2c1b283a8fe8")

-- DLC: 1/1

addappid(4051390)