-- generated by KeySteam
-- update time: 2025-10-19
-- app_name: Dark Flowers: Tiny Starlight

addappid(3875630)

addappid(3875631,0,"a2952abd8a0077fa22337939bfe78173b5801054a61286693d4891ce4197c070")
