-- generated by KeySteam
-- update time: 2025-10-18
-- app_name: Forbidden Terror: Board Game

addappid(3994530)

addappid(3994531,0,"620caca17c9f447884464f8acb36ff3247d03f77abd90a681c76346e90808b2c")
