-- generated by KeySteam
-- update time: 2022-01-13
-- app_name: Meow Pow

addappid(1348680)

addappid(1348681,0,"ab84ed225d48e1f699ba26add5c7e7adc5de83544ee07b678793040083d52427")
addappid(1348682,0,"6f2bf1a420bc85a9ab9619f9c6405c7deec12242e4db1b80425220457eb65043")
