-- generated by KeySteam
-- update time: 2022-06-29
-- app_name: RPG Maker MZ - FES Resource Pack

addappid(1350930,0,"92fd78952af55afb7c0d52d34f1e1ec4613c74b09b39a05c62a8839a8b65de4d")

addtoken(1350930,"17195215361648695113")

addappid(1350930,0,"92fd78952af55afb7c0d52d34f1e1ec4613c74b09b39a05c62a8839a8b65de4d")
