-- generated by KeySteam
-- update time: 2020-11-23
-- app_name: Escape Room VR: Inner Voices

addappid(1351220)

addappid(1351221,0,"79bbc24c84a1a9c4a12d2c56e420cb81297cf8e1b7fa3e5a37e14e4465d1acb2")
