-- generated by KeySteam
-- update time: 2025-10-16
-- app_name: Bomb Rush Cyberfunk

addappid(1353230)

addappid(1353231,0,"39e891398178eb462896935f7400ec32fb665213162d174d4b34d9b843519e66")

-- DLC: 1/1

addappid(2518220)