-- generated by KeySteam
-- update time: 2021-02-13
-- app_name: Next Earth: The Journey Trilogy™

addappid(1353660)

addappid(1353661,0,"b781792682c13a4cf3f772a46c8eb6c716b345ae6f7d8b7228ff2d522fce3264")
