-- generated by KeySteam
-- update time: 2020-06-19
-- app_name: Girls Memory Card

addappid(1355010)

addappid(1355011,0,"2ff144f1e63d011bc6bfab7f86d6372d8b54a1aec8202b348e287d17438b15c2")
addappid(1355130,0,"5f9ab99c019c204a187288ee5d21eb7d71e095112c6b810214af99eca4199375")

-- DLC: 1/1

addappid(1355130)