-- generated by KeySteam
-- update time: 2024-11-15
-- app_name: City of Broken Dreamers: Book One

addappid(1358250)

addappid(1358251,0,"2c4814db747d2278c49ba72c2001bb39a857bc26f980d9d54b3f31c027e7cc48")
addappid(1385850,0,"b693ffdfe811030a735b70b587601ce26758aab13cfa40e674c08b117474bbbe")
addappid(3169990,0,"5a6c1d1472aed2af663041e89fe0b461cc1358c503a0a65aad1554885234c4c8")

-- DLC: 2/2

addappid(1385850)
addappid(3169990)