-- generated by KeySteam
-- update time: 2024-04-13
-- app_name: Adventurer Farmer: Save my son!

addappid(2284270)

addappid(2284271,0,"0e64ef09ecaed5fca6b130b8fe25dce73ad2e51eb0e90d6b8e9ab94e9e753c42")
