-- generated by KeySteam
-- update time: 2024-04-18
-- app_name: UFO ROBOT GRENDIZER – The Feast of the Wolves

addappid(2295970)

addappid(2295971,0,"aea4ca56c25a7bc1b3f86e2db5d0be7151d7e136be82005b9baae7bbb1053e1d")

addappid(2438720)
addappid(2438721)