-- generated by KeySteam
-- update time: 2023-07-29
-- app_name: Mr. Mat Hematic

addappid(2295390)

addappid(2295396,0,"a991ffeb4422725d80f724a6e62eb50e09b4eb9ae6bd844de08e07e6f4e69f19")

-- DLC: 0/1
-- missing DLC: 2298640
