-- generated by KeySteam
-- update time: 2024-12-22
-- app_name: Otherworldly: Beginning of the Rift

addappid(3165610)

addappid(3165611,0,"1a8c0c1147e0db7693b68d22f7372bd9d5f86c6362591305a87c55e7ec1aba41")
