-- generated by KeySteam
-- update time: 2026-04-02
-- app_name: 动物栏：桌面牧场

addappid(3167550,0,"8ad4b349f08144eb89fa2093abe11113c34919b9d82567c4f0d802ade2479a76")

addappid(3167551,0,"2eb36141e330220bd89c47de8cca1c780182686771b6f5e9251eeef811774d14")

-- DLC: 4/4

addappid(3467780)
addappid(3592330)
addappid(3687640)
addappid(3734130)