-- generated by KeySteam
-- update time: 2025-02-15
-- app_name: 梦5：春节

addappid(3172220)

addtoken(3172220,"6905363394419308191")

addappid(3172221,0,"420c56109db1519fc24b75968bfeb19a77a69e7391b47125420aeae63bc2c6b3")
