-- generated by KeySteam
-- update time: 2025-06-25
-- app_name: 奔跑吧，香肠！

addappid(2324300)

addappid(2324301,0,"71462dd0917e0aa39a99ff768fb7499b7db568c079fc185067010642ef24d3f9")

addappid(2839980)
addappid(3791180)
addappid(3791190)
addappid(3791200)
addappid(3791210)
addappid(3791220)
addappid(3791230)