-- generated by KeySteam
-- update time: 2026-01-30
-- app_name: 杯杯倒满 Feed The Cups

addappid(2336220,0,"aa39f2b69bb2f489d3bf78e889385c33e1a5f1bca990a0a214a74afe637c6510")

addappid(2336221,0,"f3f120d62113945152c4dbc839727429765e41336f99fc3a1e125c5bdf43ec2b")
