-- generated by KeySteam
-- update time: 2023-04-11
-- app_name: Manic Archers - Bullseye DEMO

addappid(2339820)

addappid(2339822,0,"f9da1e4c104c2945065ee3a417ddce835b9dcf68c4711f1614d8365c23cf3cd8")
