-- generated by KeySteam
-- update time: 2024-11-20
-- app_name: FunnyPizzaLand 2

addappid(2000220)

addappid(2000222,0,"5f4129b6590bce7bc78b31d3738f05b24f3a597e529dd81ef44439ba77813a29")

-- DLC: 1/1

addappid(2213310)