-- generated by KeySteam
-- update time: 2025-08-25
-- app_name: ♡beAt! -After the Summer-

addappid(2002430)

addappid(2002431,0,"7aed5b31f331e7eded2442270ff656da4cd20d1fbd926fdcddbb18a7acd58db6")
addappid(2335470,0,"0c3282e1f66d3e860972a4d12cd54ff241ece006f191b32a776fd9f3e1224f6b")

-- DLC: 1/2
-- missing DLC: 3200450

addappid(2335470)