-- generated by KeySteam
-- update time: 2022-05-17
-- app_name: 2004810

addappid(2004810)

addtoken(2004810,"11254346221813027148")

addappid(2004811,0,"1f08210a64644b20a0a19a17a9539b309ffacac3ead90a4413f9c1157db7d137")
