-- generated by KeySteam
-- update time: 2026-03-20
-- app_name: 生死狙击2 Test Server

addappid(2009240)

addtoken(2009240,"17116560825963788096")

addappid(2009241,0,"06f6e034601513722dcf49be72791968a9e118fe105e407a8da2c270d5aa2c2c")
