-- generated by KeySteam
-- update time: 2023-10-10
-- app_name: LIVE A LIVE

addappid(2014380)

addappid(2014381,0,"7fda95293f7806c84dd40f809c1ec537ad42ad31989ceb136bd9815b627341d7")
addappid(2378630,0,"fc227986471c0ba10af08000a62d1676802df92afbfff6411ade394ae8c8dc34")

-- DLC: 1/1

addappid(2378630)