-- generated by KeySteam
-- update time: 2022-05-30
-- app_name: Rich Taste of Ecchi

addappid(2015260)

addtoken(2015260,"3621599600728284890")

addappid(2015261,0,"2fab1327a77144444087c36271e8fb604fe42dda44578ea1d5e706e1ff52500e")
