-- generated by KeySteam
-- update time: 2022-10-28
-- app_name: Burning Requiem: Fates

addappid(2016510,0,"906a370c5391982b366aebd1990ba116f5a7913b474c52ac539fd9c2fa458244")

addappid(2016512,0,"9e9e243d1638022c94d9d9ace005e8757f745c4af1cca9f4d3ba23c8ee1d8e64")
addappid(2065301,0,"882387e1260ec5d4f8913eaba39071f5ec9caa4a7f1c66e3e69ccc2e19bd8bee")

addappid(2065290)
addappid(2065300)
addappid(2065301)