-- generated by KeySteam
-- update time: 2026-03-28
-- app_name: Scope

addappid(3700410)

addappid(3700411,0,"B58CBEE3D4AD208A9C2559170092302E8A66575F96EF3C9A21C7ACD1DC1B7120")

-- DLC: 1/1

addappid(4366310)