-- generated by KeySteam
-- update time: 2025-07-03
-- app_name: 悲剧的精灵

addappid(3700370)

addtoken(3700370,"9861168376806535901")

addappid(3700371,0,"6bc9bed2dc4706819006aa8ec213e7d41968e35e508cd9dfa9d09ff174bc772b")
addappid(3700373,0,"4c45f7de0192fb511b922bf2d9a54414394ef02a7d30ba4cebeade09f22d933c")
