-- generated by KeySteam
-- update time: 2025-05-18
-- app_name: Rumours of a Roman Empire

addappid(3716280)

addappid(3716281,0,"013ddb5e9e75e0e3cb379d140b568e92e35ce32474cbb914a2564ea1ee02bef6")
addappid(3750180,0,"9ee66d65ca4ec3231b84f5d77e662e3e4d55b05a841303af306a177bef021c0e")
addappid(3750200,0,"b048cc1aab4dcc69614443cf8d39e5d8d092a0d75fdfdd864b87e196f0da452e")

-- DLC: 2/2

addappid(3750180)
addappid(3750200)