-- generated by KeySteam
-- update time: 2025-05-20
-- app_name: Air Traffic: Greenlight

addappid(1861880,0,"368e2c773d793cbaeb9edc2bb46d1275cbe1826822b5269e795b4c05fd53dff8")

addappid(1861881,0,"dcd1681a7b335a37d70b6776e85874328a6f793ddd3f30c8c9850082922231c0")
