-- generated by KeySteam
-- update time: 2022-07-24
-- app_name: Mysterious Adventure of Michael 2

addappid(1866840)

addappid(1866841,0,"2c141fa320d067765d7b215f6a7ea105b4606a6daeb9dd48219956ec1d60271d")
