-- generated by KeySteam
-- update time: 2025-01-20
-- app_name: armageddon war: old era wreckers

addappid(1867550)

addappid(1867551,0,"0cddae4076ee72d8729ab966e2ea0ec3ef82b526a96c0cabc0c7857ba4a59322")
