-- generated by KeySteam
-- update time: 2022-01-14
-- app_name: Crossroads: On a Just Path Collector's Edition

addappid(1868550)

addappid(1868551,0,"e78ca161f3f32c1d69b786d124e11fff53cb0a7cc83b1d4bd3125ddf538f4e3a")
