-- generated by KeySteam
-- update time: 2022-11-26
-- app_name: Tower Words

addappid(1874680)

addappid(1874681,0,"908a6d5bd5f9a26abaa4a4fce648189fe2b9ea241e48996ebdbec204a172bc61")
addappid(1874683,0,"56104705e0629aa436585467a6a7e895ecf85d3063b869c91aae6a15786956de")
