-- generated by KeySteam
-- update time: 2022-02-23
-- app_name: 1876250

addappid(1876250)

addtoken(1876250,"11507708563763401784")

addappid(1876251,0,"a550bcd9524c6ff5a9f2a301f90dbcdaeffe68dc8618b0f516a3a1c613e1fbff")
addappid(1876252,0,"5577cde553f0af0bec77fa9955e4a7fa60497e6cf9d70988530be362ec1102e7")
