-- generated by KeySteam
-- update time: 2021-10-26
-- app_name: Rorys Restaurant: Winter Rush

addappid(1801920)

addappid(1801921,0,"f72fac98ed3f2ae862972d5cf7541277a435861c028b83f591d7d753196e7223")
