-- generated by KeySteam
-- update time: 2022-08-18
-- app_name: 维斯塔利亚传说2：希尔瓦比西之圣剑

addappid(1811600)

addappid(1811601,0,"c8756ec9abdb4ee5f5ead8af843ceddad3644d0d47ab3a677c4df766a20eff92")
addappid(1811605,0,"dcc6667074f793012ef946f91343bfec0bc2d0c25c911e8985bfd509f4529b79")
