-- generated by KeySteam
-- update time: 2026-01-14
-- app_name: The Plague Doctor of Wippra

addappid(1811740)

addappid(1811741,0,"3a56f3af59475db5f9d5b4556535f61089b8b25c558f22a2bfe87569cc8351d0")

addappid(2167500)