-- generated by KeySteam
-- update time: 2023-10-25
-- app_name: Kickback Slug: Cosmic Courier

addappid(1814250)

addappid(1814252,0,"5560b25276914c599c768d92dbd99f2172b371362eafb61ee0b14029376a6579")
