-- generated by KeySteam
-- update time: 2022-04-28
-- app_name: 女仆骑士艾莉西亚

addappid(1815010)

addappid(1815011,0,"24854a1318f2a74b4d76f4bcdadc3c8c5e386fb19515bc115215a0e6a5e62349")
addappid(1815012,0,"88eac923267b988e18d4fc9613a59601b1e704ab8cf9ece400385c03ee7a49d0")
addappid(1965221,0,"cee0c9356ae0b11dc119a265fe5613bddfae5f36661a4adfd8d3e0caf1b4989e")
addappid(1965222,0,"c8203cd79a2533c352d0869a8cb57055b4f2786bb23fd2ffa1ffc620498a1623")

-- DLC: 1/1

addappid(1965220)