-- generated by KeySteam
-- update time: 2021-11-13
-- app_name: Splatformer

addappid(1815140)

addappid(1815141,0,"6a933a676722566bb85d38ca5400202b27230335369a00bf6966b432fda29463")
addappid(1815142,0,"809c1e1fbfff1019d5ff2bd21b2c841c4e7cc3486a29a2229a589e2ad2827883")
