-- generated by KeySteam
-- update time: 2025-09-28
-- app_name: Pinecone Game

addappid(1818150)

addappid(1818151,0,"0b2ef32720e4afdcf75d6795bf2d9889b3fcf1450496988eb868caf638f53248")

-- DLC: 1/1

addappid(2340490)