-- generated by KeySteam
-- update time: 2022-11-22
-- app_name: Ultimate Muscle Roller Championship

addappid(1818410)

addtoken(1818410,"10002313267698791492")

addappid(1818412,0,"C7A953F7C1AC479D3A055F1F29420E74B66441E1C629E82D6FD95B244691182D")
