-- generated by KeySteam
-- update time: 2022-03-15
-- app_name: Draft Day Sports: Pro Basketball 2022

addappid(1819870)

addappid(1819871,0,"f709b45a963adf6fe89df0bf5919852f6c48f67529e1a7e4c0c107a0c6c6f27e")
