-- generated by KeySteam
-- update time: 2021-04-29
-- app_name: The Signifier Director's Cut

addappid(1082930)

addappid(1082931,0,"553e921b25e671919b403d536245861ee14d6ac6a3ba68fd3a9165eba981b2df")
