-- generated by KeySteam
-- update time: 2020-07-29
-- app_name: Winter Resort Simulator

addappid(1089790,0,"401743cb673eb8049b65b25a42ede2a21f3c6149395eac780f594dbcb205c3e7")

addappid(1089791,0,"c7cfd0362a6faf917cf564bc5f978931ad96e584f8fe0b0a72878d3f3977dc69")
addappid(1294390,0,"67e54a4e56453712c90afca17150c2e0a06f7520ab836d9f83cc1d79fdfffc4e")

-- DLC: 1/1

addappid(1294390)