-- generated by KeySteam
-- update time: 2026-01-06
-- app_name: Asteroid Run: No Questions Asked

addappid(1090030)

addappid(1090031,0,"954fdf30bd0756c681be5042545b33d122d4955bc6374f0670cedf8f446b1852")
