-- generated by KeySteam
-- update time: 2019-07-26
-- app_name: Coffee Runner Black and Mocha

addappid(1092830)

addappid(1092831,0,"a746afa0748bf1554c14d499a3595050d3798109f3d24ac55235e2282d2319f3")
