-- generated by KeySteam
-- update time: 2022-09-14
-- app_name: 彼岸晴空

addappid(1094920)

addtoken(1094920,"2640977931433120032")

addappid(1094921,0,"ad47ab3ec0c2c84e27c8be94a6810ddcaf42718715aa120bfb0246d0cf27a9ab")
