-- generated by KeySteam
-- update time: 2019-06-13
-- app_name: 故郷をさがす三姉妹/ The Three Sisters looking for their back home.

addappid(1094190)

addappid(1094191,0,"6eebaa0c68213c5d3a68a513b37d5edd7cca4362138ec82331c33aff40e61e19")
