-- generated by KeySteam
-- update time: 2022-05-30
-- app_name: 桌面萌娘2:魔法引擎

addappid(1096550,0,"af37925d51d73191b7d9986f9fae1529f5317bedaee3fee116f54a3f3596c460")

addappid(1096551,0,"1b205d4d13f527bf953207c14bae7e03cba734ee980f371d9f3aa23b01b33436")
