-- generated by KeySteam
-- update time: 2021-12-03
-- app_name: Mighty Fight Federation

addappid(1096690)

addappid(1096691,0,"F2E28F9AC99131B89EC500928BF2E8D6942BD72EC4C05E3EA8174BF77B7B082B")

addappid(1700750)