-- generated by KeySteam
-- update time: 2023-01-07
-- app_name: 暗影火炬城

addappid(1330470)

addappid(1330471,0,"90bde5ea2666baa460c9476da114f0a78a6b63f314fcfb7456c0f499841e5dfb")
addappid(1330472,0,"2ee73d4dd8b85b4d1601563faf22a7a679a33f4fafe1766746e8e448e4a79bcb")
