-- generated by KeySteam
-- update time: 2026-02-25
-- app_name: Becastled - 月兽围城

addappid(1330460,0,"0b6bd5f8a9d69ab3bb3d7b7c2a60509fec82e0e8618062c62230785f71e63733")

addappid(1330461,0,"2f315404e0292ce573c52729ebbfa7921f02ec79592f67bb9a761a9a63c97c76")
