-- generated by KeySteam
-- update time: 2021-01-28
-- app_name: Gladiator Guild Manager: Prologue

addappid(1332470)

addappid(1332471,0,"a7fbaa17953591bfab10582898b9fe25b86ca8efc67372b01b36bd99d16ca6b4")
