-- generated by KeySteam
-- update time: 2021-08-20
-- app_name: Kaapelipeli: The Cable Game

addappid(1335350)

addappid(1335351,0,"f6a1d54a2ceb7f850ef108b9f2fa8325ef221b7c37f1a3370fd7ef50541cd651")
