-- generated by KeySteam
-- update time: 2026-04-02
-- app_name: 电视台模拟国

addappid(1338030)

addtoken(1338030,"13310321601085722540")

addappid(1338031,0,"3683c6aa34c6d5f71b5f86ff1d5306bc19d9ea041016bcac947fe6b6d4f5540c")
