-- generated by KeySteam
-- update time: 2023-01-12
-- app_name: 阿尼艾丝的工房

addappid(1684480)

addappid(1684481,0,"139faccafe8f96ab69365c0bfd9663ce9a4a3774ee7cee4ec26eca6ce709312f")
addappid(2323252,0,"182ffa6cace609deb6f10c944570d8078b81e7c61f8351eb5e23ad962ad6aeaf")
