-- generated by KeySteam
-- update time: 2022-06-23
-- app_name: 1685470

addappid(1685470)

addtoken(1685470,"6741153437633478923")

addappid(1685471,0,"a5b12625bd5e532b3a16934951860adefd0c6b6d7dda5414daf40426edf44bb5")
