-- generated by KeySteam
-- update time: 2021-09-17
-- app_name: Unholy Alliance - Tower Defense

addappid(1689220)

addappid(1689221,0,"85c7cdcd5b3b55725a16f1557555914d1e3cc936347745acd9784f9f57b18bce")
