-- generated by KeySteam
-- update time: 2021-07-16
-- app_name: Paranormal Files: Ghost Chapter Collector's Edition

addappid(1696040)

addappid(1696041,0,"c0b41ccd5cbe1239399a7d014529d9a8e38e800ea8c7d15b7832e1e40a15e3e1")
