-- generated by KeySteam
-- update time: 2025-12-20
-- app_name: Aeon's End

addappid(1063580)

addappid(1063581,0,"08ad1e0a465543f8e67d3c90d86c35b17065cc3d671632d03d04307f1082d42f")

addappid(1179230)
addappid(1321770)
addappid(1596830)
addappid(1736700)