-- generated by KeySteam
-- update time: 2020-07-31
-- app_name: Cartoon Network Journeys VR

addappid(1063530)

addappid(1063531,0,"ee8435a191bc6c3dba99e02c9f12387ffab2563d1e758f8cbdacb70dd432133b")
