-- generated by KeySteam
-- update time: 2019-04-10
-- app_name: New Yankee 7: Deer Hunters

addappid(1066700)

addappid(1066701,0,"69c4c73b8564226168fda871efed46b206e6a8669cc4f5e9bc12f0cd709339d5")
addappid(1066704,0,"03f074a57606265fbaa9b3a99ce2414618c7b977db20a4d08dd8794499a4e95a")
