-- generated by KeySteam
-- update time: 2020-12-07
-- app_name: 洛基：北欧怪奇之旅

addappid(1067540)

addappid(1067542,0,"b1ea89da87ef88ae5869d6b6f0a8819f556a88248db30ff43230bece5de1bfb7")
addappid(1402610,0,"886c1d4da026da531c5933d5b0c387f1c88d591577eb23bcf2d00705cf5a6617")

addappid(1402610)
addappid(1402620)