-- generated by KeySteam
-- update time: 2025-07-18
-- app_name: META REVELATIONS - RING SPIRITS

addappid(1067030)

addappid(1067031,0,"d339facbd4a82f9a53fa5d188c3f818974ed49b27c782d39c11b578d274eb7d4")
