-- generated by KeySteam
-- update time: 2026-03-05
-- app_name: OVR Toolkit

addappid(1068820,0,"497d3631e03efd5431847d78de22db53c7315f734d838831b0bea7490cdcaa6a")

addappid(1068821,0,"b1ac70eb9afc949e0644b8f68791b30974d10d6976185dc44402eef72124e49b")
