-- generated by KeySteam
-- update time: 2025-10-27
-- app_name: Ultimate Admiral: Dreadnoughts

addappid(1069660)

addappid(1069661,0,"2ac313c2c0171e5f729d2433e47d343eba402d3d3440484e74b2731db0368126")
addappid(2672570,0,"21b720441f5fccf705c1bd037a0bbd0b8c817964c20bd281dbda5bb74dc173f0")

-- DLC: 1/1

addappid(2672570)