-- generated by KeySteam
-- update time: 2019-09-25
-- app_name: Morningdew Farms: A Gay Farming Game

addappid(1069390)

addappid(1069391,0,"2057cefeeaea92b7c4cd09e30756a437478d2a6ed9ba1a2ff4b76ce892abd8fa")

-- DLC: 0/2
-- missing DLC: 1154280, 1160990
