-- generated by KeySteam
-- update time: 2020-06-27
-- app_name: America's Retribution Term 2

addappid(1072350)

addappid(1072351,0,"d4703e827de8f6bc85e5142c2d777c6bba15671109dddb5bc5121592adc450bb")
