-- generated by KeySteam
-- update time: 2019-06-09
-- app_name: Quest For Wartorn Brotherhood

addappid(1076830)

addappid(1076831,0,"4a24189f4e7e4ddc88da2a6d19e61bc6b31711415c73a7e9bc95a5614684acc6")
