-- generated by KeySteam
-- update time: 2021-11-24
-- app_name: Critters for Sale

addappid(1078420)

addappid(1078421,0,"5ced3d1b6b07ca4f0b8763c92f6ba3b1f2aeed7bbce48895ed242e5dfaca22eb")
addappid(1078422,0,"d6a61b30148d61ce04d4feb25f3eb280b732e9ecdeabe9d97f77da1aeda69cf1")
