-- generated by KeySteam
-- update time: 2026-01-12
-- app_name: 植物大战僵尸™：重植版

addappid(3654560)

addappid(3654561,0,"6fc167060f8d59e04b1336aa831531599eba25b5d81a6d659408e1d69b65b456")

addappid(3802680)