-- generated by KeySteam
-- update time: 2025-09-19
-- app_name: Four Divine Abidings

addappid(3655580)

addappid(3655581,0,"23C4B597CB7B6AE18C07660D8A21B8B7858B82783C7B29DF05D159672521D076")

-- DLC: 1/1

addappid(3834680)