-- generated by KeySteam
-- update time: 2026-01-16
-- app_name: Deep Space Exploitation

addappid(3656660)

addappid(3656661,0,"15339c036cbe4ee3c6b600fab91511cc93581d1b0dfa5b742f8fdc14a3c97bdc")
addappid(3656662,0,"bad14bcfc7367d8a21087dae0bdccb384433c7d443ecf11110c3366c97596e70")
