-- generated by KeySteam
-- update time: 2019-04-26
-- app_name: Prologue For A Vacant Kingdom

addappid(1040490)

addappid(1040491,0,"319f8e592773c708e6688b777bce66f17ad05938bf22025aa3691b6c3094d712")
addappid(1040492,0,"bfdc0a47318db0da81a1f3629a91bd6e8f4120d471a728198b9ec6aa45026109")
