-- generated by KeySteam
-- update time: 2020-04-16
-- app_name: The Walsingham Files - Chapter 1

addappid(1045850)

addappid(1045851,0,"cf7cf4f22ab8332159ca7d081546b279fa3a35a144a0531adc2947fa1789b672")

-- DLC: 0/1
-- missing DLC: 1054960
