-- generated by KeySteam
-- update time: 2019-09-30
-- app_name: Kao the Kangaroo: Round 2

addappid(1048540,0,"047675a31987ac550d3da57c60e15c45b5d4dde91aee5b42e9c8430f38ab32ed")

addappid(1048541,0,"2a805f50e38282567abf3c50a4e61e11886633220e2b88399ec25c87db6038c7")
