-- generated by KeySteam
-- update time: 2019-04-22
-- app_name: 火柴人和七色彩虹 Stickman's Rainbow

addappid(1050690)

addappid(1050691,0,"d13a612237027309f2fcf43d0269e23dec73f2fcc22c3103cd4efae04118d2e0")
addappid(1050692,0,"dad06ae741bf508322664d45240c310f7ea3e6b474699939759ba57297f02cf9")
