-- generated by KeySteam
-- update time: 2019-12-26
-- app_name: The Artefacts lost in the Galaxy

addappid(1052750)

addappid(1052751,0,"52727fd5d58d77ed0c99bc6de48f2dad7d8c70ba2b6cd9e254a3d763173d02dd")
