-- generated by KeySteam
-- update time: 2025-06-23
-- app_name: Shopkeeper: My First Supermarket

addappid(1057580)

addappid(1057581,0,"dfbd523da2b80719c9a5c0de76ceab3033dfbdcae123d82df6852ba73d551a9a")
