-- generated by KeySteam
-- update time: 2021-03-04
-- app_name: Ritual: Crown of Horns

addappid(1059150)

addappid(1059152,0,"55ecab879eb55e91594900345cdf8923e103a3ee0f0351314f19d0e1edf2c108")
addappid(1179130,0,"e279fdc371ce670ebd2bc34f1e056d9a8c57744a3fc1071137a415d8a70b1154")
