-- generated by KeySteam
-- update time: 2021-01-10
-- app_name: When I Was Young

addappid(1059230)

addappid(1059231,0,"d7c2c05ed5898548ecc634660e3e8e321d7e270da7c51eff07d34df5ffae5e48")
addappid(1115940,0,"b22006df3fbdce1fb8458dc05ce32774e7c16bf4e4c9cc9831d83be56badcf4b")

-- DLC: 1/1

addappid(1115940)