-- generated by KeySteam
-- update time: 2018-08-24
-- app_name: Ghostly Horizon

addappid(700590)

addappid(700591,0,"84d4266e50653c56211916e282d08cc9b83e7ff008f94865c416ac6002f37308")
addappid(700592,0,"60925142579ef850257d7f2dbfade693ee729ca45735dae17d9f34b57b5fe74f")
