-- generated by KeySteam
-- update time: 2025-12-08
-- app_name: Paper Shakespeare: To Date Or Not To Date?

addappid(702940)

addappid(702941,0,"931a64f8377dc16187dde6995f68dc0fefaa6596deaa334e04cc1c745b465032")

addappid(711960)
addappid(731980)
addappid(836380)
addappid(842670)
addappid(843600)
addappid(878830)
addappid(890490)