-- generated by KeySteam
-- update time: 2026-04-07
-- app_name: Castle Clicker

addappid(704040)

addappid(704041,0,"1a47fd4d018480cf6e48f8342acb811c17be5e29073f239a378b32bcc8eb6b84")

-- DLC: 0/1
-- missing DLC: 2394860
