-- generated by KeySteam
-- update time: 2017-08-30
-- app_name: 707600

addappid(707600)

addtoken(707600,"5632231295858116993")

addappid(707601,0,"652f63bfc288823f1fd86cd075c6e1cefe76ce21c523b3cce4c16f9deca4add4")
