-- generated by KeySteam
-- update time: 2026-01-07
-- app_name: Mr. Barrel

addappid(713380)

addappid(713381,0,"4d1f13bb8bf662b6871a6adfcf6c9bcda34e4a599c673f79aa5257779a6c2a7a")

-- DLC: 2/2

addappid(815020)
addappid(1122530)