-- generated by KeySteam
-- update time: 2020-08-18
-- app_name: Goblin Storm

addappid(713840)

addappid(713841,0,"53d3e711040ca11a49a6756728d36c9ee68a70db958575c66a11283aa232d44b")
addappid(827440,0,"af6d6ecf765d850abfa0eefb3f01bcdf1e754ef791dacda1faf87d0c76b4d2b3")

addappid(827440)