-- generated by KeySteam
-- update time: 2023-05-22
-- app_name: 冰封之焰

addappid(715400)

addappid(715401,0,"137ac76cbbb80df9e88bf9287ca2973bd41e26ac5793c5d2aaffd8290b899438")
addappid(2221360,0,"cf70e6d7e0b70788d68f94419c99624352c248b7dc59be80a149846bf8865c85")

addappid(2221290)
addappid(2221300)
addappid(2221310)
addappid(2221320)
addappid(2221330)
addappid(2221340)
addappid(2221360)
addappid(2358760)