-- generated by KeySteam
-- update time: 2018-03-08
-- app_name: Galactic Lords

addappid(716230)

addappid(716231,0,"3afa597064d5f5e262b823334a0b2a78a90ebb7d50cc78bfaa62a980daea583f")
addappid(754650,0,"1ba53dc41144bafe077410b98652c0ae8ff0e0475b154ad497e1e8252dace455")

addappid(754650)