-- generated by KeySteam
-- update time: 2026-03-30
-- app_name: Reign of Guilds

addappid(716350)

addappid(716351,0,"900749c5f46586cd9c823732b9e377672e55bc0f53bf3f49e37d31f0d19bb713")

-- DLC: 5/5

addappid(2587000)
addappid(2611870)
addappid(2611880)
addappid(3223340)
addappid(3223490)