-- generated by KeySteam
-- update time: 2017-09-16
-- app_name: 717370

addappid(717370)

addtoken(717370,"2745327650328262357")

addappid(717371,0,"0d4d3c34db8260fae37d479a9f5180b92c97d3bee0cce84918a0f155f94ccf63")
