-- generated by KeySteam
-- update time: 2017-10-01
-- app_name: Daemonsgate

addappid(719300)

addappid(719301,0,"5aca294ce324435a4ab37138e37fb208acbe1df5cc8d6d88da9b3f38e9a824b1")
addappid(719302,0,"cc78e27271ae72986698afacd98bacd5ad834451ce0acdb730cf4057781cb45e")
