-- generated by KeySteam
-- update time: 2021-10-20
-- app_name: Megacraft Hentai Apocalipsis

addappid(1780060)

addappid(1780061,0,"528265eae6af76aba5e7d5fe0302ae428084f03e5922d2fd8d6f0bf801719807")
