-- generated by KeySteam
-- update time: 2021-10-17
-- app_name: Fantasy and Girls

addappid(1782320)

addappid(1782321,0,"173350fa72a189e246fc3017f1672356391624f067976cf32a91aa527ab61c57")

-- DLC: 0/1
-- missing DLC: 1794500
