-- generated by KeySteam
-- update time: 2026-02-27
-- app_name: 鬼怪传说

addappid(1783280,0,"edf6c615d27d3eb9f56a9d3ccf1580b37318df2f9729d0dadf40b528a6eefcfb")

addappid(1783281,0,"0d1ead4cea09777b847e74d2023f5cdaa28eb5b0ea6a0c85245014f7dbd521aa")

addappid(3204010)