-- generated by KeySteam
-- update time: 2024-06-18
-- app_name: Like No Other: The Legend Of The Twin Books

addappid(1786480)

addappid(1786481,0,"e8f34607bdcab1be0cf81da2352b1fe352d56537cd8026082252c6f013159a7e")
