-- generated by KeySteam
-- update time: 2023-07-27
-- app_name: 你已经猜到结局了吗

addappid(1788850,0,"c1445b4654266eb9f290b215629b5a843bcce98e8ecbb9583f81aafbdcf4d7de")

addappid(1788851,0,"734df2f28139f8a71a32ef69c370b6a4f154de5d9284b4f5a5d9e18757210f3d")
addappid(2052360,0,"9d825169961a024c0c9370736b2a5c9c1bcabc283cf6b17e6b6e3b8f2294be7d")

addappid(2052360)