-- generated by KeySteam
-- update time: 2021-10-18
-- app_name: Fantasy Sliding Puzzle 4

addappid(1795080)

addappid(1795081,0,"4d18e823de81a58082fa9c30bc52108b0f8435644e55348e711685c8be24be9d")
addappid(1795650,0,"97fa9a7350156214bae75d4692e5deea8f57146a6dac42cd505ee378524124e7")

addappid(1795650)