-- generated by KeySteam
-- update time: 2021-10-19
-- app_name: Nekomimi Nikki

addappid(1796510)

addtoken(1796510,"6867854418712726566")

addappid(1796511,0,"b881321c9598a19bbfe7947e053067197e5e11fe7f56cc5af9c43742dc1ca090")
