-- generated by KeySteam
-- update time: 2021-12-07
-- app_name: Math+Sticks - Coffee Break Club

addappid(1799160)

addappid(1799162,0,"b1bb5f4ae86fd260f206ff74ff8fc6ce23470a78e81eb281e99521ef05d80d88")
