-- generated by KeySteam
-- update time: 2021-05-05
-- app_name: The Legend of Bear-Truck Trucker

addappid(1581580)

addappid(1581581,0,"52dcd9d6953027835343a0c767a9b7bfac88fc4468096f2e404fe37dfe4bdbf5")
