-- generated by KeySteam
-- update time: 2021-06-08
-- app_name: Rounded Hills

addappid(1582160)

addappid(1582161,0,"82355a4932e5432eca1e121656ae93d8c683c310948c4143ff71e6f43300ca20")
addappid(1582162,0,"3d9265e5bef05776c817267dc94a05e30a1bc6703474c70a0bacf784e2bf9fca")
