-- generated by KeySteam
-- update time: 2022-06-03
-- app_name: 1582390

addappid(1582390)

addtoken(1582390,"11328531627297403255")

addappid(1582391,0,"7d413f1c6d6f1ac91865a75fa12fb88391bbe8c484eda4103a5d21e7371f62f7")
