-- generated by KeySteam
-- update time: 2026-04-05
-- app_name: Meat Beating: No More Horny

addappid(1583390)

addappid(1583391,0,"c0737af744e63b9b0bc57ce7dd38bce676e1225c524fc1b2fce568cac9aff29d")

-- DLC: 0/1
-- missing DLC: 4333970
