-- generated by KeySteam
-- update time: 2021-04-16
-- app_name: 1585580

addappid(1585580)

addtoken(1585580,"15617073103165555861")

addappid(1585581,0,"56fc63033d18b6c154d5a00e3549a5b398e43dd5a36e68791d15b592b6fd903d")
