-- generated by KeySteam
-- update time: 2021-04-05
-- app_name: SUPER DUPER ISLAND ADVENTURE

addappid(1587500)

addappid(1587501,0,"0f1df3993c9e6261d3a21b75fe099c11f60e19f6caee88b7daebfe766f2c6fe6")
