-- generated by KeySteam
-- update time: 2021-03-27
-- app_name: Mind-Blowing Girls 2

addappid(1588950)

addappid(1588951,0,"2dcd34d991ab033c2d7809d3792d42b43c97ac7da08fb0436690fe074b9d9a41")
addappid(1588970,0,"62aa73cea4267d6931cce0422dcb3e1989e2846c22c436a93e8a5f0b9d181fe1")

-- DLC: 1/1

addappid(1588970)