-- generated by KeySteam
-- update time: 2026-03-30
-- app_name: Dungeon Alchemist

addappid(1588530,0,"d6bfc7b359f0478577da4da12c403c8465eb3d5587847588f50adafa3380fea3")

addappid(1588531,0,"a9d28558cd0686aa83b4c6a439b5fed7f391983302c52bc7b8229c935c2e1aa0")

-- DLC: 1/1

addappid(1930700)