-- generated by KeySteam
-- update time: 2026-04-01
-- app_name: Depths Of Horror: Mushroom Day

addappid(1590840)

addappid(1590841,0,"17dd82949e7d040fd9977dd1114bd67d6507a76a6e6a101984c2413542a3325e")
