-- generated by KeySteam
-- update time: 2026-01-28
-- app_name: Anarchy: Wolf's law : Prologue

addappid(1592680)

addappid(1592681,0,"5239a1c4ee6c72861fb6c2da962605467648d880f7282f92418fe0405868035f")

-- DLC: 4/4

addappid(1668070)
addappid(2191520)
addappid(2192580)
addappid(2292480)