-- generated by KeySteam
-- update time: 2026-03-23
-- app_name: 工业巨头 (Captain of Industry)

addappid(1594320)

addappid(1594321,0,"4ff3d26a9ec89b9d17aa43ee05ea46cb83cd638a31b36a385b43fc810ccc6703")
addappid(2004740,0,"99e976dbccd9e46b15b201695ea57868cd42725d13bb6fc4512e5f3a7d620687")
addappid(4349830,0,"06605130aff9e40092bf43024ef429e6fd4c60c5da7f397898598e936d14e8a6")

-- DLC: 2/2

addappid(2004740)
addappid(4349830)