-- generated by KeySteam
-- update time: 2026-04-15
-- app_name: City20

addappid(1597980)

addappid(1597985,0,"69bc62e3db157c7aa6c2630c3e39c77f0bfe909eef1ee33952712b8ff79fb593")

-- DLC: 0/1
-- missing DLC: 3216560
