-- generated by KeySteam
-- update time: 2021-04-06
-- app_name: Grim Tales: The Final Suspect Collector's Edition

addappid(1597330)

addappid(1597331,0,"52a513eee2b146369c3b398f024034fb29dc20f534346aa8356df842ae2eb7d3")
