-- generated by KeySteam
-- update time: 2021-07-17
-- app_name: 见习侦探

addappid(1598930)

addtoken(1598930,"13690532672455026920")

addappid(1598931,0,"2174cae4885bbc5acc5cea1b2fda8c1ff2d9acf7151bb4d71d8d5a11ab2241ff")
