-- generated by KeySteam
-- update time: 2021-09-24
-- app_name: Puppy Adventure

addappid(1599230)

addtoken(1599230,"10618532469834091884")

addappid(1599231,0,"f7b98dbb478219af1f7586077b096d79be24683594d9a021cae5a1cdfa3bf8b7")
