-- generated by KeySteam
-- update time: 2026-03-08
-- app_name: Fight Life: Vanguard Playtest

addappid(3188850)

addtoken(3188850,"1445731646301394029")

addappid(3188851,0,"5833c0be521e0638da48a15d1a0864a6403788e8dd2b7a4c40d9c6ec6aaa1a5a")
