-- generated by KeySteam
-- update time: 2025-03-08
-- app_name: 快盗天使双胞胎 〜时间与世界的迷宫〜 Re:light

addappid(3192560)

addappid(3192563,0,"449e3d539a3143f6bd0cdd3aeeee12d0c88194c17d93b99b807581c3c87020b8")

addappid(3524190)