-- generated by KeySteam
-- update time: 2026-04-02
-- app_name: White Knuckle

addappid(3195790,0,"71406315e98d9557deca70bc8f2beb2d7464a0f461ab40b9102675941d4a80cd")

addappid(3195791,0,"5ca40880a5993420bafa2b8361350f6f806bc4ad220384095505b4b65a35209e")
