-- generated by KeySteam
-- update time: 2019-11-23
-- app_name: Let's Explore The Jungle (Junior Field Trips)

addappid(363070)

addappid(363071,0,"01ccdb36a1d90316d8d88be62a5c4ccf436a4854c3c6a9465cac2daf58583685")
addappid(363074,0,"cfa2ce1fd537d44afd543700b8524c5a0d6a39eea2ea1f5b0580d85a6f024f6d")
addappid(363075,0,"21f5af4805b058b9561ecfee7b25276026162265d5566bc35e6e5309f40bd951")
