-- generated by KeySteam
-- update time: 2016-09-13
-- app_name: One Manga Day

addappid(365070)

addappid(365071,0,"d6c8e084b7644bfbb142d80d64bbdadd622d38818c43bba62036609fce97fcec")
addappid(431980,0,"8d12ca21253b452bce4865292ab47fe56c6b7795ab360ee3265d1180e11b2c05")

-- DLC: 2/2

addappid(367380)
addappid(431980)