-- generated by KeySteam
-- update time: 2020-12-21
-- app_name: Controller Companion

addappid(367670,0,"eee899d2a1baab75fbd66806d3871b6dd8383e873e9c1dcd505604581bb81400")

addappid(367671,0,"3bc0ccfdf6aa8ad040b70e6aa2b778caa5d18060e0e407efdf18db55f44a1739")
