-- generated by KeySteam
-- update time: 2025-10-13
-- app_name: 咖啡店大咖 Coffee Shop Tycoon

addappid(370060)

addappid(370061,0,"f6ad58df88788704b9bb1782aaed27fd610a8eb555045347272898e6c9dd0277")
addappid(370062,0,"1e15aec6adc76bc2e89263f3911e6c6c6d2d9fc213a9d3c2472e727830757c4d")
