-- generated by KeySteam
-- update time: 2022-08-08
-- app_name: Wyrmsun

addappid(370070)

addappid(370071,0,"7733aa7dcb2fb0761c983eba90fa4b65c7e12971ad8dfb04547c5a206392cf84")

addappid(445340)
addappid(445341)
addappid(645220)