-- generated by KeySteam
-- update time: 2020-05-28
-- app_name: Dark Future: Blood Red States

addappid(370870)

addappid(370871,0,"19a10d1edd8ff00afe1e2599c99dbc6df6a052713f8d0910b3f8a0367b5fabcf")

-- DLC: 2/2

addappid(1084700)
addappid(1084701)