-- generated by KeySteam
-- update time: 2016-06-18
-- app_name: Bernie Needs Love

addappid(373120)

addappid(373121,0,"b440930f7ed65ae7eb2adb60588bd49e10c0716eed9389e4fdf89c15c794e0af")
addappid(373122,0,"dfe174942be10b74cd96963bfc831d33d74dad36bc9aaa816f4b09fdf39af3d6")
