-- generated by KeySteam
-- update time: 2016-04-05
-- app_name: Blockwick 2

addappid(377660)

addappid(377662,0,"2fef3ddef32711d33f6251d76d7703fd3638edded1d4e76238545317144907b3")
addappid(377664,0,"1495c90ff664f4ada64a48f08a3e70d0cdb472ad62e0fef2030529e90855f7c9")
