-- generated by KeySteam
-- update time: 2025-04-29
-- app_name: A Coloring Break

addappid(3382500)

addappid(3382501,0,"446FBA6723170ECE98C1F80BDA6C4A96A7872A6DDC8ADAC07152249B722B4A14")

-- DLC: 11/11

addappid(3442480)
addappid(3442490)
addappid(3442500)
addappid(3442510)
addappid(3442520)
addappid(3442530)
addappid(3442540)
addappid(3442550)
addappid(3442560)
addappid(3442570)
addappid(3501270)