-- generated by KeySteam
-- update time: 2025-02-10
-- app_name: Urban Shadows Racing™ Tokyo

addappid(3396460)

addappid(3396461,0,"46fe289b6c66cb35e2c198b8725c400168a8315f9ce79364c1fa7bb57e318923")
