-- generated by KeySteam
-- update time: 2025-09-18
-- app_name: Detective Club: Gallery of Shadows Collector's Edition

addappid(3623550)

addappid(3623551,0,"5aed44ad527fa9c93882d7df2f88e294102604bde85d198e1523ded8eda0fcf8")
addappid(3948690,0,"90f85d6168b9308b0fcb969d2acdefd8690d7e8fd053e937615e0c7b52c24d6b")

addappid(3948690)