-- generated by KeySteam
-- update time: 2024-06-03
-- app_name: Animal Trainer Simulator: Prologue

addappid(2202220)

addappid(2202221,0,"838c0422a62016979aaee51365f8e11899dcd107d5923dc27a876ef6f7ee0c3b")
