-- generated by KeySteam
-- update time: 2026-03-23
-- app_name: Scourge Of War - Remastered

addappid(2205330,0,"6b562f37bd1d06ebcbb6d57f9e659578a0907f9221dc6968cd98cf56ca6a7cbc")

addappid(2205332,0,"53b677bd1c09ce8b076074bd7cb31e530faf10940692714aa754df801443ca69")
addappid(3136660,0,"19d0496fad42ac6e1ade7e711a52c1decb6951026d1e82bd62a8c90235dd97d8")
addappid(3136670,0,"1fb1f93185218c7d43b1a1f7b10c9d8004f5b52ad992130cc0115fa8f7fdfea1")
addappid(3136680,0,"f86467806e2ea11b8237728eec6f14f2cee09b70c4af6be6c63bfd0c5ca88dd4")

-- DLC: 4/4

addappid(3136610)
addappid(3136660)
addappid(3136670)
addappid(3136680)