-- generated by KeySteam
-- update time: 2026-01-23
-- app_name: Top Racer Collection

addappid(2214000)

addappid(2214001,0,"70070ece4f1e0d702c001aa27bd3a90fd923bb62d3e5ecb673649443a1733106")

-- DLC: 0/1
-- missing DLC: 3800320
