-- generated by KeySteam
-- update time: 2025-11-03
-- app_name: Kitty Survivors: Rogues of Catmere

addappid(2217740)

addappid(2217741,0,"026772f8d6ee37677d75c3da9f5e7dbc11f4cff882a64674424d0c8c5ca87849")
