-- generated by KeySteam
-- update time: 2025-07-15
-- app_name: 闭嘴，跳舞吧：特别版

addappid(2218930)

addappid(2218931,0,"b8659d1981fcc1defcbd6dacb72132f10b95627b2ac3af2ae249537a90512e40")
addappid(3024790,0,"81dc8d51fcdece129616d5f425923af2a199560a0773c98ef9abaf4dbfb04c7d")

-- DLC: 1/1

addappid(3024790)