-- generated by KeySteam
-- update time: 2017-03-05
-- app_name: Yeti Adventure

addappid(604810)

addtoken(604810,"5237405534876930666")

addappid(604811,0,"8e0db3435e86f7455cd7f6003688c1fb1d5b1c52a1304a998293894703ecab97")
