-- generated by KeySteam
-- update time: 2019-05-10
-- app_name: CRIMSON METAL

addappid(606960)

addappid(606961,0,"0178714416f0337d044ae001b33f16e6989a752de6624fef7a0775c52df539d1")

-- DLC: 2/5
-- missing DLC: 614610, 614620, 779520

addappid(614621)
addappid(1031750)