-- generated by KeySteam
-- update time: 2025-08-01
-- app_name: HAUNTED: Halloween '86 (The Curse Of Possum Hollow)

addappid(607490)

addappid(607492,0,"3c7a09baea84bb3892ebf9080f8ffe40591e4b1f25582cd19b674569d6183edd")
