-- generated by KeySteam
-- update time: 2017-06-24
-- app_name: 609180

addappid(609180)

addtoken(609180,"4725004609830874639")

addappid(609181,0,"0c5a2bfa5310b28c3e98beeef6bee5c94af821771e205c5dce987e62311a444f")
