-- generated by KeySteam
-- update time: 2018-03-02
-- app_name: Arcade Tale

addappid(618030)

addtoken(618030,"12445558775019160730")

addappid(618031,0,"18018b4d93749ea29c2d4ee969107d90d15244049358e97cf9b0a87573c3ba80")
