-- generated by KeySteam
-- update time: 2017-06-04
-- app_name: 618340

addappid(618340)

addtoken(618340,"5157895756992377022")

addappid(618341,0,"9da4fde4aed955e50b24e5b875843369c06b0198285a4becb00f50df506d021e")
