-- generated by KeySteam
-- update time: 2017-08-17
-- app_name: 619730

addappid(619730)

addtoken(619730,"17631494730563823138")

addappid(619731,0,"d95aeb4e6033bcae6a798ff8b3e0fb40f760e8802e4a3e31b04946e2cf299df7")
