-- generated by KeySteam
-- update time: 2018-01-29
-- app_name: Heaven Island - VR MMO

addappid(400250)

addappid(400251,0,"34ee9d6655c6505a5db0902f20a0852224d291396b20a361a85501a49b9561a7")
addappid(455470,0,"101ddee2d5da8c241c4886c68ba1962fbf339ce47e58df2e5b99e7c24c617f73")

addappid(455470)
addappid(573920)