-- generated by KeySteam
-- update time: 2016-04-19
-- app_name: Driver Booster 3 for STEAM

addappid(403040)

addappid(403041,0,"c11315336fa35bb14f33e13a8d443f3074e7df1916e6daca87cfa671387c42f4")

-- DLC: 1/1

addappid(412090)