-- generated by KeySteam
-- update time: 2024-01-29
-- app_name: Starward Rogue

addappid(410820)

addappid(410821,0,"5e56ee3f26e41ef2eb077d47c34a9ea136a2f61effcf740497a230d8ebe51db1")
addappid(410822,0,"a3ade7f14e75072602fed2db43c42151938063b1b8becfdd4128bbd2e6188c02")
addappid(767650,0,"a119aa2992262547087226c20183f4f3c253103c2c66ca612c4aa6d060dceff6")

-- DLC: 1/1

addappid(767650)