-- generated by KeySteam
-- update time: 2018-05-11
-- app_name: The FOO Show

addappid(411820)

addappid(411821,0,"690af99e79fa082336de039a63fbdcb198d21e818f47107ca735b555f0e04e1c")
addappid(411822,0,"f313f3185799439740d60a51390104ca9aacaf95776c8e43ffa468f7b13a2bd9")

-- DLC: 0/5
-- missing DLC: 593920, 593930, 593931, 593932, 625710
