-- generated by KeySteam
-- update time: 
-- app_name: Metal War Online: Retribution

addappid(412470)

addappid(228990,0,"44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8")
addappid(229000,0,"3aae9271fb93da5395ffbfe338d3647de5dcfab3fc6fb901ca2ec28849b3d6bf")
addappid(412471,0,"c14c8d708c8684f67d10eeffe87f790ff6b8912eadeac1ec1e950de36a0d9922")
