-- generated by KeySteam
-- update time: 2017-01-08
-- app_name: Rocket Fist

addappid(413500)

addappid(413501,0,"b095d91742ec808787f0648a45b4b0100ab0b09a2eeb09bb5b6ca7c572f44fb8")
addappid(473410,0,"38fec743a3549c075f8bb1fe1df5cf3a575c0e25966936a78e71065e9e339c30")

-- DLC: 1/1

addappid(473410)