-- generated by KeySteam
-- update time: 2020-03-31
-- app_name: Blue-Collar Astronaut

addappid(414760)

addappid(414761,0,"dc27c53a5701b6893d35ece8060767c18ad0f7d946f64d38ce9cfae2c6cca9e7")
addappid(616600,0,"9c02786b72dfe9bf7536ac6f537ca650efc0903063f5ba19b98ac73a7189fe07")

-- DLC: 1/1

addappid(616600)