-- generated by KeySteam
-- update time: 2022-09-14
-- app_name: Tale Of Tale - Hansel And Gretel

addappid(2082950)

addappid(2082951,0,"d0813ab11d04ad73d71e97aab9976726348387af9658c196637ae15b733ad86e")
