-- generated by KeySteam
-- update time: 2022-10-28
-- app_name: Miss Kobayashi's Dragon Maid

addappid(2086380)

addappid(2086381,0,"01f915a13f7628c96e7896c84bb3fbca3030ea71b037fa33e4ee3f8821fd528a")
