-- generated by KeySteam
-- update time: 2024-05-23
-- app_name: 温泉物语2 (Hot Springs Story 2)

addappid(2089450)

addappid(2089451,0,"43f9c70bb33eb9d0b264ada46b9b27dda12bcc016eed6f4bf1f4ea6875c7c63d")
