-- generated by KeySteam
-- update time: 2022-09-23
-- app_name: Steel Saviour Reloaded

addappid(2096800)

addappid(2096801,0,"a1dd2eb9a6890a32f01f32a811940568a0bde324c7f2018759bed2f0429e05f4")
addappid(2096802,0,"bfd5ad6817c5da601b193da6ab501f335295016c6b6562e45be0d4d9343a430c")
