-- generated by KeySteam
-- update time: 2026-03-31
-- app_name: 星之侵略者

addappid(2097570)

addappid(2097571,0,"162f5956918437b675aeb87b3b4b3392bb4b253d3d41aeb4701ffa463b0d1f1e")

-- DLC: 1/1

addappid(3632550)