-- generated by KeySteam
-- update time: 2025-01-28
-- app_name: Sattelite

addappid(3361280)

addappid(3361281,0,"54681b8a1e0a6d5db1cb8bd224c61f315b937ac18596e8cdda768d2654b23774")

addappid(3490110)