-- generated by KeySteam
-- update time: 2026-03-31
-- app_name: 理想图书馆

addappid(3372420,0,"e05ae15adadce2371a5a8aca13b9d3bab76e2900cf9b583c0df94fb3416d148e")

addappid(3372421,0,"91e80ef6816786129900aef7915ab66da7913c958ed6bbf675e904127d57583b")
