-- generated by KeySteam
-- update time: 2025-06-30
-- app_name: Tales Beyond The Tomb - The Farm's Secret

addappid(3374720)

addappid(3374721,0,"28dd8bb14e71b58196601970f55da06dac5e13330dba028f93fcfddee54f4714")
