-- generated by KeySteam
-- update time: 2024-02-22
-- app_name: Goat's Tale

addappid(1702180)

addappid(1702181,0,"b28c87395fd7fd381ce09deaa4835e455560c8923fa81d15c485ed014794139b")
addappid(1847090,0,"f3874ab014c6518c82489a6a2428b90f5c14f4d718452acf7cb9da41e5f1e1b7")

-- DLC: 1/1

addappid(1847090)