-- generated by KeySteam
-- update time: 2021-07-27
-- app_name: The Ancient Art of War in the Skies

addappid(1704640)

addappid(1704641,0,"f5e3f7040a93a84004066ac403181429b141873c8ecd5b72392082ac6cb440cd")
addappid(1704642,0,"491bc58fb6c6d0a13b55f1bb028c762d932e03f9d5113ac5db2d2541cf135969")
