-- generated by KeySteam
-- update time: 2024-08-10
-- app_name: Five Likes Please

addappid(1709320)

addappid(1709321,0,"F588666CBF52E61D493D43A9B602ED4C09735E7EFEC5D7B01F1E95A631FEEF33")

-- DLC: 2/2

addappid(2074280)
addappid(2256460)