-- generated by KeySteam
-- update time: 2025-08-23
-- app_name: BOT.vinnik Chess: Early USSR Championships

addappid(1711190)

addappid(1711191,0,"bb3272a682bfbffb0181a832a0c6cd0d48d347d58adedd564cee4245a61cd8db")
