-- generated by KeySteam
-- update time: 2021-11-10
-- app_name: 1713860

addappid(1713860)

addtoken(1713860,"4616198563445445673")

addappid(1713861,0,"87c2532fef0871a44e724b8e005ec2b4086521a9ef7cd6c67ac23a7c4ebaa663")
