-- generated by KeySteam
-- update time: 2026-02-10
-- app_name: 神之天平（ASTLIBRA Revision）

addappid(1718570)

addappid(1718571,0,"5340c7c9ef95f91f6e844d2e4f42b9b9a18b873a71a20516b0a1f23cb65c86db")
addappid(2669361,0,"d0945427a75897ebf551e5d57660b66c67e276511b1e0bef90039bf01c0e3de9")

-- DLC: 1/1

addappid(2669360)