-- generated by KeySteam
-- update time: 2022-12-18
-- app_name: Youropa

addappid(640120,0,"0e6e7e133c4b2e8756705474a0926a7f5967c3394aab83fc98516901f8eac2a9")

addappid(640121,0,"b71dcd6ae324547dffb978cdf4df0d3b0cf8b789ee3c39fe37bedaa73667b93b")
