-- generated by KeySteam
-- update time: 2020-05-27
-- app_name: BOXVR

addappid(641960)

addappid(641961,0,"defa24f8ae3f8e69cf198ef773e311b06c61f618d3a3079edaacc63f80d79d50")
addappid(641962,0,"44f8bd071e711b1a291c063586b9e652acd129cbb619f5befa516c8e73a59dd0")

-- DLC: 2/2

addappid(1281710)
addappid(1288240)