-- generated by KeySteam
-- update time: 2019-04-14
-- app_name: Pixel Devil and the Broken Cartridge

addappid(648440)

addappid(648441,0,"b72acadc2dcdc906fdf1821f93eaecbc7a69b815a6a225183b523ff6a192545f")
