-- generated by KeySteam
-- update time: 2020-04-05
-- app_name: Warbanners

addappid(650440)

addappid(650442,0,"ae5e1c76ccd91170a498a451fcb26e39f6fcf74c06c018a8932bc9f552741a6f")

-- DLC: 1/1

addappid(818700)