-- generated by KeySteam
-- update time: 2018-07-31
-- app_name: Tiny Town VR

addappid(653930,0,"0acc9d94d5e75e6d6d9153672d9afff8457c7fabed676bf505e746db0da0497a")

addappid(653932,0,"8c3d3c7df4b3f0f5c06bce6e886996cdb7e5ed68b44abb328ec1cd246a3a7e22")
addappid(885070,0,"7645db3b811103b456c927515aa8a54f77cd75c5574787ac81c976b200b83533")
addappid(885071,0,"92713d9003ef44a8b42be593458eae807f2735e33136dd416b89a4defcb098a4")

-- DLC: 2/2

addappid(885070)
addappid(885071)