-- generated by KeySteam
-- update time: 2018-03-15
-- app_name: 654650

addappid(654650)

addtoken(654650,"11510764554984539415")

addappid(654651,0,"83abbe29cc653d06fa0db91cb7bb3946d5cfc8d6227541a002486526b1b6b459")
