-- generated by KeySteam
-- update time: 2017-07-19
-- app_name: 656790

addappid(656790)

addtoken(656790,"17001814679606474211")

addappid(656791,0,"93f68e7200ad5076bfd2c898fcac860c23f6409ee96cf728f68192c2ec87b04e")
