-- generated by KeySteam
-- update time: 2017-12-06
-- app_name: Cybercube

addappid(656880)

addappid(656881,0,"b6ce96dce118799f716fbc0065ef2b166a5809f27ee8dea29abcbc94d6ba6713")
addappid(656882,0,"a3ab93da71bcc5ab5fec7d1af064a78cff9485fb941a27367924a48038ba2493")
