-- generated by KeySteam
-- update time: 2022-04-20
-- app_name: 战争机器人世界 《Warfare Robots Online》

addappid(659840)

addappid(659841,0,"e1b1561472dd7d3fa398c302b36f6fa58f8e0d99aeb5eb70beb3f2fbeb76b745")
