-- generated by KeySteam
-- update time: 2025-10-28
-- app_name: HEAVEN SEEKER 残酷世界的拯救之道

addappid(2865230)

addappid(2865231,0,"cacb7e2580465b9365628d8bdc5f9d64f6ab035b7234f4ce5860f58246b0d2ce")
addappid(3227440,0,"e1a4b6d5573fb3fd7b897dc24160949ccbb3349d989fb0fbfe84cfc028f85b96")

-- DLC: 1/2
-- missing DLC: 3508810

addappid(3227440)