-- generated by KeySteam
-- update time: 2026-04-10
-- app_name: Cubed and Dangerous

addappid(2870580)

addappid(2870581,0,"b06d96787bf753259a791ca5ad5dfe001ec6fd828585000d036ad6c4fb6a1ed4")

-- DLC: 1/1

addappid(4119790)