-- generated by KeySteam
-- update time: 2024-08-09
-- app_name: Wind Rider

addappid(2874290)

addappid(2874291,0,"FA03DC7ED15F5CD79F1A2687DCC92B7DA5299E2EEE9BDA036ECE68BFCE70B6F9")

addappid(2942200)
addappid(2942210)