-- generated by KeySteam
-- update time: 2025-02-26
-- app_name: 哈利·波特：魁地奇锦标赛

addappid(2878600)

addappid(2878601,0,"1f592e4f58b2197dbdc21348883475d72796385505b5ee13ae0e5cd7fc4142a4")

addappid(2922880)
addappid(3105320)