-- generated by KeySteam
-- update time: 2026-03-08
-- app_name: Mannequin Character Generator

addappid(1280420)

addappid(1280421,0,"70f61105b645192b0611a9f846ff09f52918aa66c4756760a6cadd70ced4ff0c")
