-- generated by KeySteam
-- update time: 2020-04-11
-- app_name: Asura Girls

addappid(1284790)

addappid(1284791,0,"f0c7b48f0f60f113abf3764f0ad3b042f3b974609716082bfae17765e0f4e906")
addappid(1290870,0,"dd0d33ff050628bd1430ea46f85af5c8fcbae3494d7f2d3fa8ef22c86689d823")

-- DLC: 1/1

addappid(1290870)