-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: Maneuver Warfare

addappid(1285180)

addappid(1285181,0,"35f59e403d5f9997934b1f2d260e1ac2fbf8e79ef1c57a6512405f5fb7b57346")

-- DLC: 4/5
-- missing DLC: 1515680

addappid(2058930)
addappid(2437200)
addappid(2461720)
addappid(2894190)