-- generated by KeySteam
-- update time: 2020-11-02
-- app_name: String Tyrant

addappid(1286980)

addappid(1286981,0,"85642b3781601d0ea98e6167749dbe59789a0f5fae8262d8abe3c47888e21fbb")
addappid(1286982,0,"c85be2c6f1af607416701d7adcfb861858aedc029417532092200c5e0fc19303")
