-- generated by KeySteam
-- update time: 2022-08-27
-- app_name: 正义执行 Justice.exe

addappid(1291210)

addappid(1291211,0,"d64b1103eda81b6c66eab85565a284c057cfbf7f2a59d0edd855d202606f6ea3")

-- DLC: 0/1
-- missing DLC: 2008210
