-- generated by KeySteam
-- update time: 2022-02-26
-- app_name: Silmaris: Dice Kingdom

addappid(1293120)

addappid(1293122,0,"48a5c9c742e9e81ef75d82c551a366c8c045319497ead0b51de1977f08976a71")
addappid(1293124,0,"423c0763f42c6085c218917e9de6e05ffe3d28cc169eddd6aad03d5597803661")
