-- generated by KeySteam
-- update time: 2020-08-04
-- app_name: M.U.S.T. Repeat

addappid(1293940)

addappid(1293941,0,"82064ec307453dba215c1757f4af2ac50a9cc4bb4601185a1fc86daf1538e3c2")
addappid(1293942,0,"82ce63d6c5ed05a00b3ce3b1bac3ff68b69237a84264ab94ef3bf120c2f58f13")
