-- generated by KeySteam
-- update time: 2026-04-01
-- app_name: The First Berserker: Khazan

addappid(2680010,0,"1421e968f8fce076add3633dd0c538406bc9f3969e5c70613d12134644b51dcb")

addappid(2680011,0,"fe9a3ee6a263260b75cf97d27ffc4eeda8c9eebc8019bdc57c247a546f450077")

addappid(3265140)
addappid(3265150)
addappid(3265160)