-- generated by KeySteam
-- update time: 2024-02-02
-- app_name: 2685430

addappid(2685430)

addtoken(2685430,"7258759187965900601")

addappid(2685431,0,"709d8ffb3a2c9cc00f5deeb3c14f8ffaca26872590e53f7efe8c115fc0f82068")
