-- generated by KeySteam
-- update time: 2025-03-11
-- app_name: Borıng.

addappid(3128950)

addappid(3128951,0,"bbe160c4a48b822b1eeb193965a791c7736892fe9f4334bf0345b8b6be27826d")

addappid(3468050)
addappid(3584110)