-- generated by KeySteam
-- update time: 2024-09-06
-- app_name: 3129530

addappid(3129530,0,"a247adcad5817ec3f49d84bfefa505bcc2d6a3750e6bce2670f939e752c811bc")

addtoken(3129530,"3983366802017702124")

addappid(3129530,0,"a247adcad5817ec3f49d84bfefa505bcc2d6a3750e6bce2670f939e752c811bc")
