-- generated by KeySteam
-- update time: 2024-12-06
-- app_name: 拘束战斗色情RPG - 命运的厄尔庇斯 -

addappid(3132310)

addappid(3132311,0,"5a09fc774077e78b30234e96ece8ecd04aeed0a6741f90468be0f2837f359332")
addappid(3132312,0,"2c72ed5318bed2ac15048b1b1d68cf9a6edd229998a4aa09be64806ebed7b2be")
addappid(3132313,0,"5a7bde0e193dadcdfcd7216e8ccd108af1af8b838a343ce4331a5c7e5d9817dd")
addappid(3132314,0,"fca9f0916692e6f4b95d5aec436e76f44cd8ddcfca9c874b5fb522e45d559bd7")
