-- generated by KeySteam
-- update time: 2024-08-01
-- app_name: Emerald Dreams: Sanity -  Platformer Quest

addappid(2987640)

addappid(2987641,0,"17B5E1271E275AACAECF6C8089F3F7052EA7E51C9ED1ABA91ADAD48C6994EF20")

addappid(3129610)