-- generated by KeySteam
-- update time: 2025-06-08
-- app_name: Night Patrol

addappid(3722070)

addappid(3722071,0,"c2f40fafb4c09881c05bf1211b96213a6a98ee9c8b5189cf85e59affd4bb0b7a")

-- DLC: 1/1

addappid(3793340)