-- generated by KeySteam
-- update time: 2025-08-05
-- app_name: Light Followers: Blinded by the Dark

addappid(3737700)

addappid(3737701,0,"7cd1120be7d40383d4054b6c062f7c97710b8e32914af509c891d30030679d8a")
