-- generated by KeySteam
-- update time: 2025-12-16
-- app_name: Asterix & Obelix - Mission Babylon

addappid(3489240)

addappid(3489241,0,"1511E14AFD238F4C4714AAC04B347B297FC50FFDD9BF1D63B71AED1B3171CD0C")
