-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: Mai: Child of Ages

addappid(3499550)

addappid(3499551,0,"af1e32a98b94cbd7a2457c753ae50a0c0ae615ea2c67d073752ba17d589d13f1")

addappid(4140630)