-- generated by KeySteam
-- update time: 2024-06-06
-- app_name: 枯萎的梦想

addappid(2640600)

addappid(2640601,0,"4718038428cb9cc4c661867959e0357185ed3d16f12eba547383b50237e79bb0")

-- DLC: 0/1
-- missing DLC: 2763350
