-- generated by KeySteam
-- update time: 2026-04-03
-- app_name: YoloX

addappid(2641350,0,"1d4f4be01c2a98fe8b49b30b32d79426d2d18408b1ed41588810e16dd6eb39df")

addappid(2641352,0,"b0f4c63cdb543d5bb1d0dfb5693998ec72f5395bbddd92c76223ce3474687142")
