-- generated by KeySteam
-- update time: 2026-01-01
-- app_name: 魔神少女 Episode 4 传达的心意

addappid(2644240)

addappid(2644241,0,"91999ae2c1ae89c4233a5d729c91b1b27bab5a78666126dcc38bff12d5a659b9")
addappid(3773340,0,"158480c17cc03958516302415563269cee62e763a57251a4811720e7ea575a87")

-- DLC: 1/2
-- missing DLC: 3864720

addappid(3773340)