-- generated by KeySteam
-- update time: 2025-10-10
-- app_name: Vampire: The Masquerade - Reckoning of New York

addappid(2658720)

addappid(2658721,0,"908bfe0ee03084b92b50fe278e3ab5318feb326f2629641078f42448c58636eb")
