-- generated by KeySteam
-- update time: 2025-07-12
-- app_name: 100 China Cats

addappid(3141120)

addappid(3141121,0,"72c1449dbabd955de195aa7668ac1ca73490fec265d4d9937a384835dd347549")
addappid(3801900,0,"82d63a1cf0892bfec26aa5343e57ae810da278eecbc127a161d42a360d4e073c")

-- DLC: 1/1

addappid(3801900)