-- generated by KeySteam
-- update time: 2026-02-19
-- app_name: IF蜘蛛纸牌

addappid(3153240,0,"a9b7ebd9af1d7006c8d6b957384f56bbf2f30a3ebe98e0763f2a4dc7ce4f59cb")

addappid(3153241,0,"fc02d6f7f1a84a14dca32d93c535eefcbc11c61c9fbddae284f5730ab4f74b62")
