-- generated by KeySteam
-- update time: 2025-03-24
-- app_name: 蕾贝卡与诅咒之剑

addappid(3158290)

addappid(3158291,0,"39f307bfc7736f489b15c98899dbf752f065e6f2ae6f6580bd7bfa5eadf2d0fd")
addappid(3158292,0,"9cd9561fb831a05a07db6a902c1b81ea6531b1b7b40fcf87a0b0179b28784ac2")
addappid(3158293,0,"5a39bf4ae758ec0bdb64778aee59922f5997e4a596061a8702a5f34cff66be61")
addappid(3158294,0,"4f7f547cb5dac89620cd823fcf0a11cc8c1c0878564b491f8fab04bec4a38b9b")
