-- generated by KeySteam
-- update time: 2025-11-18
-- app_name: 《联结：星火之盟》

addappid(3159570)

addappid(3159571,0,"8b67b11313f1da51f2ba40bab7831b79558154057a6270e935dfed05d85b9fef")

-- DLC: 1/1

addappid(3269880)