-- generated by KeySteam
-- update time: 2022-03-02
-- app_name: 迟到摄影师2自由版

addappid(1900130)

addappid(1900131,0,"9126725b292de1827c510fae7e20878d5c670848bb168d37abbaddd4d01c6b9c")

-- DLC: 0/1
-- missing DLC: 1900150
