-- generated by KeySteam
-- update time: 2023-03-27
-- app_name: Dungeons & Dragons: Ravenloft Series

addappid(1904560)

addappid(1904561,0,"1dc0d2da1dac66f263d4f9df06e1ed1838af426b71c7353cfd669865f7d10869")
addappid(1904570,0,"21cf5d55fef0041b6a71d3290bfe82e9ff0bbd78e116cf39fdde8adaf67863d3")
addappid(1904571,0,"750108ba130f35c62446041f0050d70b3b2885dc97911c73de97f0a23e804658")

addappid(1904570)
addappid(1904571)