-- generated by KeySteam
-- update time: 2022-03-08
-- app_name: 1907560

addappid(1907560)

addtoken(1907560,"15874168417921031802")

addappid(1907561,0,"cec7684c2b4b3684d1e25bb87d93ed4ca919b6a22057ad9f93d9872924cece8d")
