-- generated by KeySteam
-- update time: 2025-11-14
-- app_name: 泰拉往事 Terra Memoria

addappid(1912750)

addappid(1912751,0,"244027c934f4d4c69edd854d1bb2be2929f71873ebc6d0e567a3aeb43f8a319d")
addappid(2848870,0,"3abf934e923319e27f1e07ba89f65129da8a9be7957e6f5a7bc8b6a2b468c743")

-- DLC: 1/1

addappid(2848870)