-- generated by KeySteam
-- update time: 2023-09-22
-- app_name: SNWBRD: Freestyle Snowboarding

addappid(1912130)

addappid(1912131,0,"f08d1d86bda1bc4c9bbba96c324b6e3eabe2c79589de491da284cadbdfae7036")
