-- generated by KeySteam
-- update time: 2023-04-13
-- app_name: 索罗灵魂之戒

addappid(1917630)

addappid(1917631,0,"3c0369f0bd428fa34988259a396b23d2c3aa9973bc07c0fa7d10d79acfb96950")
addappid(1930820,0,"8c8c6ac783b8508be24d93307a2a0de220bccf9ebdf0d96098703da7559d31bf")

-- DLC: 2/2

addappid(1923950)
addappid(1930820)