-- generated by KeySteam
-- update time: 2018-12-05
-- app_name: 720010

addappid(720010)

addtoken(720010,"1766438911364444933")

addappid(720011,0,"0a4f10b1569d3a4a229208b8f10c5450b7b7c298c4f93ad69b6152c83053647e")
