-- generated by KeySteam
-- update time: 2017-09-22
-- app_name: 722220

addappid(722220)

addtoken(722220,"1787338073857742785")

addappid(722221,0,"8bfecd14507807c87972e9bd5ea8882f9d6f49ba3bd562bb428e323f211a0a21")
