-- generated by KeySteam
-- update time: 2019-05-06
-- app_name: 中国象棋

addappid(722670,0,"37a3d86c5b16e30e7554fcb08409bf5a2cc6b165d4f8f66f857d54a2fc51c8a1")

addappid(722671,0,"abe2a90907af2d70d578d4159039c8bfacf35e28ac123dc20b2de4de1f64c425")
