-- generated by KeySteam
-- update time: 2017-10-04
-- app_name: 726650

addappid(726650)

addtoken(726650,"2011141649940343790")

addappid(726651,0,"6c2c46447eaff26028c07478ba140a8b28d9da77ad15c4b6e0e25b06dc875b7d")
