-- generated by KeySteam
-- update time: 2022-08-04
-- app_name: Borderlands GOTY Enhanced

addappid(729040,0,"6b0632c9d06e9d6046f80d98a9e3fd6515d35f11fbba9aa53cdfb01e7fe46034")

addappid(729041,0,"6bf645f76a001bb548c0f52d99fb5a7f5c7130c9a7ed3d6518318c0bdea77f8d")
