-- generated by KeySteam
-- update time: 2024-02-18
-- app_name: Eat All The Things

addappid(730290)

addappid(730292,0,"1a763f6481353e7115c1865d86edd9f3cb39b41a65051c430f1bcc76c212405c")
addappid(730293,0,"eae417e6d9dce23f814546cd6038aa8303889a7ee8b7557f64fefb997931a251")
