-- generated by KeySteam
-- update time: 2017-10-12
-- app_name: 732550

addappid(732550)

addtoken(732550,"4955890222263983495")

addappid(732551,0,"5cf246eb378dadc6af53a405ea0936b93e255076d4e11df599efa35261ee615b")
