-- generated by KeySteam
-- update time: 2022-05-03
-- app_name: Mustache Politics Shooter

addappid(733090,0,"6b7ad488955196750ff7d15543b9ed3fae33790815571e48fc75c732497f6168")

addappid(733091,0,"6f2efcf732c90a3eae51277049efb98037d325bd2b3704e929fd9f7518895811")
