-- generated by KeySteam
-- update time: 2019-09-10
-- app_name: The Forbidden Arts

addappid(735060)

addappid(735061,0,"92dc135303786539f9521a46b8404eb2ccbc6d81b3dd9ec56150fd9b119ad545")
addappid(735062,0,"2bb9de701d385cd30cb62565972ebf72adc974362a785be57d9c0adcf757acf8")
