-- generated by KeySteam
-- update time: 2024-04-04
-- app_name: Dosoland: Snake Man's Adventure

addappid(1500300)

addappid(1500301,0,"47f0f529062cd5e31d43d2d335c7e9c876f546e1b36647287ebd662441f48a17")
