-- generated by KeySteam
-- update time: 2021-07-08
-- app_name: The Other: Rosie's Road of Love

addappid(1509790)

addappid(1509791,0,"78b6cf2adcd5fdaff59352e91553bd7685dfb6fa66d96d85f28e5560c3b27499")

-- DLC: 1/1

addappid(1565930)