-- generated by KeySteam
-- update time: 2023-09-12
-- app_name: 秘馆疑踪2 / Heaven Dust 2

addappid(1515900)

addtoken(1515900,"1912663682185596137")

addappid(1515901,0,"3d807e205a7ae7a2c70eeb7fe919c52f17c54a5d642efc4269db0b837bc211d0")
