-- generated by KeySteam
-- update time: 2023-05-23
-- app_name: Monster Tribe

addappid(1515330)

addtoken(1515330,"8005839956731287600")

addappid(1515331,0,"1032bdef2fe72df6c4e59a75103f7c77c7dfaf52c9759da13ffaff19f033e408")
