-- generated by KeySteam
-- update time: 2024-10-21
-- app_name: WARCANA

addappid(2022930,0,"e7e750a9703cc42116f56613cf7a34b04264a6450ed42774af765ec408541cdc")

addappid(2022931,0,"d229c5081f104f5986426a1ca355121a5c09c23c0e90058b743c86b849a2cb6b")

-- DLC: 3/3

addappid(3073620)
addappid(3073630)
addappid(3073640)