-- generated by KeySteam
-- update time: 2025-11-10
-- app_name: Bakso Simulator

addappid(2022270)

addappid(2022271,0,"24e561a9ea2a3811d188e870b8bb5439597cd6f1f06886a2c494fba8ec12a470")

-- DLC: 3/3

addappid(2066820)
addappid(2066930)
addappid(2066931)