-- generated by KeySteam
-- update time: 2026-02-16
-- app_name: 先觉斗牌 2

addappid(2022230)

addappid(2022231,0,"3a087f4dae1221a5505e229e96108eae01d24f4e0c56e9d506e3d8ce788414b3")

-- DLC: 1/1

addappid(2801300)