-- generated by KeySteam
-- update time: 2023-09-25
-- app_name: Tank Commander: Battlefield

addappid(2026070)

addappid(2026071,0,"9c791df9cc90d04f3745627a293e408d7683bdf00d782045f2b7ac80895cd104")
