-- generated by KeySteam
-- update time: 2021-04-28
-- app_name: Holostar Command - Quantum Alliance

addappid(1462560)

addappid(1462561,0,"79f8563f6d1fa7dd9b5d2de840ea581f9e0e619170f810d183e31c374fb0478f")
