-- generated by KeySteam
-- update time: 2026-04-02
-- app_name: 污痕圣杯：阿瓦隆的陨落

addappid(1466060,0,"f53acb7f143a62f46c302975a2d5cdb7d58fb41a5a7d9a0a03f722a39493e160")

addappid(1466062,0,"b164844c9d1dcef4202a397a747eff0fc24b75b5553e21bebbd7e86042d94bca")
addappid(3687050,0,"8a5843ffcee408b2a16680531955ed57dd20d577be56ebb42d7c99dd653a3b2e")

-- DLC: 6/6

addappid(3681950)
addappid(3687050)
addappid(4132150)
addappid(4183140)
addappid(4492250)
addappid(4514980)