-- generated by KeySteam
-- update time: 2023-03-21
-- app_name: Slime Fantasy: the search for the lost sword

addappid(1472810)

addappid(1472811,0,"eef5c6dc9d405b09d985af26c3af54c7096fe7ca3e9b376ad1218c431f24dac7")
