-- generated by KeySteam
-- update time: 2022-01-01
-- app_name: Mrs. Santa's Gift Hunt

addappid(1473660)

addappid(1473661,0,"b4e8997b8898d88f92a94fe5544497d489b95ad90b2415c2d75307adf33dd0ef")
addappid(1473662,0,"7af2662403c1930546f35b39cc84c906e95c2dbe9f069705cf6798d8c66cf695")

-- DLC: 1/3
-- missing DLC: 1473720, 1477800

addappid(1474380)