-- generated by KeySteam
-- update time: 2023-07-24
-- app_name: Hundred Chances - The Fortress

addappid(1473220)

addappid(1473221,0,"21cd0d18fed23b72713dd6bca5685fa8767bf1bf119cc86d2ffcaabd3ff3bac8")
