-- generated by KeySteam
-- update time: 2016-07-20
-- app_name: Extravaganza Rising

addappid(501030)

addappid(501031,0,"e2b5d38d66a2944b6b94975cfeaffca3556e78f474fd1531aa01fbff0d3a92da")
addappid(501460,0,"c531f610b576697035924ea077d558f0412205e7883953f149f6c374d528fadd")

-- DLC: 1/1

addappid(501460)