-- generated by KeySteam
-- update time: 2019-07-14
-- app_name: The Shrouded Isle

addappid(501320,0,"c52865460280ee9f0443a38c9c1ae244baa5c6d8fc4236b7cc2679104287b2c9")

addappid(501321,0,"b9811c7974d74633b7e34ff7d5703c96f1301e20901c724488ad22fa4242fa41")
