-- generated by KeySteam
-- update time: 2026-02-06
-- app_name: Elven Assassin

addappid(503770)

addappid(503771,0,"4847dd1de9fcf351094865e0e0757667ecced7be8fda54c3784fcf397222feec")

-- DLC: 1/1

addappid(2524910)