-- generated by KeySteam
-- update time: 2018-06-05
-- app_name: Patterna

addappid(503860)

addappid(503861,0,"4737203c516472fc743edad5abe875bf32558a08f787dc0e91f7bb0f79ffdf02")
addappid(503864,0,"91bbfafa2297d0df9d2dadebe16f6467dd1f11018a83288c9365e0342f18baf1")
addappid(534590,0,"5dfdd3d5310968df77af0959fa8aef7ee92fd51c7617961a80dfadef1b76983e")

addappid(534590)