-- generated by KeySteam
-- update time: 2018-06-10
-- app_name: Bicyclism EP

addappid(507030)

addappid(507032,0,"2a0599971c41cb08a0528a97281f6c736575647512c4773b06603360e0d86816")
addappid(558120,0,"3e6da9efae1f99d914d23dcbf872dee60245caead326cf50ab876652628e797c")

-- DLC: 1/1

addappid(558120)