-- generated by KeySteam
-- update time: 2016-11-28
-- app_name: Island Simulator 2016

addappid(507440)

addappid(507441,0,"b19866dd93472010abc8142e946bbe8d7f1c585cf1e10f72b744abf66b51206f")

-- DLC: 2/2

addappid(541810)
addappid(541940)