-- generated by KeySteam
-- update time: 2018-08-19
-- app_name: 平面英雄

addappid(508790)

addappid(508791,0,"46b944d04d399ccf5495bbd7c98c87f19958a902c783f300af2c2bafb4a44735")
addappid(508794,0,"f576d6a257f28dc7cab6cfca7a3403ca9f17b8302d08f25ea0f3429e3a335b3f")
