-- generated by KeySteam
-- update time: 2025-10-07
-- app_name: The Lord of the Rings: Adventure Card Game - Definitive Edition

addappid(509580)

addappid(509581,0,"52c1a0087cbfb151a2209e4d93d765e9878d82528d0076b0c86ae46d6af8ecae")
addappid(509584,0,"6f4ef29c5403c908f51d9898f44f7eba226e146ec440fac3ef4f979367e1f830")
addappid(862380,0,"ea50f89b9d89a6d6ad85242cf427790a45f47c3f8930e9ff94b7b4b1341af12a")

-- DLC: 7/7

addappid(743610)
addappid(743630)
addappid(743631)
addappid(743632)
addappid(862380)
addappid(863240)
addappid(1047230)