-- generated by KeySteam
-- update time: 2022-07-31
-- app_name: Xecryst Remains

addappid(510000)

addappid(510001,0,"cb143f72b00dfc2031a1cb99e64a25dad86b9a544474e3b91e762b4c4005e5e9")

-- DLC: 0/1
-- missing DLC: 1022350
