-- generated by KeySteam
-- update time: 2020-03-19
-- app_name: Evolvation

addappid(510840)

addappid(510841,0,"184671c131437b37a00c49824c4af7096b98e13957fad1543f0da315a77e8824")
addappid(510842,0,"f744674412928d90eef9be2e6047c570730747b8311b1e9b1ed20ed0cf52bae6")

-- DLC: 0/1
-- missing DLC: 961160
