-- generated by KeySteam
-- update time: 2022-12-13
-- app_name: Redout: Enhanced Edition

addappid(517710)

addappid(517711,0,"3c65968fa84da5dfbace9314360f35d4a1248dac7c04e5b29cb534136bd31025")
addappid(573350,0,"3224256c0ee945c5558c62535afa805507c54a00d1aa7663a4bab5caa1d9facb")
addappid(580620,0,"612ff17c5ccf72474d746c8b29cb7d98890f8be0521b50ce98c67cc4dc5c7294")

-- DLC: 6/6

addappid(573350)
addappid(580620)
addappid(627430)
addappid(627440)
addappid(728910)
addappid(762770)