-- generated by KeySteam
-- update time: 2016-11-25
-- app_name: Zenza

addappid(519990)

addappid(519991,0,"5224089f64ca351dfae24b5043ac3dc6fdb18efaa0e33cacb2b52ab9e77f15fe")
addappid(519992,0,"f00fbe8ba1fbfcc81ce736b644ce0d680488e6c2eb7e5dc82e65a70af4731057")

addappid(549630)