-- generated by KeySteam
-- update time: 2026-04-04
-- app_name: Pox Nora

addappid(201210)

addappid(201212,0,"bfe82ddd4316cf061286add495e0b41806b6296cb6244ce82f297fc9793f69fe")
addappid(201214,0,"ee455a5e29aa42de607991a9ea5aaf47a1e2d38648265257bfbe0cd2e2abb185")
addappid(201215,0,"9c0c25fdb339169d8d6dcbf9d53e0fa7fdd13f02e782148f00255e77df8d503f")

-- DLC: 2/2

addappid(649430)
addappid(649431)