-- generated by KeySteam
-- update time: 2025-07-25
-- app_name: EverQuest II

addappid(201230)

addappid(201231,0,"a5817b43de7d68063b2aa3d8cd6b0e58e2dcbeb9fa677536cd931bbfedb71160")

addappid(24100)
addappid(24110)
addappid(24190)
addappid(24230)
addappid(224560)
addappid(249770)
addappid(332430)
addappid(333890)
addappid(333891)
addappid(333892)
addappid(334430)
addappid(420410)