-- generated by KeySteam
-- update time: 2026-01-05
-- app_name: WRATH: Aeon of Ruin

addappid(1000410,0,"5fe21717b240e5174b78446abfad61f98cc1a925c119721fd7d98181a02f55cf")

addappid(1000411,0,"1cbbf1c9d6b1d0aee69b3d4114d5b5b5ebe60f335599cc50eb08bfaffa7b0efc")
