-- generated by KeySteam
-- update time: 2019-01-02
-- app_name: Area Cooperation Economic Simulation: North Korea (ACES)

addappid(1004350)

addappid(1004351,0,"4ff1b5dcf76a2380185f93221e5ab398e0da68c9e16ffbd6637d7f517540f1f5")
