-- generated by KeySteam
-- update time: 2022-05-04
-- app_name: Jewel Match Solitaire L'Amour

addappid(1009700)

addappid(1009701,0,"e1eee1709d98c775a167699973d465e7432cbb479ee2fe018495e4becc806e1d")
