-- generated by KeySteam
-- update time: 2019-06-02
-- app_name: Sankaku Renai: Love Triangle Trouble

addappid(1009450)

addappid(1009451,0,"8d37254f0cfa45913457bc911f43c48e5b9f46f2bed18015540feed1284e8dad")
