-- generated by KeySteam
-- update time: 2026-04-03
-- app_name: 军事冲突：越南

addappid(1012110,0,"a93d85b18f48771cc6875074b5fa6fa65b56550ab887b7e25fde78da9427baa7")

addappid(1012112,0,"cbc5b812e9be7c6d177cef1dd0db8c45d057d2cc1b24bdde7fd70a011b394cdb")
