-- generated by KeySteam
-- update time: 2022-01-02
-- app_name: Bouncing DVD : The Game

addappid(1014370)

addappid(1014371,0,"8fc4f625ad99bba708a2c342f7d80dc8ec7250e5d0de15d4894bd9fc63a9c3b5")

-- DLC: 1/1

addappid(1129470)