-- generated by KeySteam
-- update time: 2021-09-20
-- app_name: 1015520

addappid(1015520)

addtoken(1015520,"7970785008626046099")

addappid(1015521,0,"573228acca192ecfa69df96ca08149eea90ca4d804e0748c9dec088ae8b86796")
