-- generated by KeySteam
-- update time: 2019-04-11
-- app_name: 少女之路

addappid(1015710)

addappid(1015711,0,"95e6ca883c468c0a42c0394ab5551c08d91a4da5fda7bca10a832fbb33445822")
addappid(1015712,0,"7bd8bbad897e18ec7d461658b0d3d16a167518f18788182ed1bd9680d8050e6d")
