-- generated by KeySteam
-- update time: 2019-06-18
-- app_name: Castlevania Anniversary Collection

addappid(1018010)

addappid(1018011,0,"f369e7edc8f5b3ceafff6f9366fbf8d1b5f3ce2d064444f966315ff1b0cbdf4b")
