-- generated by KeySteam
-- update time: 2025-07-01
-- app_name: Cats

addappid(2977660)

addappid(2977661,0,"29150367fcc9e93c29642116034902c42263aef00a211988da1acce45e534eac")

-- DLC: 1/2
-- missing DLC: 2979910

addappid(2979900)