-- generated by KeySteam
-- update time: 2021-09-01
-- app_name: Hidden Objects - Cartoon Fantasy

addappid(1746730)

addappid(1746731,0,"73c6d1ead452c6309bba04c7e2130cbac412be1cc6235db53bd224949d5f1fc3")
