-- generated by KeySteam
-- update time: 2025-10-28
-- app_name: Sex and the Furry Titty 2: Sins of the City

addappid(1750200)

addappid(1750201,0,"0fc0057a167ee8605ab6dfeaef8ecccff8f406bcd28b2d06c32585006f70331a")
addappid(2123470,0,"c55542f436fcc2a9f218a17312be20db29fb233bcca85d9d4ed055875b6bbcca")
addappid(2123471,0,"38e96b866cdd613bed564a2892f027927c82fa09b801e260dcdd4ced5d432d2c")

addappid(2123470)
addappid(2123471)