-- generated by KeySteam
-- update time: 2025-06-17
-- app_name: 转生魔塔

addappid(3292410)

addappid(3292411,0,"16d7ececf2db5ba5a981ed018dbc31e6def80aa76eb66c810161e377fa53e010")

-- DLC: 1/1

addappid(3430980)