-- generated by KeySteam
-- update time: 2023-11-20
-- app_name: Kowloon's Curse: Lost Report

addappid(1161640)

addappid(1161642,0,"07dde70c584d694f53c5002a58bb1576b67681253786046f50f2766111363b96")
