-- generated by KeySteam
-- update time: 2026-01-31
-- app_name: 希克斯之歌

addappid(1162750,0,"07dc704409f3fd3165944e949f52741c2580711859867ee831530a6fa561f28d")

addappid(1162754,0,"e0b5f2cfdcd692e1dfff1936c6d58da7c9e39ad1c13c8bbc64f4fea1e739ccba")
