-- generated by KeySteam
-- update time: 2020-01-21
-- app_name: MMX: Otherworld Mystery - Expanded Edition

addappid(1162760)

addappid(1162761,0,"153cd9f8b19e9f51fbb79ec2a9d46e58e81b2ba714f7bf13f18957c614db074a")
