-- generated by KeySteam
-- update time: 2019-12-19
-- app_name: 1001 Jigsaw. Ice Age

addappid(1164300)

addappid(1164301,0,"c47bf576627d264475c2645037b13edfacd7700bec3758b2b9f0421dbb6534ee")
addappid(1164304,0,"acd1a0343fabe79708427386888c8184895ba0a2037eaab7620c4f041a95b351")
