-- generated by KeySteam
-- update time: 2020-02-18
-- app_name: Tasty Jigsaw: Happy Hour

addappid(1165100)

addappid(1165101,0,"e606e5ea097757a5c501bd730aefe421ed58f257faec71db3d6ef4e4d2c15c52")
addappid(1165104,0,"7e56a6fcbaec69a81d83af3a3d0ce6b3193170f9718f08f578d70cc9dbc1080b")
