-- generated by KeySteam
-- update time: 2019-12-18
-- app_name: Shine's Adventures 6 (Go! Girls)

addappid(1175470)

addappid(1175471,0,"edfcf097871305484af5a8c39fe63f9279f70937f50b822face49815c87f3e3f")
