-- generated by KeySteam
-- update time: 2019-10-26
-- app_name: 1177450

addappid(1177450)

addtoken(1177450,"11781894574963382622")

addappid(1177451,0,"7840e59c33914e470e9703a98bc5ca91fbc6a36ecd61e89172195b652e1fdbf9")
