-- generated by KeySteam
-- update time: 2021-06-24
-- app_name: Yu Escape / Monday

addappid(1177720)

addappid(1177721,0,"e36c2d595f48ca926faf1e0854dce7603ab4fa9bcdf0b7acfe3417a7b60635ca")
addappid(1192561,0,"f87d03323f1cb69dc8c4248069783414e82b6fb9ed6c7c2199484282179db384")

addappid(1192561)