-- generated by KeySteam
-- update time: 2026-03-03
-- app_name: Zombie Killer

addappid(2925210)

addappid(2925211,0,"C2CB0654AEDC191F2D2A356F79DA627AE10F7BD3A8A6D6D30DE1D19373D832E1")

-- DLC: 0/1
-- missing DLC: 4062720
