-- generated by KeySteam
-- update time: 2026-02-12
-- app_name: 《指环王：重返墨瑞亚™》Return to Moria

addappid(2933130)

addappid(2933131,0,"571136626b31c8951f3afe863e98bd7d8c833657d08311b65aa528309cb9b6ef")
addappid(3184500,0,"f496d95994c7faaae378d2296549e6dcf8caba08288406472ede9bf5c3cdf2ef")

-- DLC: 7/7

addappid(3184500)
addappid(3308250)
addappid(3349540)
addappid(3560550)
addappid(3739100)
addappid(3739110)
addappid(3874660)