-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: Monsters are Coming! Rock & Road

addappid(2934220)

addappid(2934221,0,"655fd0514b7ac5f0ea01bc1fce34a46d3b70436dc4e6f1527dc230ecc6548eab")
