-- generated by KeySteam
-- update time: 2025-12-08
-- app_name: Desktop Town

addappid(3748960,0,"dd5108ddff70164fd7ca7674e49426d11da90a07247b62499b918b66d27cd45d")

addappid(3748961,0,"9bf4b3e433ef238c0cd891af8e8a465176b0c744a682168554c56a0602a5ddbb")
