-- generated by KeySteam
-- update time: 2026-01-06
-- app_name: Blackstone Academy for the Magical Arts

addappid(1245670)

addappid(1245671,0,"317c0ddd6844e1a379967a64c7b744c31c0a5a83f2848dfdbbe2e228f4dacf94")
