-- generated by KeySteam
-- update time: 2025-09-05
-- app_name: Realpolitiks II

addappid(1248060)

addappid(1248061,0,"475f797e335e27ddcd4cbf01075cd21575204571580416182c6c4d8227e9758d")
addappid(1581130,0,"a0d54181576ebcac0c46882afdec67dd40410f94d9939be0d0bfa7000f6b0aa7")

-- DLC: 1/1

addappid(1581130)