-- generated by KeySteam
-- update time: 2021-06-30
-- app_name: 意识迷宫：克苏鲁卡牌

addappid(1253860)

addappid(1253861,0,"a413f0623457407e6ba860cde72d57a4d5d513e80d42e967ed38685a4e80df93")
addappid(1524740,0,"90acd5df5808bb42300a25b2ab546ae03b58c568daa7a0907eab140e9d4bd326")

-- DLC: 1/1

addappid(1524740)