-- generated by KeySteam
-- update time: 2025-05-14
-- app_name: Corrupted Paradise

addappid(2701750)

addappid(2701751,0,"0b49d809733f3c29c345861dd3655bc56b5e680b74285b1e596506dfb1f50b5f")
addappid(3327130,0,"a6e2835c19958f4d1990533627b9dedbd85433dc8f0ffbc7b722f29c9a294cf1")

-- DLC: 1/1

addappid(3327130)