-- generated by KeySteam
-- update time: 2025-11-26
-- app_name: 3D Watermelon Game

addappid(2707420)

addappid(2707421,0,"affab90ea176c4f4451aa06b9f0b9bcb316f527bc7a46bf16489a3fa606b5393")
addappid(2707422,0,"89aac3ea9f039778b84638eae6795d8f76a3cd73cc4d17c5685b6a2dc96215fe")
