-- generated by KeySteam
-- update time: 2025-10-04
-- app_name: French Fries Pusher Friends

addappid(2714330)

addappid(2714331,0,"a4026252a117009e52db77059fcc6be52d19b7a81a7f813d72d34803ac42723b")
