-- generated by KeySteam
-- update time: 2026-03-20
-- app_name: True Fear: Forsaken Souls Part 1

addappid(440420)

addappid(440421,0,"cd2c23953d2cbb0f7104a2f17f9439812277c4786896c4bd333f52476c42cb2a")
