-- generated by KeySteam
-- update time: 2016-04-29
-- app_name: Aselia the Eternal -The Spirit of Eternity Sword-

addappid(445420)

addappid(445421,0,"1670978f8645f602c4c3f3811c0eb14ecf3a091e2cff0b7eca82f375dc85642d")
addappid(465320,0,"92ce54986ed25604d864df71acdc7a53020a7a647754cac67761d93bd0fc73d7")

addappid(465320)