-- generated by KeySteam
-- update time: 2017-01-29
-- app_name: Seinarukana -The Spirit of Eternity Sword 2-

addappid(445430)

addappid(445431,0,"b848eb6823c7dc2667fe860cf8ffcd7b46e0bd542105de17d43e638b3026ec21")

-- DLC: 0/1
-- missing DLC: 465040
