-- generated by KeySteam
-- update time: 2018-08-01
-- app_name: Planet in the Shadows

addappid(448820)

addappid(448821,0,"ff5acb8661457e13d92174e18e3487a73f3a3cbf6ff553f7c9ba7fce047a65d7")
addappid(448822,0,"52b07e0bd33989489c947940c3fd06dbfab7b6fd33c119e0aa23c8cf32ca46cb")
