-- generated by KeySteam
-- update time: 2026-03-25
-- app_name: Shadowverse

addappid(453480)

addappid(453481,0,"2d9100139d25ad3d55a3f991cac443df7e67660b53ca305fae62664cbc570a75")
addappid(453483,0,"219ef9ff0535392a5cd7763da0e326b3634e62b232da9c0a024b34f97a956c21")
