-- generated by KeySteam
-- update time: 2024-04-21
-- app_name: Hotel Perkkow and the Two Vegetarian Werewolves

addappid(2420780)

addappid(2420782,0,"882fe7628f11993283b3eb63898220553f7e24b819479681daa6f6f8d2df9de7")
