-- generated by KeySteam
-- update time: 2025-10-18
-- app_name: 2427520

addappid(2427520)

addtoken(2427520,"11455794532909118909")

addappid(2427521,0,"b8afb0c43a7a5c871210f252b3aa6bcf3b12ed31e6a4224f9bf3138ccbbdf3ab")
