-- generated by KeySteam
-- update time: 2026-04-01
-- app_name: World War Armies

addappid(2438160)

addappid(2438161,0,"9bbe74ebfcb59f9ceb1838b59527be8b8ebcec60e8ba6461a1dcd752784b5b06")

-- DLC: 9/9

addappid(2826470)
addappid(2826480)
addappid(2826490)
addappid(2936560)
addappid(2936570)
addappid(2936580)
addappid(3165270)
addappid(3381000)
addappid(3687220)