-- generated by KeySteam
-- update time: 2019-08-05
-- app_name: Hamsterdam

addappid(922040)

addappid(922041,0,"bc4bb04174614aa733707309e62ec031a6a8ecf9610a6661d1e5f34e2cbb9441")
addappid(999010,0,"ee55c325e514da37d957826257d5c87d87873d65cefe50888d232d2a396acc6d")
