-- generated by KeySteam
-- update time: 2019-02-13
-- app_name: 无主之地:银河 4X-Galaxy

addappid(922450)

addappid(922451,0,"a443146c275a32f06a493138eb415706ba75461349e232401e48908e3644c2a9")
addappid(922452,0,"46d52c7afb65fb380f07005473587a30dff4564da35e4cd2a625ba3cc16a237a")
