-- generated by KeySteam
-- update time: 2018-09-30
-- app_name: 923330

addappid(923330)

addtoken(923330,"6779253120822560629")

addappid(923338,0,"07251084f6c92cc1ef6eb549ba472bc789b0de857f03402f0c6867c32b118dbe")
addappid(923339,0,"2320dfacafc4d2700ffc26e38db9f853e77789dad1ee6e8f97b4818857fdfed7")
