-- generated by KeySteam
-- update time: 2018-08-15
-- app_name: Mystery of the Ancients: Curse of the Black Water Collector's Edition

addappid(926100)

addappid(926101,0,"3fee35b5d0d88e37683eeb6ee517746f95fea772d6d0f308b4df95ea6b95d854")
