-- generated by KeySteam
-- update time: 2019-10-06
-- app_name: Quantum Covenant

addappid(927120)

addappid(927121,0,"d3cff0ca000f4d89ee98bf3e41fdeccb1d8cc24a02db1025881c1b96d4ce92dd")
addappid(927122,0,"8459254705c624827efa5fcb616e31f26efed0d0438dff0c45d92c69090eb6cf")
