-- generated by KeySteam
-- update time: 2018-08-27
-- app_name: Christmas Mahjong

addappid(929440)

addappid(929441,0,"4e6fa091fc36152f99a73c7ce5d081cddd744040449f3f7bbd9596e1a017ef76")
addappid(929443,0,"a4e4ca5b1ea9f1d2ad9fe061fe95e8de2ba3ad76548694f374148a9395fa8851")
