-- generated by KeySteam
-- update time: 2026-03-21
-- app_name: Bikini Heaven

addappid(929800)

addappid(929801,0,"e08b6909114575c5d3e1d3c3dc15e48354a3e5c919e03181106a8370e11092b3")

-- DLC: 0/3
-- missing DLC: 4125120, 4125130, 4125140
