-- generated by KeySteam
-- update time: 2025-10-23
-- app_name: Dead Island 2

addappid(934700)

addappid(934701,0,"9f01bb4de4308fcda3524d8e086fb30c2cee5a647bc41b8ca77afad561bde375")
addappid(934702,0,"74f4653f5c8cd21938bd4a269765ee3310d860bbf57e7fcc44dd02751f277a49")
addappid(934703,0,"58de2f171f82b74cb47ade0cbc87eb4a5046814bdf0bf1b6d359625a63543852")

-- DLC: 14/14

addappid(2667910)
addappid(2813000)
addappid(2813010)
addappid(2813020)
addappid(2813030)
addappid(2813040)
addappid(2813050)
addappid(2813060)
addappid(2813070)
addappid(2813080)
addappid(2813090)
addappid(2813100)
addappid(2813110)
addappid(2813310)