-- generated by KeySteam
-- update time: 2019-02-23
-- app_name: Super gamebear with its three girlfriends你想知道关于超级喜欢游戏的一头黑色矮小的游戏熊是如何与它的“三个后宫团女朋友”购买到GBC游戏机的吗？

addappid(937020)

addappid(937021,0,"1b1d2ec0612dda48d9675f953b1a75f93521e542900770cd8ef8dabc6b676138")
addappid(937023,0,"dc4786ba244625382da521dd69a081eadce3d52603c4a92099b12f9fd6e2ae85")
