-- generated by KeySteam
-- update time: 2018-09-03
-- app_name: 937220

addappid(937220)

addtoken(937220,"7635474539911995995")

addappid(937221,0,"f8632c882c810a580aad45b45f9e07b207fe0d1c10dfd595893702e1011a6a95")
