-- generated by KeySteam
-- update time: 2018-09-06
-- app_name: Quixzel Rush: Pumpkin Bash

addappid(937610)

addtoken(937610,"2170174232756290941")

addappid(937611,0,"d5b769421f7f230bbb08598abbce58a9c3f5a1d6cf3deb087ca53f1b23b771b1")
