-- generated by KeySteam
-- update time: 2020-07-13
-- app_name: Infini

addappid(1120420)

addappid(1120422,0,"95463357f4f9c6cc749d18be38588788d643b4f06963191396b8e80b77737643")
addappid(1120424,0,"76228c80ce41c65eacdd66629f3a83908b1b86f759fa66deb8c9a002392562af")

-- DLC: 1/1

addappid(1307210)