-- generated by KeySteam
-- update time: 2022-05-03
-- app_name: Curse of the Dead Gods

addappid(1123770,0,"d0d53200d054f56b72381e9e109bcb806aadeb5d8c24ec2b976f5e9958686d83")

addappid(1123771,0,"1a98ebf1f0691fe81c354b0a0d89224f4652aa3696853b7040d5492e272bb48a")
