-- generated by KeySteam
-- update time: 2019-11-22
-- app_name: Endless Fables 4: Shadow Within

addappid(1129030)

addappid(1129031,0,"127ed737381b161e51381a005c7593224b569b972b936b36c8871d59ef79bb8a")
