-- generated by KeySteam
-- update time: 2021-11-12
-- app_name: NERTS! Online

addappid(1131190)

addappid(1131191,0,"fe3682850fb9a4a52955d15eb8fc1fcebe6cb36272a45923dbd19d2d5d3ca914")

-- DLC: 1/1

addappid(1541260)