-- generated by KeySteam
-- update time: 2020-03-20
-- app_name: SECTOR 40: The Soviet Legacy

addappid(1260250)

addappid(1260251,0,"241a161139f068c2487e7ab4a0e8f2faf28d3c3e194dc75547012c7f9f4f7d57")
