-- generated by KeySteam
-- update time: 2024-10-26
-- app_name: Fantasy World Online Tycoon

addappid(1268290)

addappid(1268292,0,"96ada096c06c5ae6c654a9d32f8b46aec743cd6ce58f7772890fb1f9ee43e0dc")
