-- generated by KeySteam
-- update time: 2020-08-06
-- app_name: 少女异闻录

addappid(1269820)

addappid(1269821,0,"1c517d244ae45f3cd35b6548006e6412bc38c04f898d48fc6d1752f3cffb5fa0")
addappid(1269822,0,"2a46d6fd38db1524ab90cf8f355ed1aeef6026fb9a18187a505021ad01f48913")
addappid(1269823,0,"80eed594ff5afe17b6e42848e26737bd80c7699fb5aeb81fc61cc6cb10c07c6b")
