-- generated by KeySteam
-- update time: 2022-02-09
-- app_name: Street Cleaner: The Video Game

addappid(1271380)

addappid(1271381,0,"47d3a01e7ca20e65f26c7e39bd15aeb9cbb4e1ef6edaea4a93c903e1cee0ad40")
addappid(1882650,0,"a1fa72c000ea71902da22687ee2e5d23a3860221871f10e6e371c94c2e78fb76")

addappid(1882650)