-- generated by KeySteam
-- update time: 2020-03-25
-- app_name: Geezer Gus: The Meteorite Motel

addappid(1272100)

addappid(1272101,0,"54c5e0c2a4668d7dc3ee4aa231ef171012dadb901678b13c4c2ec845ca793b89")
