-- generated by KeySteam
-- update time: 2023-08-01
-- app_name: 田园记

addappid(1272840)

addappid(1272841,0,"22f634cc9d74727e72ce93a475a329d90d2bea2a12872c4af44162593858d498")
addappid(1272842,0,"837e5dc39c95b33c581f132842b2de4a8a96f35eed9d80c7a1ecf8e183191381")
