-- generated by KeySteam
-- update time: 2025-10-09
-- app_name: Sphere: Flying Cities

addappid(1273220)

addappid(1273221,0,"f2aa4de19a6a5e455d0c10c0b74e7aa61c92142c3cef4bb3d3850353396d11c3")
addappid(1273222,0,"fc99214da2749ec43a7c9e70a2262fa1cdf490e2d9ca8e75e16351734802e254")
addappid(1773940,0,"674e75e2675fb3c9e1cacc7ec4eecdbd74742313e7f18bf8ab75925567cbeb23")

-- DLC: 1/1

addappid(1773940)