-- generated by KeySteam
-- update time: 2026-04-01
-- app_name: 黑色印记

addappid(1277530)

addappid(1277531,0,"28DE2CAB2087D7850E1BEC49FE9822095AD65D439FB14208099444EABD266CB0")

-- DLC: 1/1

addappid(3932660)