-- generated by KeySteam
-- update time: 2021-02-13
-- app_name: Jumpala

addappid(1278190)

addappid(1278191,0,"7803d85a6d60293c46d522d295797001c6aac3a83298afc11f0a2a4b71cf38d3")
addappid(1278192,0,"f5e803927e26f561e2f887d14632f7bcd9c655d56afd6bc6e1def8fb36823282")
