-- generated by KeySteam
-- update time: 2026-01-05
-- app_name: Screw Drivers

addappid(1279510,0,"f0c942fe2cbc4dc5969f0ab7b555a66ff802afbe06c5ee011facd3f1b2125924")

addappid(1279511,0,"ef004932c90fe787672412305ac6f8a390431f51947c405d255840ead5220052")

addappid(2999730)
addappid(3288110)
addappid(3500960)
addappid(3816730)
addappid(3816740)
addappid(3816750)
addappid(3816770)
addappid(4129420)