-- generated by KeySteam
-- update time: 2017-08-16
-- app_name: Lumber King

addappid(681500)

addappid(681501,0,"54a43663fd75b16ec20bcb159758f965237d121465da6f392cb5581dd21ec4e0")
addappid(681502,0,"add45dde08aa717812335bcfa70a7e5f6b063735d1ab04a9224a4a3b6a24f9c5")

-- DLC: 7/7

addappid(681510)
addappid(681511)
addappid(681512)
addappid(681513)
addappid(681514)
addappid(681515)
addappid(681516)