-- generated by KeySteam
-- update time: 2017-09-05
-- app_name: 仙剑奇侠传四

addappid(681820)

addtoken(681820,"7878866788261462933")

addappid(681821,0,"e35e37ed82fe1940f5a55d30efec4060d46f5c794d675532a34f5423cbf3618a")
