-- generated by KeySteam
-- update time: 2025-12-19
-- app_name: Drug Dealer Simulator

addappid(682990)

addappid(682991,0,"b17004026dd40cb3def275b5276b337fc8f1168b1fe8bdd531b927897621acb3")
addappid(682992,0,"52b59e88229b597e044a71ea1391a8bb52efc9f17b744820600007b650b2188c")
