-- generated by KeySteam
-- update time: 2017-08-04
-- app_name: 683570

addappid(683570)

addtoken(683570,"11195244821970244535")

addappid(683571,0,"54d97a9eeb07b8338f32b8ae6d9412e4c3e752e149b21c51e0d7a57323e3c613")
