-- generated by KeySteam
-- update time: 2017-07-23
-- app_name: 685390

addappid(685390)

addtoken(685390,"15449555978575757757")

addappid(685391,0,"77e99ada893c634dc9e7c48879a0543454996e7549ecdb29150efe6385d7aa71")
