-- generated by KeySteam
-- update time: 2017-09-12
-- app_name: Tokyo Dark

addappid(687260)

addappid(687261,0,"ff3d2dd1487a9a94db6c10c283d9c82bbfcb85ab86ebdcaf6029554dc15e9b65")
addappid(706580,0,"bf33e464ecafd0c8879a80e4859ba079ca57b6d241fdbfb83eec69cd0a3ed7bd")

-- DLC: 1/1

addappid(706580)