-- generated by KeySteam
-- update time: 2017-09-22
-- app_name: Doodle Jamboree

addappid(687360)

addappid(687361,0,"7f62da240437b0344c9eab9da35dac163001458122e4205d8ce9031fc471adae")
addappid(687362,0,"9ac0435cbb7945df864b6dc76f29b2e38c7aeabe2ac2fda37f75225b397a4921")
