-- generated by KeySteam
-- update time: 2017-08-08
-- app_name: 689080

addappid(689080)

addtoken(689080,"4565296154002382767")

addappid(689081,0,"d9ea114df4eff78c3adbfb0a7b4bb081b7e3ad2c36596d3c64c1ac8d4d24d9fd")
