-- generated by KeySteam
-- update time: 2018-04-09
-- app_name: Sky Hunter

addappid(690460)

addappid(690461,0,"6d843e605e0bade4ba4312dce691388ca10ad9b5432abc7a0efde4194204f080")

addappid(696331)
addappid(696570)
addappid(731630)