-- generated by KeySteam
-- update time: 2023-07-12
-- app_name: In the Village of Grandfather: Summer,Sun,Heat.

addappid(690500)

addappid(690501,0,"427b5af7ed232d702af4110067c9436ba262c365e78fec25f99a6864fb2ad8ed")
