-- generated by KeySteam
-- update time: 2017-08-03
-- app_name: 691660

addappid(691660)

addtoken(691660,"15211834248720784661")

addappid(691661,0,"6bc6fad1bbda2aad34eca7713f6c31d81fe5ec3c24c3e3ace2c0e0d22cada06d")
