-- generated by KeySteam
-- update time: 2017-10-25
-- app_name: 692180

addappid(692180)

addtoken(692180,"4283731750244543556")

addappid(692181,0,"c8543e841e5f769088ddd8b6aae05ca7ad940a3086b2bfce0a3cf59c17ef8db0")
