-- generated by KeySteam
-- update time: 2018-01-24
-- app_name: Hard Era: The Fantasy Defence

addappid(692260)

addtoken(692260,"15979591118393384900")

addappid(692261,0,"0d272062fd01c9faa3da570d7dc563075d0721d831e24f448eed6e73b18f6a09")
