-- generated by KeySteam
-- update time: 2019-08-27
-- app_name: Underworld Ascendant

addappid(692840)

addappid(692841,0,"369994d75489c1470cce9292474f5b40810c41732c8bf42e0515d86e2df931fc")

-- DLC: 12/12

addappid(869980)
addappid(870215)
addappid(870217)
addappid(870219)
addappid(870220)
addappid(870222)
addappid(870223)
addappid(870224)
addappid(870225)
addappid(870228)
addappid(975420)
addappid(975421)