-- generated by KeySteam
-- update time: 2025-12-23
-- app_name: Bloodstained: Ritual of the Night

addappid(692850)

addappid(1041460,0,"2c19abb45d89483fe9c472010021ec0c562d84d899c95ddec3c790be5b38a5dd")
addappid(2380800,0,"ea34e52a8ed5dd5224ebc4fc59b61ac0e039e99814be125d48ac84445301784a")
addappid(2380801,0,"53471e1a66ed778aec25e1d97bb5984842ceaea23e626815dea9a5e444db91fd")
addappid(2380802,0,"7edcfc402e1ec88ddfa6d6980e93b542bb1e44d25b7c91ede8a5bc2fdba6fe54")
addappid(2380803,0,"0eed91ff956f249361d9daa24928e52fec0a6f789680cb1a166b78482bb404b6")

addappid(1041460)
addappid(2380800)
addappid(2380801)
addappid(2380802)
addappid(2380803)