-- generated by KeySteam
-- update time: 2018-04-15
-- app_name: Doki Doki Literature Club

addappid(698780,0,"ed445b469f4232dd8cadc03437edb2338e6f1133128f276bc8324e10d7f3b5b4")

addappid(698781,0,"c24a048a8453bd60406b67d609faf739001185d7e0de5388cabdea3b45b0c73b")
addappid(717250,0,"bf6eb99cce9dbf17167ae51987b809bf3e95a8e1e0d55a5387065d4404eb6eba")

-- DLC: 1/1

addappid(717250)