-- generated by KeySteam
-- update time: 2021-09-09
-- app_name: Fell Seal: Arbiter's Mark

addappid(699170)

addappid(699171,0,"a6a19247bafe572cc53c2ee1f2c86ea33c6af6dafd0c13fc7ee6b8ad466dd3e8")
addappid(699174,0,"cbb6e67068851d25c18d73fa378eb251f1a8cb1b748a55a7a8bae8267f7a0b8d")
addappid(699177,0,"1b58d70174489f0ed8e97e9c13e625ea3d3a3714d47c3323b59198aebe63c523")
addappid(1155320,0,"ce2e68b73360ee26bb0db24c8d6a0e4890d46a00fd7982fc29676d5cffa6bd41")

-- DLC: 1/1

addappid(1155320)