-- generated by KeySteam
-- update time: 2026-03-08
-- app_name: 异端尖叉

addappid(2181610)

addappid(2181611,0,"5a03d9d0c80ec83426e64dc7850226cd8471d4715a8d6274913d832946937f1a")
addappid(2589740,0,"c97fcd0cd658dd2e0e3ceff1bdc985282a18a16ae64afd946b3c19eed10d7664")

addappid(2589740)
addappid(2744540)