-- generated by KeySteam
-- update time: 2026-02-28
-- app_name: Monster Knockout

addappid(2181620)

addappid(2181621,0,"a7bedd17f3a6ba86683a8a0a3ec6d8db4e46d636a82c8dbbaaba1a3f00506a63")

addappid(2258600)
addappid(2258610)
addappid(3420470)