-- generated by KeySteam
-- update time: 2026-01-05
-- app_name: DR LIVESEY ROM AND DEATH EDITION

addappid(2181930)

addappid(2181931,0,"855fed2de6c56315ee1e987c549bad7917ae168dc87c075ef656e185eae595b1")
addappid(2181932,0,"92d1eef57f9c612d61e18278a3d7e9f8b3073f322e282b5aa2e7cb751f46891c")
