-- generated by KeySteam
-- update time: 2026-04-06
-- app_name: 放置文明

addappid(2181940)

addappid(2181941,0,"9e92101116da086f1ae243d5106e9a14e396d4939f7fb6478e24ce44fcf91cc6")

-- DLC: 2/2

addappid(2788080)
addappid(3399010)