-- generated by KeySteam
-- update time: 2022-10-16
-- app_name: Zombies in Metropolis

addappid(2183490)

addtoken(2183490,"12208015817327977432")

addappid(2183491,0,"ce33de01b0cb9b72850f8bbb0779609b543e75f9fc98f24e29064e170d649cd0")
