-- generated by KeySteam
-- update time: 2024-02-22
-- app_name: 重返深渊

addappid(2185780)

addappid(2185781,0,"42b07f01a4faa2c66c58d95ce40238638fa3452a0f56e84292fc3509cfefc699")

-- DLC: 6/6

addappid(2314410)
addappid(2314411)
addappid(2314412)
addappid(2412590)
addappid(2561740)
addappid(2561750)