-- generated by KeySteam
-- update time: 2024-03-05
-- app_name: ghostpia Season One《幽灵镇少女》

addappid(2192620)

addappid(2192621,0,"8f9989f1eb84753fe67e98a24a7ef3066473ea85b22f63a17ed1746a8456fae8")
addappid(2538471,0,"db3ec9a96d5fc08b638d257e11e5a847b3b45e981f5f910ed2aeff8e3c3ee2b1")

addappid(2538470)