-- generated by KeySteam
-- update time: 2023-04-16
-- app_name: Escape!!

addappid(2196570)

addappid(2196571,0,"b73a9ed49d409d3ef1f71c3b447debfed4cb04ebce21ad9c82e98109ac906212")

addappid(2204610)
addappid(2392410)