-- generated by KeySteam
-- update time: 
-- app_name: Tex Murphy: Mean Streets

addappid(302330)

addappid(302331,0,"47b5561d1e76416a969c8b2757972852e065f87668f974209510dc45423f942e")
addappid(302332,0,"93ddfd60b3e5bfb0d4168d28c4e55b3f51cca1014a50983546d7cfda8898c054")
