-- generated by KeySteam
-- update time: 
-- app_name: Tex Murphy: The Pandora Directive

addappid(302360)

addappid(302361,0,"2f55b027eab980cb80a22389041d5c1a309f41879ad30645e41b18279330d03c")
addappid(302362,0,"36de0f2b4b920c23ba6e178639bb9aa1a12d4731da30cb1f112dc30b05fdb4cc")
