-- generated by KeySteam
-- update time: 2019-08-21
-- app_name: Buzz Aldrin's Space Program Manager

addappid(308270)

addappid(308271,0,"dce4afb250acf0d94d2f98bc1fe4bba6667b0be9de609427ef3d17dcde12be28")
