-- generated by KeySteam
-- update time: 2016-04-07
-- app_name: Knights of Pen and Paper 2

addappid(310060)

addappid(310061,0,"410e46050d8a9e0373ec4415d2bc8fc4e3dece59e3512b30c862861040dff0e5")
addappid(363700,0,"e838027aa753df8225db9d93f3da9310e333d3b9cc330d148c61214939587f75")
addappid(363701,0,"27f0beaa18fccef633c43333f3d262203900407cda9d982446ad74d1e9160d36")

addappid(363700)
addappid(363701)
addappid(363702)
addappid(363703)
addappid(420640)