-- generated by KeySteam
-- update time: 2026-02-24
-- app_name: Naval Action

addappid(311310)

addappid(311311,0,"f6cef5d884c5388e8ef8d7d216236d741b9f5797b7c84fcd2b1450e5b350a498")

addappid(785910)
addappid(814110)
addappid(867240)
addappid(885270)
addappid(904370)
addappid(1045170)
addappid(1045190)
addappid(1054070)
addappid(1054071)
addappid(1143890)
addappid(1214480)
addappid(1307430)
addappid(1307440)
addappid(1412530)
addappid(1588640)
addappid(1588830)
addappid(1869320)
addappid(2322810)
addappid(2402190)
addappid(3010160)