-- generated by KeySteam
-- update time: 2020-07-11
-- app_name: Eufloria HD

addappid(221180)

addappid(221181,0,"7e31bdf78eda08ea4277b1e2c80f8baca85e06d525dffb0e9b0ca03a67f2ecc9")
addappid(327040,0,"14b048a6a4a96fbcb07310038ff56a41e36116fb890d44d46eeca9446a9b7376")

-- DLC: 1/1

addappid(327040)