-- generated by KeySteam
-- update time: 
-- app_name: 230630

addappid(230630)

addtoken(230630,"1717636495111549482")

addappid(230631,0,"4c2d9ad1b8845042daa463106005d0007a8c1d61bbb8892348e8b5cdaffb1406")
