-- generated by KeySteam
-- update time: 2019-10-16
-- app_name: Euro Truck Simulator

addappid(232010,0,"cb0437f9728729be64ca1b1ef35fd3b088a6501b6fdddf807f36a583b84f2238")

addappid(232012,0,"eee24598d30f66f53b02477b62b46e26866a3a4af6f45b9c9b60f900705ccd9a")
