-- generated by KeySteam
-- update time: 2023-12-04
-- app_name: Strider

addappid(235210)

addappid(235212,0,"f6d661cba339f2c874731a36916f13b62cdd6c17a99cde94fa5decb56e7d3b95")
addappid(278610,0,"b88e6a98be71d98985d966f3fac895d1ae226d64a028137ce32de8abc8db2413")
addappid(278611,0,"52f7331d7ae43793e129085abdf830427317791b5578452f092ef978e7d6e23e")

-- DLC: 2/2

addappid(278610)
addappid(278611)