-- generated by KeySteam
-- update time: 2026-01-13
-- app_name: Legacy of Sin: Ill-Boding

addappid(2585580)

addappid(2585581,0,"ebf0182bb881ffb042075d779cfffe6b41bf77d9f8a0d00df2dbbab57f8377b1")

-- DLC: 1/1

addappid(3485490)