-- generated by KeySteam
-- update time: 2023-09-03
-- app_name: 2588730

addappid(2588730)

addtoken(2588730,"13248962948964421763")

addappid(2588731,0,"e76094e45b796ffe4a7fa52f41eb29304c37bd8140564226bd19386e1ae02e44")
