-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: 希特勒是我的暗恋对象

addappid(2595860)

addappid(2595861,0,"b195524f4c4facf9a070a85a64a5ed1c2c2eb85b90bfc8a86760da23a038ac90")

-- DLC: 2/2

addappid(3129600)
addappid(4353010)