-- generated by KeySteam
-- update time: 2020-01-17
-- app_name: 警察模拟器

addappid(1140440)

addappid(1140441,0,"5543534b8abadbdbafa82b1ce1812ec8a80cd8da2f1b123e30bfd0bac2426cdb")
addappid(1140444,0,"08d206dfac473b4955d6bb8c0ae4a660fbb6ce4aacfe2307fcf1491f7378a7a5")
