-- generated by KeySteam
-- update time: 2026-01-07
-- app_name: Beat Aim

addappid(1142220,0,"dc556872795b3453d5812b980236a4ac8c09a216333fce9d85de7df5c0478b65")

addappid(1142221,0,"23a1202b5a6f3e071cd2037db76ed80dc890cb59370c0456581737a7b3f93ee9")
