-- generated by KeySteam
-- update time: 2020-03-24
-- app_name: WAIFU HELL

addappid(1144250)

addappid(1144251,0,"9ae7c9da4425e1e017fb087c6553980c44d994bcc1e970a0b3c6c952f7ccc79c")

-- DLC: 1/1

addappid(1163520)