-- generated by KeySteam
-- update time: 2022-02-12
-- app_name: 妖语

addappid(1146630)

addappid(1146631,0,"d6677ff8c86e5325c89f53ec13f6a2786d222216470de4ee86fe15a6d25de946")
addappid(1218040,0,"07d01be2d74f287c3bdd45075ad45710462a7959a63a24a13ec42c16bb67b2bf")
addappid(1347520,0,"f9664ec1895f1f65ddae50d52c2b5bfbce9752aa0e342a9ac2cb4de749f88dfe")

addappid(1218040)
addappid(1347520)