-- generated by KeySteam
-- update time: 2019-09-12
-- app_name: Solitaire Game Halloween

addappid(1148090)

addappid(1148091,0,"8996d07299fe04556f83a6cfd222bfd2cf4ecfe8827b4a0741bee43d318a7470")
addappid(1148094,0,"49b6a93e63f87a09f9eaa93d18db000cc1629146569e6d74276b20b2ffb8d39c")
