-- generated by KeySteam
-- update time: 2023-06-27
-- app_name: Trails of the Black Sun

addappid(1152940)

addappid(1152941,0,"a1404e8fe04707fa751d8a39abe8f0b49c7af4b9741e020b0bb7456a77e05dd7")
addappid(1152942,0,"579a1151e54b1c9f0213d43f4839dba0823ed65de3c119163343a6907596979d")
