-- generated by KeySteam
-- update time: 2026-04-15
-- app_name: Book of Travels

addappid(1152340)

addappid(1152341,0,"8fc7e899ad351f74aeaaf5fb7995faff59fc5c36525a4d2dd323715066dbc999")
addappid(1152344,0,"7a6aeff4e41bfc67af65cf6073c1c4d0ba3d7d130f628b82a99144fcb27c3454")

-- DLC: 1/2
-- missing DLC: 2223580

addappid(1783460)