-- generated by KeySteam
-- update time: 2019-09-16
-- app_name: Dual Blade ~ Battle of The Female Ninja ~

addappid(1155490)

addappid(1155491,0,"6997c0e72b17e88c29622b6f932ecdb73f41bb80c02f68dd2c0387e9d971a902")
