-- generated by KeySteam
-- update time: 2020-08-10
-- app_name: West-Ward

addappid(1156770)

addappid(1156771,0,"12976b4c237c53bfabaa9f0f26f3c30407b484fd1b996e68788c58f196b90a11")
addappid(1156772,0,"fd830df47d4314ecbd111d82455bb986ca692824f80e618423be46c5366f5ddd")
