-- generated by KeySteam
-- update time: 2024-03-22
-- app_name: 2905590

addappid(2905590)

addtoken(2905590,"4776952012173874675")

addappid(2905591,0,"81a667558c35d2e0458efd13f1874c039a7e6cff197b20d204fe1fdffc13fdf1")
