-- generated by KeySteam
-- update time: 2024-10-04
-- app_name: 索尼克×夏特 世代重启：现代索尼克 经典皮肤

addappid(2909780,0,"d4bca264bdbcdde86f3167d63185b55ea30748dc1670b75bd2c48fe00b16ec08")

addtoken(2909780,"13118782285101610559")

addappid(2909780,0,"d4bca264bdbcdde86f3167d63185b55ea30748dc1670b75bd2c48fe00b16ec08")
