-- generated by KeySteam
-- update time: 2025-02-03
-- app_name: 👑选王之剑：零👑

addappid(2919560,0,"5f86b2d0adfe20075ff688afb89b85c75b02eff623bc2c1f717540d2aa66e967")

addappid(2919561,0,"24b1810f009a486a4b39e1792008e046dc3a178658d6682c19590324c5468b0f")

addappid(3114710)