-- generated by KeySteam
-- update time: 2018-06-01
-- app_name: Common Hanzi Quiz - Simplified Chinese

addappid(860030)

addappid(860031,0,"b48a1d788845495d084f42cb3dac2d762da1917514b3c7ec6037b684f8cfa571")
