-- generated by KeySteam
-- update time: 2018-05-07
-- app_name: Math Problem Challenge

addappid(860380)

addtoken(860380,"16378251285124967272")

addappid(860381,0,"f90e4f70ce1953cb394a4c0bc17242325476ed445da5054a85897f3a6b3fb617")
