-- generated by KeySteam
-- update time: 2018-05-09
-- app_name: 862040

addappid(862040)

addtoken(862040,"1691561861630115376")

addappid(862041,0,"19bfff5df263a2d7d5c9f66928420a9bf91cf7a6411738ff34c449371a9d0d9d")
