-- generated by KeySteam
-- update time: 2019-03-23
-- app_name: Gravity Jump

addappid(867800)

addappid(867801,0,"ea8f0506afb8fbdd3d155e7caa802d85cfe68fcd49de676dc5cff18f45062696")
addappid(869430,0,"d2f0d446abcd4930977edfcafb0d7c7ffa17388cd2119a3dd94715e0f54bc70e")

-- DLC: 1/1

addappid(869430)