-- generated by KeySteam
-- update time: 2020-01-07
-- app_name: Hope of humanity

addappid(868710)

addappid(868711,0,"a31860c25f90d055621e4828798c23130be2e5f8999cf21dfc595c9f84a2671e")
addappid(868712,0,"da82f87e7acf42132d742d19f48bc8871cef8ef11dff0ec16762ee1473464f90")

-- DLC: 0/1
-- missing DLC: 1219660
