-- generated by KeySteam
-- update time: 2018-07-25
-- app_name: 869320

addappid(869320)

addtoken(869320,"7546261981320227027")

addappid(869321,0,"9a8c66cfbd2ed77675723aaf0be214d6d497bbab92bbd69c7b5e7f24cad0aa39")
