-- generated by KeySteam
-- update time: 2018-06-01
-- app_name: 869590

addappid(869590)

addtoken(869590,"6368293315898182787")

addappid(869591,0,"d5e7126f668ec15da92a158a614b264b25816651a4ef67e8e2190558d7dca185")
