-- generated by KeySteam
-- update time: 2018-06-08
-- app_name: 869780

addappid(869780)

addtoken(869780,"8472050742403883453")

addappid(869781,0,"b9df17efe3a43223ceec6e3d8b44a02beff3b3b213e36802285e2b68fa931be9")
