-- generated by KeySteam
-- update time: 2026-01-19
-- app_name: Galaxy Trucker: Extended Edition

addappid(870690)

addappid(870691,0,"caf2eb70248ee1bf52a9d22d4b737f9c8e1790cc2886afa1a5952695580a35ed")
