-- generated by KeySteam
-- update time: 2019-06-20
-- app_name: 灰色幻影扳机第5卷

addappid(871280)

addappid(871281,0,"6d57833bc9201ae2cb86c56352b863279840f7de6baad99de2dd0655435a778e")
addappid(871282,0,"ef128c78bfe765a3367d327bc3ecef8639d0798411bbc487a03d306f4e706fbe")
