-- generated by KeySteam
-- update time: 2018-07-01
-- app_name: 871450

addappid(871450)

addtoken(871450,"6254894656120052967")

addappid(871451,0,"05265e5f9fd5abfe97530482d910fc4ac419ccead9a8162194010207cc2c5cad")
