-- generated by KeySteam
-- update time: 2018-05-27
-- app_name: 873360

addappid(873360)

addtoken(873360,"6152358909309729714")

addappid(873361,0,"eb54baa030f178b3ef704b020b8053779e477e86e3fef13c75692eba177d8442")
