-- generated by KeySteam
-- update time: 2018-06-03
-- app_name: 873700

addappid(873700)

addtoken(873700,"15292553345518835592")

addappid(873701,0,"24ef8f8ad5b1e15839a7eb2ea6a1b0fa86023a7ff5278c990bedb4566839f7d5")
