-- generated by KeySteam
-- update time: 2018-06-05
-- app_name: Let's Split Up (A Visual Novel)

addappid(876290)

addappid(876291,0,"8bffb7323b99cbc2cbe3ef2555825cb2bee65ac896ed68c819a3cbda47c638ca")
