-- generated by KeySteam
-- update time: 2018-09-11
-- app_name: Sumerian Blood: Gilgamesh against the Gods

addappid(877310)

addappid(877311,0,"ad062f8e9f5bfd98ffd0363841987221924f88a28115256fe70c19b6eb2a6f6c")
