-- generated by KeySteam
-- update time: 2018-09-29
-- app_name: Thick Light

addappid(877760)

addtoken(877760,"10879754369217853078")

addappid(877761,0,"6ced8306f01d977896a7d875ae989f62b3f197a2d84340df720b7cd22ac78dfe")
