-- generated by KeySteam
-- update time: 2021-08-18
-- app_name: World Soccer Strikers '91

addappid(877870)

addappid(877871,0,"ca88b2e279b29d71c7d3016627a358666f2fddb71a9c7987bd72f73128664b6a")

-- DLC: 0/1
-- missing DLC: 1433760
