-- generated by KeySteam
-- update time: 2026-03-07
-- app_name: Tribe XR | DJ Academy

addappid(877850)

addappid(877851,0,"ccad8c1141394688ea99a109d23f0e15b356be8db2c5319766e2fb79eb50bc35")

-- DLC: 10/10

addappid(1077060)
addappid(1093940)
addappid(1093941)
addappid(1194360)
addappid(1194361)
addappid(1214620)
addappid(1464880)
addappid(1502870)
addappid(1628460)
addappid(2411700)