-- generated by KeySteam
-- update time: 2018-07-10
-- app_name: Sally's Salon: Kiss & Make-Up

addappid(878520)

addappid(878521,0,"69d16135ebb0574fe32e9724fde570f88c37d8e80e082ab08273f32245325aee")
