-- generated by KeySteam
-- update time: 2018-08-09
-- app_name: BORIS the Mutant Bear with a Gun

addappid(879060)

addappid(879061,0,"7a071d3b1ce85b5ee0237122eeb0b20a3f82b70e4dc78e679eb750db6ad69d4d")
