-- generated by KeySteam
-- update time: 2019-08-20
-- app_name: 1st Core - The Zombie Killing Cyborg

addappid(879270)

addappid(879271,0,"a276fc90ec727d38602a3d3794958a315aad643a1f2cd0be4ce82238295300d6")
