-- generated by KeySteam
-- update time: 2025-03-28
-- app_name: 偶像演唱会☆Under Ichigo Love me baby!!! in TOKYO SUPER ARENA 2025

addappid(3500840)

addappid(3500841,0,"CFF06B26944D6ED01CAC158E0A5B9967C2B52C0CC3E7E8A6BB7BA4D68DB229CF")
