-- generated by KeySteam
-- update time: 2025-02-05
-- app_name: Freeforce Airplanes

addappid(3515270)

addtoken(3515270,"14140426606086201774")

addappid(3515271,0,"eac28c168df39975d0cd85f28e76ffdd01510a8000d8fcab076b1f0e93563e04")
