-- generated by KeySteam
-- update time: 2016-06-22
-- app_name: 383030

addappid(383030)

addtoken(383030,"10864229366076636166")

addappid(383031,0,"a40ceb6e064874ad35618c2f66222aafe0dd1e8fbf7d22ee6648090baafd8ecd")
