-- generated by KeySteam
-- update time: 
-- app_name: Slybots: Frantic Zone

addappid(384100)

addappid(384102,0,"bc78f8f8ed14af56ed93b26ec8e81670070590b55e877799c14a7347f811f754")
addappid(384104,0,"b6d03f4a119e7a14b40183619ced1e523b6c9e508c10c6389cacff4d3b02a68c")
