-- generated by KeySteam
-- update time: 2022-12-21
-- app_name: Blood Code

addappid(386480)

addappid(386481,0,"fcbada8188b60108b51f19ec8fad943e88d29903333a0ad8b8a97629ab0967cd")

-- DLC: 1/1

addappid(457720)