-- generated by KeySteam
-- update time: 2025-01-13
-- app_name: Spooky Bonus

addappid(388450)

addappid(388451,0,"f291df7f2f4ca572a252950e56723f003341fcbfd0361b54799874d7630fffee")
addappid(388452,0,"3c8d1f48417883aeff41bd0495c281ebec91e794da3df044bd86455204cef803")
