-- generated by KeySteam
-- update time: 2025-10-03
-- app_name: Horizon Chase Turbo

addappid(389140)

addappid(389141,0,"b701d7dd3a6c31a23eaa83ded7b72728699ba4d822037d08c55f33ab6c04a498")
addappid(863521,0,"80f7f5b36927564fed2173e60c64c1fc651c0cd2b58b14e582ccd20226392c6d")

-- DLC: 4/4

addappid(863520)
addappid(1137940)
addappid(1174880)
addappid(1608540)