-- generated by KeySteam
-- update time: 2025-10-17
-- app_name: Mitos.is: The Game

addappid(389570,0,"89ccca46db6b43649b880880d6aaf64128b3ca34d88e9acda231cfd5f37355e5")

addappid(389571,0,"3ad1880aa4488c4945d57bc1a3b1c6bb73d8eb5e75bd65f7439e2ee3a7f390a8")
