-- generated by KeySteam
-- update time: 2024-01-26
-- app_name: 拳击俱乐部

addappid(394310,0,"7502d139a0a3bd12111c5f5bee7ca139b395d0bef2efec4217f6548c2083b928")

addappid(394311,0,"eb8e09ffae72cf2b7d9b19f3ec8b25acd9135c665c26017047a74a2998ba71c4")
addappid(431490,0,"2254d8c81372e2923dd5979569eb313478009b44d236978b318adbb796feb9b8")

-- DLC: 1/1

addappid(431490)