-- generated by KeySteam
-- update time: 2016-06-23
-- app_name: Ben and Ed

addappid(395200)

addappid(395201,0,"ca694c01dcc9f9bf8319a7fdec56dc00adacc83d4606043eb20a65423daccd28")
addappid(395202,0,"3d4b9c027dca060ef7a2d02238199e4ece71d251cdbf6d68b2f1930b6ca4a291")
