-- generated by KeySteam
-- update time: 2017-04-05
-- app_name: Sengoku Jidai: Shadow of the Shogun

addappid(397190)

addappid(397191,0,"58780f55bedd88037c768589b72bc21702d20e80bb378324f28eaf7e58b6db5c")

addappid(461930)
addappid(461931)
addappid(461932)
addappid(461933)
addappid(461934)
addappid(461935)
addappid(502360)
addappid(502361)