-- generated by KeySteam
-- update time: 2017-05-20
-- app_name: Super Bomb Rush!

addappid(397810)

addappid(397811,0,"b265ce008b344c74dafdf6dd9bd382edac20f1044c0cf6d4d67bd8031281e909")

-- DLC: 1/1

addappid(432580)