-- generated by KeySteam
-- update time: 2026-03-10
-- app_name: Business Tour - Online Multiplayer Board Game

addappid(397900,0,"7fd743ce52a7d009b7587919b80a632347f621bc6e1b4058eb67ba015718dbba")

addappid(397901,0,"004c56553d38452e960e65fa55a078ec817e63e8950dd328b3d97451153226fc")

addappid(511840)
addappid(716790)
addappid(797240)
addappid(819240)
addappid(842000)
addappid(862610)
addappid(865210)
addappid(880350)
addappid(880351)
addappid(893700)
addappid(906060)
addappid(915590)
addappid(915591)
addappid(1024050)
addappid(2305850)
addappid(2305860)