-- generated by KeySteam
-- update time: 2017-11-20
-- app_name: 399270

addappid(399270)

addtoken(399270,"3755172348553042029")

addappid(399271,0,"a49246fb4680d116755c1130f09bedf7094bd9a3fd4ae8b62330d7f3c67f260d")
