-- generated by KeySteam
-- update time: 2016-07-25
-- app_name: Game Corp DX

addappid(399670,0,"564cae2b018d699fd15bd33d51fc3db1ee59e6217f78f74c80ec865bc3ebaeb4")

addappid(399671,0,"0620b21bf6be8f37be532c64cf806aa62408f451b6aaaf9aa120af23061363e3")
addappid(502491,0,"39c7a66630ea50e4953f177c91a58e2710acc55076de0a9a105c4c5e59afbf40")

addappid(502490)