-- generated by KeySteam
-- update time: 2024-03-31
-- app_name: The Symbiant (共生纽带)

addappid(1883090)

addappid(1883091,0,"2ed3e6e43f9e58ad0b7f6f43d7f62b9e4dcce79030941d7c3a64d945412d254e")
addappid(2261481,0,"b9f2c41e52caf06d4e37cfba4186ce7c1f4e109f2b659fc712c8a390a2acdfd2")
addappid(2261491,0,"11d792a53caa7a0c0d4693c19dfbf85fda401624cb285c5c292538e0e2d4c0e8")
addappid(2277881,0,"80fe11554b9c291410eb1faa0ba2b9ae29cfec36cb871d9354f6347c6fcfabd2")
addappid(2326981,0,"e30a6035d825b0549221198e64f1fedb21f6738da4888ed9948abd2d110d3490")

-- DLC: 4/4

addappid(2261480)
addappid(2261490)
addappid(2277880)
addappid(2326980)