-- generated by KeySteam
-- update time: 2022-04-12
-- app_name: Golden Rails: Road To Klondike

addappid(1886400)

addappid(1886401,0,"1e380ee9746cf9ad5683ebfa636cb5ec988c49884fb76a2da4193f6983a0f68f")
addappid(1886402,0,"c046c137a85830df718f8c9a7923db738dbd40dbf26b14fae6e5221d6b9cf23c")
