-- generated by KeySteam
-- update time: 2023-11-30
-- app_name: ALAN-13 Reformation

addappid(1888130)

addappid(1888131,0,"cae87f92804f572f0b43baf8d9f3b40da5edeebfc9b9de297729cb9236e10fa4")
addappid(1888132,0,"fd2b5b1327f8e88aa05192ad507efdab21d9984ce594f5d8546243c5b3d0a887")
