-- generated by KeySteam
-- update time: 2023-06-28
-- app_name: Maze: Pedestal of Trials

addappid(1892240)

addappid(1892241,0,"64c435cf94fceffe1f97024ee223a70266aa151b5f63bfcce44c40f3c0ca0533")
addappid(1892242,0,"7839d79c51dcb24e3f935bbf616a0c42ef88ad537bc781e8cbb71af0494e5f74")
