-- generated by KeySteam
-- update time: 2022-03-18
-- app_name: 1001 Jigsaw Detective 2

addappid(1895550)

addappid(1895551,0,"b3233173ba3b5871e726e0bb9daa9f8f59cdac92343202c299084fffc573dbf8")
addappid(1895554,0,"8ce2b003a2f359bb783eaa3b527e9b301ebb31dfab87580278b79049eae11cf0")
