-- generated by KeySteam
-- update time: 2023-01-13
-- app_name: 鲜血之爪

addappid(1896090)

addappid(1896091,0,"970953a5f48152b468052aefd277cdf417ad4cf38cc495a8f376897a5b36d29d")
addappid(2270660,0,"47aa12461f5c81f359e8a4631114fb4533d69118afa5b9506086373fe5a68eb8")

addappid(2270660)