-- generated by KeySteam
-- update time: 2018-04-27
-- app_name: #Have A Sticker

addappid(841860)

addtoken(841860,"14090007310291609529")

addappid(841861,0,"d3904aec36cd66b7d190b7dce1110e9e5310390db511a76fefa3049a46a4a582")
