-- generated by KeySteam
-- update time: 2025-10-04
-- app_name: Gem Rush

addappid(845860)

addappid(845861,0,"97a565441e2de145c0c745be4263a14c1c8107b4231a63499e0c5818a4f0eee3")
addappid(845862,0,"06635ca60b8a1852948015fbb2a2535b6635ca2399eb3a5a1c4a8eeabbb371ad")
