-- generated by KeySteam
-- update time: 2018-05-24
-- app_name: 848650

addappid(848650)

addtoken(848650,"15890804325409983563")

addappid(848651,0,"6aa785861c24ed4ace25a0c3eeca233179edc4e96201d864a8424ac30ab029d1")
