-- generated by KeySteam
-- update time: 2018-08-31
-- app_name: LUMINES REMASTERED

addappid(851670)

addappid(851671,0,"a52d6f893a3bd97c89b5a9791a7431131e438415e5ed0751b73f56a7f717604b")
addappid(852430,0,"795802960c12b5951c1a45aeab49469f719a12197a218b569bac79fd475e4acf")

addappid(852430)