-- generated by KeySteam
-- update time: 2021-02-02
-- app_name: G2 Fighter

addappid(851800,0,"4b984a69bc385b416723d793d69ace9968180a3b17cb6c10d8f0dc192dac89d6")

addappid(851801,0,"0aeab049adb7f79e3cf7109f88b3511a9c7d35fb933bef32c47397b36561f865")
