-- generated by KeySteam
-- update time: 2024-08-22
-- app_name: Paper Shakespeare: Stick Julius Caesar (with a dagger)

addappid(854530)

addappid(854531,0,"4f8170798080454f0cb84dc35f88f5f30cd2b6b2c32229be18cc6507495b678d")
addappid(913611,0,"4354c028e66415f70f1c3520ed9e81fd852847190e538853ad55f61df3dd7481")

-- DLC: 1/2
-- missing DLC: 913610

addappid(913611)