-- generated by KeySteam
-- update time: 2024-10-20
-- app_name: Sword Tale : Lost Excalibur

addappid(3305630)

addappid(3305631,0,"201BF63145E95B2E08AA37B0B9D7FDDB4025B7C0266132614129C134107FA2F1")
