-- generated by KeySteam
-- update time: 2026-01-12
-- app_name: The Berenstain Bears In the Dark

addappid(3319650)

addappid(3319651,0,"18166f6139db9a48815112834001d9879e91e282fa572a65e0e96261add6da6f")
