-- generated by KeySteam
-- update time: 2025-06-18
-- app_name: Battle Against the Acolytes of Science

addappid(2941950)

addappid(2941951,0,"66C87C394C766BD83D031D0132C2F0943C467B2C92A286329B31B2F22BEECF02")
