-- generated by KeySteam
-- update time: 2023-11-10
-- app_name: 2663770

addappid(2663770)

addtoken(2663770,"2157497038262940418")

addappid(2663771,0,"4906c7fda41f80b2e8b8a0e977f865fb4c32f0b7b945bd548490f944afd9ed64")
