-- generated by KeySteam
-- update time: 2024-09-16
-- app_name: The Adventures of The Black Hawk

addappid(2664930)

addappid(2664931,0,"A00BA7A6C36E5042E9190CD403F0CF8BD1616D274A1A90B19F53941307125F9B")
