-- generated by KeySteam
-- update time: 2025-06-28
-- app_name: Car Parking Real Driving Sim

addappid(2671480)

addappid(2671481,0,"35311d0ecebc5ec86e7ca50fc7419c21bbf860624ae94a780ce4d29b15e83873")
