-- generated by KeySteam
-- update time: 2024-11-26
-- app_name: Tales of Seikyu Playtest

addappid(2523170)

addtoken(2523170,"4189977128687648023")

addappid(2523171,0,"7da930bde22683a4d9b4cc11e371d478c6001c6a79806ad630ef3ee8e6648e16")
