-- generated by KeySteam
-- update time: 2024-06-14
-- app_name: 物宅空间 Cozy Space

addappid(2524480,0,"b7418705db1df950060408e349ae624aa140f76d60c70d3a15dabd3f26a5d07e")

addappid(2524482,0,"9467b2ad0422cdb1cbe3253df9008c92fff875e37f5139ea65e2a1dec5e80f8d")
