-- generated by KeySteam
-- update time: 2023-11-04
-- app_name: Soul's Majesty Rise of Gilda

addappid(2524590)

addappid(2524591,0,"3ac157357e00d6ac63f466bf20b431559902fd7753532dc5928b32bd1fb9a1bb")
