-- generated by KeySteam
-- update time: 2026-04-15
-- app_name: 古魂

addappid(2524220)

addappid(2524223,0,"f41aaccd2056d49a1f5966672da006ddfd954ae64267191b03d67bbb94ff134e")

-- DLC: 4/4

addappid(2590930)
addappid(2604350)
addappid(2607530)
addappid(2607670)