-- generated by KeySteam
-- update time: 2024-04-15
-- app_name: The Lost Prince

addappid(2525830)

addappid(2525831,0,"a173d661a9feb42a6c2146efffc7082d1ad4daf0ec0b1e852c7efeca52f19706")
addappid(2701530,0,"c3d2a5740230d825ff72c6883c9660dc67125edbb703c8b31303d9c41ba83ce3")

-- DLC: 1/1

addappid(2701530)