-- generated by KeySteam
-- update time: 2026-02-18
-- app_name: 方块公国 (Drop Duchy)

addappid(2525310)

addappid(2525311,0,"4f575923f1b939467dae8a961bf95e3c380dd3594554f5f67b1c64fe7edd3409")

addappid(3839960)
addappid(4091080)