-- generated by KeySteam
-- update time: 2021-01-11
-- app_name: Skill at Time

addappid(1520260)

addtoken(1520260,"3889494943423225671")

addappid(1520261,0,"9de44c84422447f99f3b860b5c3007a8021fe695823d34258076eef8105919e2")
