-- generated by KeySteam
-- update time: 2021-03-28
-- app_name: Silent Earth

addappid(1531790)

addappid(1531792,0,"9e16e0c5244f8ab7a9b815234711cadb282a41c2149fd92640001d27e6918900")

-- DLC: 0/1
-- missing DLC: 1561700
