-- generated by KeySteam
-- update time: 2022-10-25
-- app_name: The Fridge is Red

addappid(1532460)

addappid(1532461,0,"64352555846e0e06a68617151fa193cc19b91662ff9c2ff895149691fe8a4217")
addappid(1532462,0,"633f1f40267e354c321cee2852fdbcb41c6729fe40d43b6259a0156ff0222ce6")
