-- generated by KeySteam
-- update time: 2022-03-30
-- app_name: Bow & Crystal Tower Defense

addappid(1537940)

addappid(1537941,0,"42f4e389b7c3025a55f90a63884948f84b560e464dc4cc9752c6b78efea23613")
