-- generated by KeySteam
-- update time: 2021-01-30
-- app_name: The Chronicles of Hercules: The 12 Labours

addappid(1538650)

addappid(1538651,0,"338a45a0c682f2d7940da57aef7e02d68a17a8dc1d6cfbd198bf7919fb32b5da")
addappid(1538652,0,"b25a9bb90f0160cbfbce34ebb073e66d594c55aa05d8b84f68d877412c8d19cc")
addappid(1538654,0,"e39ffc4f04d0f374201c31986a14cc03c9b21d55b425f9bdd7c8f937c342acb5")
