-- generated by KeySteam
-- update time: 
-- app_name: 264480

addappid(264480)

addtoken(264480,"16839124779470641561")

addappid(264482,0,"d532a6b2bbdf71f2379acd17ab59e247dbcbbae23343d6f40698b2758315898c")
