-- generated by KeySteam
-- update time: 2026-02-21
-- app_name: Anarchy Arcade

addappid(266430)

addappid(266431,0,"3d052e64a9f1c780d40de3395b9b7fbaac5736e3bd38fbc41eb05e00de390ada")
addappid(266432,0,"dd353c7c24201628ac90878d27b8654e028c26333e9d11c819c46467303ea6a2")
