-- generated by KeySteam
-- update time: 2026-03-16
-- app_name: iRacing

addappid(266410,0,"a60f70202110ecd44e88040bc4e1978aabc1b7d3b18282e676a16aa4a57d45f0")

addappid(266411,0,"c6926148df6b91b2ca1e691ad992d112a63e9ef46f067d86ad73e0e6220a310d")
addappid(266415,0,"178e63e412c7306dfaef0daf0941e930181b56ae738df0feef6e403dee85aaec")
