-- generated by KeySteam
-- update time: 2023-08-31
-- app_name: BADLAND: Game of the Year Edition

addappid(269670,0,"244b058e4d15fb81f138d74eaa1c32ec220f049784e2ee603d58d2c848a114dd")

addappid(269671,0,"80ef90a3cf557af8085a83d6d535d7c8a107d5ae95adfdebef1168a471529704")
addappid(367210,0,"7831ec253295e19f56d18bc1d97ec8c259b9b333146724487ae48dbf86cfe5ed")

addappid(367210)