-- generated by KeySteam
-- update time: 2026-02-16
-- app_name: DiggerOnline

addappid(278970,0,"d8a8d2bb0e9b57cd3c8a0f34119b2dbc61daaec6a09cdd31eea2e421b94e94f9")

addappid(278971,0,"5e84a8f7805aa5e101a63f19439368c1e69d110235f4fbcbe6455744bdb66c24")
