-- generated by KeySteam
-- update time: 2025-09-24
-- app_name: Geneforge 2 - Infestation

addappid(2480560)

addappid(2840550,0,"b58628193f1b4213fa9780f553c744d5064c69b9849c28863070b503bbf06490")

addappid(2840550)