-- generated by KeySteam
-- update time: 2023-08-25
-- app_name: 2480280

addappid(2480280)

addtoken(2480280,"8592679667272867431")

addappid(2480281,0,"347e096d07cecc20cf21f875ab89728b8c32a677ff402e72bbe6e4d305c23744")
