-- generated by KeySteam
-- update time: 2024-01-05
-- app_name: Where the Music Dies

addappid(2483250)

addappid(2483251,0,"27c134ea58b2fbeec6843ba8f6d68de40e52623f594732af49c15da1c3968f98")

-- DLC: 0/1
-- missing DLC: 2681400
