-- generated by KeySteam
-- update time: 2026-02-28
-- app_name: FINAL FANTASY VII EVER CRISIS

addappid(2484110)

addappid(2484111,0,"b3a968d9a6cc78c6beb8210974b098248155fb4c1381c8ee468f6dc99d7f0a9d")
addappid(2484112,0,"b6770454a863cb2ee2e3ec060612354adf7ad3f475da995a11311ef0e90cdbd7")
