-- generated by KeySteam
-- update time: 2023-09-10
-- app_name: Broken Hearts Island

addappid(2499420,0,"310fef508edb38633120c906ce139555e65a08bad611832c72cbd00aeb5f90ae")

addappid(2499421,0,"d4b043b1b804c4e8e1c9d759c4dbab0b8f5621cac2f74ad6d42145cc391a8b32")
