-- generated by KeySteam
-- update time: 2020-10-28
-- app_name: Project AETHER: First Contact

addappid(940140)

addappid(940141,0,"c91baaccee6b40f42ce40c2bb43b94baa1ed5cbf3cbb4518d3b7e06dc3a8fefd")
