-- generated by KeySteam
-- update time: 2018-09-07
-- app_name: Dark Romance: The Swan Sonata Collector's Edition

addappid(941040)

addappid(941041,0,"12b4d01f8f6e0c74c4f40353722ee1c7b69fb34a47b1489451e36117ba90fe00")
