-- generated by KeySteam
-- update time: 2018-09-19
-- app_name: 941870

addappid(941870)

addtoken(941870,"10264650971859392351")

addappid(941871,0,"cf702e133ab4fe1d7749525190c7f1d7f39a72ecdf72cc39e67c50ce2a18a25d")
