-- generated by KeySteam
-- update time: 2018-10-30
-- app_name: Roads of Rome: New Generation 2

addappid(947970)

addappid(947971,0,"b832a36a069f558299f8c6b0bf73c7f4b1f23fa0eb0ba96e117bf6def998c809")
addappid(947976,0,"4662603e0e78d9ee34c4463b57c362e4b556d98c3f6dc28a2ce754ad2119ab6d")
