-- generated by KeySteam
-- update time: 2023-02-24
-- app_name: Royal Booty Quest

addappid(948350)

addappid(948351,0,"92fab5555da638834308ddc9afe7aedb8061dedec2b679c046ae1bf074f625bb")

addappid(1004120)