-- generated by KeySteam
-- update time: 2019-04-29
-- app_name: 951090

addappid(951090)

addtoken(951090,"8912088500900636751")

addappid(951091,0,"594b8504df9f2e7fe94f7fa6d0b5ae3afdb11645bfa056ae7e07944e6366db3a")
