-- generated by KeySteam
-- update time: 2020-11-12
-- app_name: Alien Shooter - Last Hope

addappid(951530)

addappid(951531,0,"97adef70c3b686f7d5ea008ffa9b47e4bd270079cb6e22ad33306f8f4c623cb7")
addappid(951533,0,"5774837a45730d5140eb8cf0c5f5a712544cce2eaf428e3b8eb4b9039cf5badc")
