-- generated by KeySteam
-- update time: 2019-10-25
-- app_name: stikir

addappid(952200)

addappid(952201,0,"15b2440723c3a73f4b90ad2e7a570cf366435029d46cdc9ff89a73914a982c85")
addappid(952202,0,"81b66b0c1dca2f25aa14dd81e73446c0b15f71555ba5e086ba966da35dd27822")
