-- generated by KeySteam
-- update time: 2020-05-18
-- app_name: Dark Fantasy: Jigsaw Puzzle

addappid(955320)

addappid(955321,0,"2a17707471a2484fae3e8d3ff7a50c0fea555690ea9fa158fe07e895744113b1")
addappid(981610,0,"b3affb6b4740afeba24d648fc7c369d81ca81b95e02312697e8cee3b35154671")

addappid(981610)