-- generated by KeySteam
-- update time: 2018-10-24
-- app_name: Grim Tales: Bloody Mary Collector's Edition

addappid(956400)

addappid(956401,0,"7f631a72f41252be8d31c830d8dd5aeaa7801cd51ebd8f17372e61ae9de6f6b9")
