-- generated by KeySteam
-- update time: 2024-03-03
-- app_name: VDoll

addappid(2122110)

addappid(2122111,0,"9c54e31d25daff232da2195a6509ac3fad21f2fed42eb68a4cb73f1584274636")

-- DLC: 0/1
-- missing DLC: 2161420
