-- generated by KeySteam
-- update time: 2025-01-08
-- app_name: Ultimate Destruction Simulator

addappid(2136990)

addappid(2136991,0,"c7baa2ef045de180c763b7028b94ffbbed45db067b63b39d4007e6c51a54ae97")
