-- generated by KeySteam
-- update time: 2026-03-26
-- app_name:  AI2U: 与你直到世界尽头 ~ 我的病娇猫娘AI女友

addappid(2880730,0,"e1385c26e6800c05cc866d28488906abdeedbb1ed47c225d4e7d5f3ef9f6e199")

addappid(2880731,0,"e2ca87b16b3ac8c52ccd235d0e58670b6d208f1fa79f280ba0b72586dc36340a")
addappid(2880734,0,"b329b1ca5b99f4e76fddaf0e29537e9b7553b08ebe73195c6bb126945c9c990d")
