-- generated by KeySteam
-- update time: 2024-03-18
-- app_name: 2889570

addappid(2889570)

addtoken(2889570,"5465772214444523963")

addappid(2889571,0,"4ce12e7fe5e0676c49cea93a4d9702bce1d44872988cf1af7a2b752cfb2b3b68")
