-- generated by KeySteam
-- update time: 2025-04-07
-- app_name: 日本之旅

addappid(3001560)

addappid(3001561,0,"c9d8ebc9f17694690d406e2cba154ef6cfef0913258c98ca7214568bf3db0796")
addappid(3001562,0,"b069130f1d9de53d708ccfd2780a23ddb6135e4397cfc4e02698c4b59ae79df0")
