-- generated by KeySteam
-- update time: 2025-10-23
-- app_name: 与长生狐一起的30天

addappid(3845600)

addappid(3845601,0,"2d8364f2c5ac538d21eae15a9d72aa05fb83c2441ae893803d6b9f071569d3fc")
addappid(3845603,0,"d86ad6f2608d9e73d3235bafa31f6f32940bab52b0445e4f43835890739f0c84")
addappid(3845604,0,"a4a7fde02df89e85d3e99cf4bbb9a9ca65d438fb483fc1fbd15554d6272cac1a")
