-- generated by KeySteam
-- update time: 2026-01-23
-- app_name: A fascinating story 2 Demo

addappid(3850660)

addtoken(3850660,"15905888874845416259")

addappid(3850661,0,"acc2cf8d02cf75ed0dc380a61c10cbae732264371b4484e04cc6d5623d506fbb")
