-- generated by KeySteam
-- update time: 2025-11-07
-- app_name: 3853840

addappid(3853840)

addtoken(3853840,"5517258558651904531")

addappid(3853841,0,"90a9a9d1b213ec74bc162d151c6a63e83031e1d6e04a568a0d1668aa2ed07899")
