-- generated by KeySteam
-- update time: 2025-03-12
-- app_name: Waifu Love

addappid(1444860)

addappid(1444861,0,"b488b785a663f7fb9036cf131eeee96193621fa85f4f45fb84b4de2258f76f7a")

-- DLC: 0/8
-- missing DLC: 3561650, 3561660, 3561670, 3561680, 3561690, 3561700, 3561710, 3561720
