-- generated by KeySteam
-- update time: 2026-03-05
-- app_name: Frontline Grunt

addappid(1446950)

addappid(1446951,0,"dd08eaccfbad8f41c8e46d3c58d3bb7d66065d5dc01372db9a86271345e34f8f")
addappid(1446953,0,"8127fbb54bf148756fa59849784729edd2b734c53805a8e2d75d185c142251db")

-- DLC: 0/1
-- missing DLC: 2585680
