-- generated by KeySteam
-- update time: 2023-01-13
-- app_name: 饮料吧侍女 -回归-

addappid(1449330)

addappid(1449331,0,"ebb59ab7d79dda6561bd2f43ed2e93d2e2694c3df77bcce9dd1e1fb253274fe0")
addappid(2295330,0,"fc6c5a9b89b078ec72575697739e67e1b7b0c6050168c9283398e9a6ecc15b55")
addappid(2295331,0,"af8b433ee26a1761df1ffa43c7f74a254a80fe04a08df21fcd007e9d648fddd1")
addappid(2295332,0,"145268a612b3e66abd4c0d2eb278c8b7c866d7a4c2bf3d9dbecfe5aa34f0ff56")

addappid(2295330)