-- generated by KeySteam
-- update time: 2025-10-14
-- app_name: DUNGEON ENCOUNTERS

addappid(1451080,0,"e04fdcfc8dc3985c648f941cc5201285753c7345245a3a3726ad44a0ea16aa93")

addappid(1451081,0,"1e9210b049d3d5ab438ca571f7708025b302639f1beee2d284025fffb51911ee")
