-- generated by KeySteam
-- update time: 2025-02-04
-- app_name: Cookie Clicker

addappid(1454400,0,"bee35fc41b9a4f44f4d1017924dcc20a9241b2755b02a3178baee78dc2f49ab9")

addappid(1454401,0,"dc8be6e8bb8cf9a7d3f548fe759eb532def1c3d380deece391d81dafa6c96e67")
addappid(1454402,0,"39c00dfd8ff729f8012400b55fc6d55b1c21b5ee2b012fe72a6c33b5b5ec176b")
