-- generated by KeySteam
-- update time: 2025-08-10
-- app_name: 玩具郡 Toy Shire

addappid(2361460,0,"d0f24f9f5b4231fd35d4ca0c54755b43cb1649fccbcfebe63555b6339bad0805")

addappid(2361461,0,"6c8e6c05dd18bd60d8e9b322876fe53dc50e732db4866fa8e68a214889ec8c0c")
