-- generated by KeySteam
-- update time: 2023-05-29
-- app_name: 2378760

addappid(2378760)

addtoken(2378760,"10898605418975738042")

addappid(2378761,0,"945744e40b02f2edbb1e03a32c2ae91f40832259db028069ca83a62f2794ac87")
