-- generated by KeySteam
-- update time: 2020-01-20
-- app_name: Puzzles for smart: Underwater Kingdom

addappid(982750)

addappid(982751,0,"3c243ded42303f2fd0407f768483c7144876834d72c79ec5bcc7e75b765811b1")
