-- generated by KeySteam
-- update time: 2018-12-20
-- app_name: Nusantara: Legend of The Winged Ones

addappid(986710)

addappid(986711,0,"fe3ec5febf7da8183c8e228e14d20def6039e1877be0c3abdad815c4c380c060")
