-- generated by KeySteam
-- update time: 2022-06-13
-- app_name: The Legacy: The Tree of Might

addappid(986830)

addappid(986831,0,"1af0798913bad1601fbab30726bed78964acdf2701889f1d3afe48ddb12021b9")
addappid(986833,0,"afc4af9f85e95bb693f78080eb540ba1dec7c000627a8700727ebbd62819fe93")
addappid(986834,0,"46f711e2a4f7412c43d57596e9737ed969d289af7bc8a9ca1928fefd762f1c34")
