-- generated by KeySteam
-- update time: 2018-12-01
-- app_name: Aliens Don't Exist

addappid(989340)

addtoken(989340,"8110390376126474417")

addappid(989341,0,"f0b8fb6b27206054a3620e136f2f84f5def662af4ee6f3fc02c2e401a0dba529")
