-- generated by KeySteam
-- update time: 2023-09-21
-- app_name: Super Spooky Subgame Spectacular

addappid(2540000)

addappid(2540001,0,"863896725c5221a8dc60e7fa73fc0d24413403fb16deccbf14f5bf818f18bfcd")
addappid(2540003,0,"fbf07c617b9ee3d6768e901bf87ef282d3b623cda635bef99873a67b21e71cd3")
