-- generated by KeySteam
-- update time: 2025-07-02
-- app_name: 리프 인 부트스트랩 - LEAP IN BOOTSTRAP

addappid(2544590)

addappid(2544591,0,"a2a6282e724ebb6e35e21f6c300123192b0faec6d0d2118fdbe6239bceb47431")

-- DLC: 0/2
-- missing DLC: 2559040, 2967740
