-- generated by KeySteam
-- update time: 2024-02-01
-- app_name: Little Kingdoms: Chapters 1-3

addappid(2548680)

addappid(2548682,0,"88d38b065fd3b78165bade1daa81328889be571cd8389342e1662f3b071ec153")
