-- generated by KeySteam
-- update time: 2024-03-28
-- app_name: TEMPEST : Tower of Probatio

addappid(2552340)

addappid(2552341,0,"6c9aae9a0990c20e21970a476f2abd90a392595616989e0686defa65249ebe9c")
