-- generated by KeySteam
-- update time: 2025-11-09
-- app_name: 蔬菜斗恶兔：解谜游戏 Veggie Quest: The Puzzle Game

addappid(2402170)

addappid(2402172,0,"0ae86cc954a2443a6def8fc1465092f5b9076f69e7d042acc61d3acb7edf9e7c")

-- DLC: 0/1
-- missing DLC: 2757020
