-- generated by KeySteam
-- update time: 2023-05-25
-- app_name: Kingmaker Academy: Warrior's Duels

addappid(2409690)

addappid(2409691,0,"00778d1da528c25739fdeab8551a3a73750c77b0d87efada507862c8124e3de3")
