-- generated by KeySteam
-- update time: 2025-06-28
-- app_name: Breeze of Passion

addappid(2409780,0,"993ac38cf14b8166e52b6cef1ed25e2e60f053fb4477acfa108818a507c553b2")

addappid(2409781,0,"65720792d0c5ccc087188c5b45c2b6b8aa2ec5bdc4861d6cbe54c9fee4e82afa")
addappid(3691540,0,"7eadceb592dedc740c09d32c09a911612993d1ccb6947c05047f3c5915da9596")

addappid(3314120)
addappid(3691540)