-- generated by KeySteam
-- update time: 2024-01-18
-- app_name: 神探加杰特：疯狂时光派对 (Inspector Gadget - Mad Time Party)

addappid(2409500)

addappid(2409501,0,"b7ad4993b3f1bb36218cbaf4cf707771059b1941a7f19dc6eafeef9896697889")
