-- generated by KeySteam
-- update time: 2025-12-18
-- app_name: Ostranauts

addappid(1022980)

addappid(1022981,0,"23cc5af30ebc1c8e4c2abf3e5b4114dbf78fffbb24855fa3ac13ed24a116c3ab")
addappid(1022982,0,"076062f175ac5ad3eb3c620073f57acb90bb47aa2b176446df99b9eca4ea54ef")
