-- generated by KeySteam
-- update time: 2019-03-22
-- app_name: 1-Bit Revival: The Residuals of Null

addappid(1025480)

addappid(1025481,0,"cca2ac18a958cdfdb5311cef4d88b9168a20a747fd73cbe6773e31adc721fb51")
addappid(1025482,0,"0a4d4dec7ec87b16d7253764b88c8e5cf933717d9d9f0000808bfbebb0946a78")
