-- generated by KeySteam
-- update time: 2020-02-18
-- app_name: The Amazing Shrinking Giraffe

addappid(1033220)

addappid(1033221,0,"ef15a615911e7bc3b392a3589b501dc51a082039fecb53a1a5728ebcf2f129ed")
