-- generated by KeySteam
-- update time: 2019-04-26
-- app_name: Puss in Boots: Fear Not Hooman

addappid(1034820)

addappid(1034821,0,"d2909cf3a92de7ba33789f0c9dbfed3fa935160f1a80f222c38ee402d6aa8c1a")
