-- generated by KeySteam
-- update time: 2019-03-16
-- app_name: Escape from the tomb tower

addappid(1035500)

addappid(1035501,0,"0ccef45524371cb70a7e64350a6cbc87022eacb500e9ba1c51a7b3f860167fe0")
addappid(1035502,0,"c76720f2adf9ff76de098aa47e2bd248be89b8608f76c88e199cae325e3170af")
