-- generated by KeySteam
-- update time: 2019-03-23
-- app_name: Song Animals

addappid(1036200)

addappid(1036201,0,"e6e655f85c561b42499bd24daa9b6f2ae87b88bb1afece0c4ac0a66f72802626")

-- DLC: 0/1
-- missing DLC: 1036220
