-- generated by KeySteam
-- update time: 2020-11-18
-- app_name: Zakk Hazard The Deadly Spawn

addappid(1037150)

addappid(1037151,0,"e6938dda13d209f008ac74ec9949d5c204e682c4b007f9832bd8ca403012674a")
