-- generated by KeySteam
-- update time: 2026-03-29
-- app_name: Spire of Ash

addappid(4450160,0,"907565bcd5022f58feeec0bfd427a2ffd4679c8d78db844b9e762bec02b3287d")

addappid(4450161,0,"0f85365fbf769556bfb8b50fab38872d135c41b4850a529f674395930d2a855f")

-- DLC: 1/1

addappid(4526170)