-- generated by KeySteam
-- update time: 2025-08-12
-- app_name: 请成为最能干的VTuber吧！

addappid(3044740)

addappid(3044741,0,"7fe1736dcd0fdddc507d4692a06a7610a694c6875eeeca84ae09158c2ddf2165")

addappid(3780670)