-- generated by KeySteam
-- update time: 2024-12-31
-- app_name: Sellsword Saga

addappid(3047500)

addappid(3047501,0,"9CFEAB279FE8B6724A54C0B2F54E734B989062580CEAAC258521EFFB3B490A36")

-- DLC: 0/1
-- missing DLC: 3595310
