-- generated by KeySteam
-- update time: 2026-01-09
-- app_name: Gretel and Winslow's Mansion

addappid(1767320)

addappid(1767322,0,"504b576ceaaa90173f03b98f07c414a68477bf3467561c589f46462c6dd03f99")
