-- generated by KeySteam
-- update time: 2025-08-28
-- app_name: Road Trip to the End of the World

addappid(3769330)

addappid(3769331,0,"C7EFBF3B160B73013BB7271D09C4392D9C215B0092601F77C0D094B9558AA0AE")
