-- generated by KeySteam
-- update time: 2026-02-18
-- app_name: 超级帝王蟹模拟器 (Super Kingcrab Simulator)

addappid(3773390)

addappid(3773391,0,"034ec026e64f410bb5a5725e01ec1492f4f30098d8e015690a240756c5d715ab")
