-- generated by KeySteam
-- update time: 2019-01-17
-- app_name: Super Life of Pixel

addappid(327260)

addappid(327261,0,"f70084a21e55ccee797e2e305f80c4998e8b4704df5a15252f4936c535514b9e")

-- DLC: 1/1

addappid(369410)