-- generated by KeySteam
-- update time: 
-- app_name: Vampires: Guide Them to Safety!

addappid(328780)

addappid(328781,0,"48b8ce22330cadfdcc1a53437734bd53ab4e7d5bd9c1546d7a1f1cf62f4af62e")
addappid(329180,0,"f0e6f1c30cb338734afcfcdbc2f585db8beb38eb7d70c06e21e3a14b180bc10d")

addappid(329180)