-- generated by KeySteam
-- update time: 
-- app_name: A Druid's Duel

addappid(333970)

addappid(333971,0,"922c4c876832694bc436d671e4de4248d2abd5f18b549d15378f384a32bfbfb3")
addappid(333972,0,"c7e3b6ced296444fd7a3f1419f6354630ad9a3487defbf3e1db54c5a9347396d")
addappid(333973,0,"009e78438411e72d917945913fe9cc34ae37568f54a42cca4996b503c0a16ad4")
