-- generated by KeySteam
-- update time: 2026-02-23
-- app_name: Demise of Nations

addappid(338810)

addappid(338812,0,"8da608b5c1edf0220cf5eb8dfd62156218fe9c6d0f6a320f15c1f0e829e2dd4f")

addappid(2006900)