-- generated by KeySteam
-- update time: 2017-03-06
-- app_name: A Pixel Story

addappid(339460)

addappid(339461,0,"fe0e38efa190a85b8331ce666cb398ef6c705cb8c51b7b5b9e9139da7cf4a9fd")
addappid(357440,0,"c847aeacd45853c75cd9f2014362b840546a2e6bf2eed2a45eaba3bc5af9ec1c")

addappid(357440)