-- generated by KeySteam
-- update time: 2022-12-26
-- app_name: 姊恋游戏 - Siblings Role-play -

addappid(2262040)

addappid(2262041,0,"e6e1210aa49c8e1841915470d9342f906718fe601aa95dd2b811ab145880ac62")
