-- generated by KeySteam
-- update time: 2023-01-24
-- app_name: 2270920

addappid(2270920)

addtoken(2270920,"15852751502445425804")

addappid(2270921,0,"0f8766f0297c213ffc01d5c01974ff162cc3b5e6ddaf397fb9a78af8d0175292")
