-- generated by KeySteam
-- update time: 2023-08-26
-- app_name: Thief Simulator 2: Prologue

addappid(2272420)

addappid(2272421,0,"b465e2f33c308bc187dbebb5e3d3a154a49f12a89d306ef12320a8eb82a9b9eb")
