-- generated by KeySteam
-- update time: 2023-01-05
-- app_name: 2273400

addappid(2273400)

addtoken(2273400,"1125763698371346821")

addappid(2273401,0,"0a53195101ed72bc0d63ec93c1194aef83f90e9d58fdf72cc1bf72bda7fff964")
