-- generated by KeySteam
-- update time: 2025-12-06
-- app_name: 100 Radioactive Cats

addappid(4212340)

addappid(4212341,0,"92123f9a827d98f30c458dfe65f8c3624f59e3cb6f2dd486cf0115441168ceec")

-- DLC: 1/2
-- missing DLC: 4212840

addappid(4212850)