-- generated by KeySteam
-- update time: 2026-04-03
-- app_name: 宗门起源

addappid(3446240)

addtoken(3446240,"12366859424522752049")

addappid(3446241,0,"ddbae286524f900e39fb2c0e6d35401e7a94444b87a43825104ae7a128279543")
