-- generated by KeySteam
-- update time: 2025-07-30
-- app_name: 麦穗镇物语：放置好时光

addappid(3447510)

addappid(3447511,0,"1b25479bb3f84d9747e1b244ce6246e6b1a50330b267ff867f4c95e80d1e7071")

-- DLC: 1/1

addappid(3896900)