-- generated by KeySteam
-- update time: 2026-01-19
-- app_name: Résop Paz Yandere True ( R-pyt )

addappid(2768440)

addappid(2768441,0,"a9438153a7cafa7aa421922f7218fbdfc0deee48a834f2143ed89dc52211992c")
