-- generated by KeySteam
-- update time: 2025-07-25
-- app_name: ZomBay

addappid(2776480)

addappid(2776481,0,"11481661B56E178CD2A0A4A1E8949DABF4F919ECBEC31C1137803A42DBD1AA56")

-- DLC: 5/5

addappid(3308850)
addappid(3310270)
addappid(3333970)
addappid(3349790)
addappid(3356580)