-- generated by KeySteam
-- update time: 2026-04-01
-- app_name: 女王的游戏：盛世天下 媚娘篇

addappid(3478050)

addappid(3972390,0,"54ce84a9747fb4dadf6076ce0d851004973cc0593493aa0d29e71084f8cd324f")

addappid(3972390)