-- generated by KeySteam
-- update time: 2021-04-29
-- app_name: Jets'n'Guns 2

addappid(830820,0,"1d3526d3e83096165bb804ea1553b9641b4e32cfdafe40c4614cb1159074cb3a")

addappid(830821,0,"f4c6ba87a23d47cddd094e16be14d6c4e395c79e9c6af7caf8408d3de165b3ad")
