-- generated by KeySteam
-- update time: 2025-10-09
-- app_name: Hotel Magnate

addappid(832360,0,"d966062d0b1291980db70cfa61e7c6b0b3fcce6a4c5b45b8c7c4c67aa9a6a479")

addappid(832361,0,"2af7df4c274be9ac7bdec33394dd6206800f6c16b3e17a82cceef72c51ddcef0")
