-- generated by KeySteam
-- update time: 2021-06-24
-- app_name: 東方逆妙乱 ~ Ephemeral Unnatural Balance

addappid(834580)

addappid(834581,0,"3e780f173d9fe2e7b0266a311912717a4f73f4155338765b58d8f34c40e7b1d8")
addappid(1165300,0,"c2da22e1346a9edae676314b7370793ddeda7ed6a301199916d1f4e017d39f23")

-- DLC: 1/1

addappid(1165300)