-- generated by KeySteam
-- update time: 2018-11-06
-- app_name: TapSonic World Champion VR

addappid(837640)

addappid(837641,0,"cf79e591681d500e6720134a6a20f60660d1139c713b728dc5f98db5e2914f9b")

addappid(883800)
addappid(908040)