-- generated by KeySteam
-- update time: 2018-06-01
-- app_name: Bloodstained: Curse of the Moon

addappid(838310)

addappid(838311,0,"72aa46d79ba01711edd6facabfdc3181da46456897e9a51a04618cbdc04878d3")
