-- generated by KeySteam
-- update time: 2026-02-05
-- app_name: Phoenix Point

addappid(839770,0,"0d41e5b2f0274fda368919edf5d919041cd8cfa668a7ae163e5f443347166a4d")

addappid(839771,0,"332cfa106a9342d144de52e56d95ebe11b1bf5415e689c29c215f712db05bea2")
addappid(1357480,0,"aa477376a0154312123af1c97856b852a6917ca69bf759537ffa6c36ac700550")

addappid(1357360)
addappid(1357370)
addappid(1357371)
addappid(1357372)
addappid(1357480)
addappid(1619320)
addappid(1622220)
addappid(1622221)