-- generated by KeySteam
-- update time: 2025-12-25
-- app_name: 网瘾少年2005 Internet addicted youth 2005

addappid(2461780)

addappid(2461781,0,"45a160cad384c17d4301716d48288513f87f2b189c63936dcc562451c6c495c1")
