-- generated by KeySteam
-- update time: 2026-03-09
-- app_name: Dungeon Stalkers

addappid(2468730)

addappid(2468731,0,"130C5E50E0FA36DE027261C4BBA4D167CB11D32A5755D71511EDCEF01A30B750")

-- DLC: 1/1

addappid(3913120)