-- generated by KeySteam
-- update time: 2025-10-17
-- app_name: Soulbind: Tales Of The Underworld

addappid(2468470)

addappid(2468471,0,"c772b3aeef46170292129dafea70265fbdc0fb1196333f0889a3813422f2605c")
