-- generated by KeySteam
-- update time: 2025-06-18
-- app_name: Mortanis Prisoners Prologue

addappid(2469550)

addappid(2469551,0,"d027f81882363b5af4d1c49691a28de89ad4d4780918f20576be7b5e3a5299fe")
