-- generated by KeySteam
-- update time: 2024-02-21
-- app_name: Kittengumi: The Sakabato Thief

addappid(2469050)

addappid(2469051,0,"97d35cfa5a3e26b21341ad00ba81f7c49ded92ece86b5d31c9c5db27458e82ca")
