-- generated by KeySteam
-- update time: 2024-04-08
-- app_name: Pantheon: Card Game of H - Part 1

addappid(2476850)

addappid(2476851,0,"51bf1a50b35fcadbc6b7723631fc08ff176b91217ea560b10277a6f8acfa4092")
