-- generated by KeySteam
-- update time: 2026-04-09
-- app_name: 灰区战争

addappid(2479810)

addappid(2479811,0,"c89db92b0e186d8c1e9db781270fc739b23f152b3e11ed7733f93bba19ce6716")

-- DLC: 3/3

addappid(2633470)
addappid(2914230)
addappid(2955580)