-- generated by KeySteam
-- update time: 2025-05-10
-- app_name: 我的老婆

addappid(3547790,0,"9ad70d70bdabf7cfc8129c24981c0a35b06eeb15c8a62f6622aaf04a88749564")

addappid(3547791,0,"fdca45e5e4ad9e268edfc1e290cd7842c859dac626b2aa9cfa1bb53d7705614a")
