-- generated by KeySteam
-- update time: 2025-04-27
-- app_name: Jumpscare Simulator

addappid(3551600)

addappid(3551601,0,"3b2adb6bf1fffac4173d10381a87233e53fffd40d97365b544316d37aadfacfa")
addappid(3614441,0,"5c6ada1124085942a79bc86fc52c9100bf6aeea007de54620da4c3187c58c8ca")

-- DLC: 1/1

addappid(3614440)