-- generated by KeySteam
-- update time: 2025-06-20
-- app_name: ESCAPE FROM TIMOKHA 2: ARMY

addappid(3554450)

addappid(3554451,0,"04372e0dfb51b09feacab25028b8bbf9a684d8437157db959a46de0e49d4250a")
