-- generated by KeySteam
-- update time: 2026-02-13
-- app_name: Money Simulator: Brokeville

addappid(3555430)

addappid(3555432,0,"1bc56a50226c299e2b7accca279af332221d0dcfe4abcadfcfaabf9ca5277588")
