-- generated by KeySteam
-- update time: 2025-03-04
-- app_name: Year of the Ladybug: Season 1

addappid(3325130)

addappid(3325131,0,"478e761f8465e0041b4d9b67268325471c70652740fa08f7f1796bd18e259c39")

-- DLC: 1/1

addappid(3366610)