-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: 3328440

addappid(3328440)

addtoken(3328440,"11159318252613587197")

addappid(3328441,0,"63bc38b4b90ee4ad639121f8e7f71b2911d5cb01780fd57b68970bf28f03e04b")
