-- generated by KeySteam
-- update time: 2025-10-06
-- app_name: Autogun Heroes: Supercharged

addappid(3328730)

addappid(3328731,0,"2eb28c860b074a6729fde3e0dd4def575d4032ba7ba862f8435c0d026c20337d")
