-- generated by KeySteam
-- update time: 2025-11-29
-- app_name: Retrowave 2

addappid(3331000)

addappid(3331001,0,"a0428c138c350bf0bc84c8c8156bb309fac77ab030cdbadaf1416825c88b5477")

-- DLC: 1/1

addappid(3350730)