-- generated by KeySteam
-- update time: 2025-04-23
-- app_name: CASE: Animatronics

addappid(489360)

addappid(489365,0,"6a8d415e5a1d804e9a1855978f7a58db9e53b332440cd364da835c229449b1fe")
addappid(489366,0,"cc61585909f3303f40ac6ad4ae8ef886412dfa05653602f4b7368f7310264634")
