-- generated by KeySteam
-- update time: 2016-09-02
-- app_name: One Day : The Sun Disappeared

addappid(492610)

addappid(492612,0,"48d0a079cdf7b0c4a6db2e426d888331b5a0d15b8318d0c0f5e2609d4acfe83d")
