-- generated by KeySteam
-- update time: 2025-10-10
-- app_name: Card Quest

addappid(493080)

addappid(493081,0,"f2c98e201f340e2993bdcc7c61f5fb45784b50ec2b395c432ad139572db72ceb")
addappid(493083,0,"6a54818b3f634745928fd58ba2a2e385189379b81f2fcacaa62101443c4df04c")
