-- generated by KeySteam
-- update time: 2016-07-21
-- app_name: Dark Parables: The Swan Princess and The Dire Tree Collector's Edition

addappid(496030)

addappid(496031,0,"68130208d7984d7ed4e4dfaf03789161339d44f788434c37464cc06833101640")
