-- generated by KeySteam
-- update time: 2020-10-27
-- app_name: Mind Spheres

addappid(498660)

addappid(498661,0,"d58f94369040c331a297bdd9383df7c9e6e35c102987c26f738dea1f5f37978a")
addappid(499360,0,"361910a44e227ef3bd16997c1f0656239ef5e7c622029b3ba355078dbc3b1ada")

-- DLC: 1/1

addappid(499360)