-- generated by KeySteam
-- update time: 2026-02-16
-- app_name: 1998：收费员的故事

addappid(3273530)

addappid(3273531,0,"09d60d7670aa3a3185f7a5fa31bb15667bc958bdd7bd5a5d96e31afa73ed7228")
addappid(4102091,0,"4760fb15e5b6be345ca83b45ce7d35658b168a4c3509d8b88be6430ec0aed6a0")

addappid(4102090)