-- generated by KeySteam
-- update time: 2026-02-13
-- app_name: Resident Evil (1996)

addappid(4249100)

addappid(4249101,0,"53fc73ab0ec4b9e6fa4c415e4613c5bdc044ae2462c6c4d898c070822af245e0")
addappid(4249102,0,"cb84cbcb9b6a7d9781651ff812f235d78189a6b8603a6a8d55e23029b727b5d6")
addappid(4249103,0,"f118404bcd07c1213340ef0763197e9fcbce44aaeb046f5c467ffae95d585f20")
