-- generated by KeySteam
-- update time: 2025-02-07
-- app_name: E-Girl RoomMate

addappid(2783560)

addappid(2783561,0,"33795240e11a05d5cc67f26955f39d6cfc7f3205d51c235d4d2b8870069e643e")
addappid(2882510,0,"1a7e078284a2a312a68cc5a386406e6e628b5d44611d30777d5efddb21a612cb")

-- DLC: 1/1

addappid(2882510)