-- generated by KeySteam
-- update time: 2024-12-06
-- app_name: 风流人生

addappid(2788990,0,"aae148e63805f5de346e5860a83537d0e1982b59b9cce26d58dd0c6b5407343b")

addappid(2788992,0,"93f2fc47bac398647ae4d5f46077c992d05b65135612e0a84a5c67ac810054d0")
