-- generated by KeySteam
-- update time: 2025-07-21
-- app_name: Sin Slayers: Reign of The 8th

addappid(2790000)

addappid(2790001,0,"f23c810d3f887937c15f17006d21c1905041a007ee9913cc3e6f3e1fe55b853c")
addappid(3313990,0,"31dfa1391278b513b1682e7fd9202ed850d7c5ce31e07610d4f4541202c4c037")

-- DLC: 2/2

addappid(3313980)
addappid(3313990)