-- generated by KeySteam
-- update time: 2024-02-23
-- app_name: Galactic Gauntlet: The Ultimate Interstellar Challenge

addappid(2796100)

addappid(2796101,0,"6dd9051972dfe4d066705bfa3df0a15db67fc7a9c14591e87dd23ad4f969b6fd")
