-- generated by KeySteam
-- update time: 2025-05-05
-- app_name: Mystery of Myths: Mystery of the Fjords Collector's Edition

addappid(3687320)

addappid(3687321,0,"dc6b4895d8cf78d96076a60fe561f8a6e0141022c76762aef9d5e14afb7a4b39")
addappid(3687420,0,"cb84304694af4b4e1b270c30dcb7fed60784c99143e13738957c42030dc8b5d5")

addappid(3687420)