-- generated by KeySteam
-- update time: 2025-04-24
-- app_name: Mystery Case Files: A Crime in Reflection Collector's Edition

addappid(3695990)

addappid(3695991,0,"f6aa32b13fccde3caa6b84a12ffd584c57ef67c49957bb0c5f49227f54fd9c80")
