-- generated by KeySteam
-- update time: 2026-04-08
-- app_name: VAIL

addappid(801550,0,"c61c6b72c027d13e4fbfd83173dbafb7fc0fe78f824b789b727ea809e1713c40")

addappid(801551,0,"728061a23095cca7547013f02f30eb273a145d3f9c601be56f719c439c127ab5")

-- DLC: 13/13

addappid(2222440)
addappid(2260410)
addappid(2880720)
addappid(3289320)
addappid(3730470)
addappid(3730480)
addappid(3730490)
addappid(3922740)
addappid(3992960)
addappid(4143950)
addappid(4182980)
addappid(4182990)
addappid(4558140)