-- generated by KeySteam
-- update time: 2018-02-09
-- app_name: Whispered Secrets: Into the Wind Collector's Edition

addappid(804990)

addappid(804991,0,"7409e4af91cae9dc07990c9688a2bd81e1c6ccf8449c29f7901e2f9d6f968bee")
