-- generated by KeySteam
-- update time: 2018-05-24
-- app_name: Cubiques 2

addappid(805340)

addappid(805341,0,"722d5fc0650ccfddb81a50d66a55254c65905408900a57c34aeaaacd80193d54")
addappid(805343,0,"5f864460e19aa2fa6c5452034ffdd4a94ea2dd136e724af9e3a5ed0d0857aa81")
