-- generated by KeySteam
-- update time: 2018-02-19
-- app_name: 806680

addappid(806680)

addtoken(806680,"15101286968382603043")

addappid(806681,0,"f98dd5c1c9b3402bfdb0f072b11517bdd5f44972537bb4cb4bca10311a5917c9")
