-- generated by KeySteam
-- update time: 2018-03-05
-- app_name: 811530

addappid(811530)

addtoken(811530,"16767338020344292410")

addappid(811531,0,"29d5eb9b71130faa3805cbc268fa6e8d627a9a1540f57ed243aa0a0c43f8e4dd")
