-- generated by KeySteam
-- update time: 2018-02-28
-- app_name: 813580

addappid(813580)

addtoken(813580,"8678097760619950574")

addappid(813581,0,"5f2038a458019500e1ca5893af1e0a4faaf8ca58d7f5e0834ea25593f5eb2e50")
