-- generated by KeySteam
-- update time: 2026-02-04
-- app_name: 绿色地狱

addappid(815370)

addappid(815371,0,"2d729703a7a551530f0fadf02b8c1da3cb944c4a898295bef1c19722f9f9f3cd")
addappid(815372,0,"03a5e9ecc1760fada61452368cefd3bb2234f78fb25bb7dc481ba9660d781dc7")
addappid(2990430,0,"cc1e64d590434473930b6edd90d09027aa939a0d8b1fcc7d3ccd30f86ea21e1f")

addappid(2990430)