-- generated by KeySteam
-- update time: 2018-08-28
-- app_name: Monkey King: Master of the Clouds

addappid(816630)

addappid(816631,0,"0e9b7b9a970fdd996d7e7706f1b50b8da9ada4275a823338eb59c03c13e1bb48")
