-- generated by KeySteam
-- update time: 2018-05-26
-- app_name: 817190

addappid(817190)

addtoken(817190,"12337890542583454944")

addappid(817191,0,"8ccbace226010ad70ca60f2bdb6f7c31e33c49b22dc49f5a4010f0adb8319103")
