-- generated by KeySteam
-- update time: 2025-03-09
-- app_name: Asylum: Patient Zero

addappid(3568370)

addtoken(3568370,"9623640766369041869")

addappid(3568371,0,"3d8f14cb3908733e409848aed7f979ecb6bd468fce5119c429c60c7bd4414ee2")
