-- generated by KeySteam
-- update time: 2025-05-31
-- app_name: 火箭快送：宇宙饭店

addappid(3569400)

addappid(3569401,0,"046e002844eb263fbc457de41501876a0d8f773acc9ad97cce30a6002c3ad7df")

-- DLC: 0/1
-- missing DLC: 3576450
