-- generated by KeySteam
-- update time: 2024-08-19
-- app_name: 巅峰战斗：再次上阵

addappid(2242420)

addappid(2242421,0,"e8c12c754e50d61f8762000c31790ac56235199819ce733ae7fbebaba8584e3b")

addappid(2817220)