-- generated by KeySteam
-- update time: 2026-01-29
-- app_name: Ratopia

addappid(2244130,0,"8ac54e69d00299cceca860052d27a678fc76c276af0bc21a351dc513f03de24b")

addappid(2244131,0,"7340a83f2505a34c0c785f3f3987f8ce558a86a11e0d806d8d8cd6d7a2f742ec")
