-- generated by KeySteam
-- update time: 2024-06-07
-- app_name: TouhouGensoumarokuW - The Devil of Decline

addappid(2250790)

addappid(2250791,0,"dc27977494055fbde0d337b57a3c6ee4d7177a21c8301da399c0ca94ce371029")
addappid(2250792,0,"42cd5a900dd84baa39269bd36aec9cbd61e3417f4edd5218b7ccdbd18d8c0999")
