-- generated by KeySteam
-- update time: 2023-03-16
-- app_name: Cruise Ship Manager: Prologue - Maiden Voyage

addappid(2251420)

addappid(2251421,0,"89e6a27fba4b9884ccbb7ce10e0c332e9e6d1e3de6eeef4fcd7df87328cf8042")
