-- generated by KeySteam
-- update time: 2022-12-14
-- app_name: 2252650

addappid(2252650)

addtoken(2252650,"1229065989529853950")

addappid(2252651,0,"53467ebd09cb57d6004db7cb3d087941d946f60e0a1e8abbd18083fdb90e3c20")
