-- generated by KeySteam
-- update time: 2026-04-03
-- app_name: Kamikaze Lassplanes

addappid(2253930)

addappid(2253931,0,"be43d2ec2928a93cfcb96cdb9b4fc2653b53b7b2a9dca4fd13458f67caf8c3a7")

-- DLC: 0/1
-- missing DLC: 3570310
