-- generated by KeySteam
-- update time: 2026-04-03
-- app_name: 黑白之地

addappid(2258890)

addtoken(2258890,"15567506376809871243")

addappid(2258891,0,"b72d8df425afc5778a560cf250457c52b1123ce358a058ae05538cea39f9be4d")

-- DLC: 1/1

addappid(2991780)