-- generated by KeySteam
-- update time: 2025-08-10
-- app_name: Tyrant's Realm

addappid(2259260)

addappid(2259261,0,"aa2650859aadcdbb629fb0a080eec79020ca4840d4d6e1da873f965d7f9c420d")

-- DLC: 1/1

addappid(3729840)