-- generated by KeySteam
-- update time: 2025-11-11
-- app_name: Aragami

addappid(280160,0,"60689065685acbd4becba24f4d7ede49cb7af83215cb48666732aa32d6b09133")

addappid(280161,0,"a59b45b063a8d869318256c985ac25e690a1c67fa4c92e41924ea722d974b2a2")
addappid(280164,0,"59df90bcdfb2452f6892515a393beb5bbdb21340d210e0f2e30b4aa7f9dad7a0")
addappid(462390,0,"12cf4bda64deaa146ed0fc9bf1afe76de4d542178cbf4304bf6b2d1e75b17758")

-- DLC: 3/3

addappid(462390)
addappid(564400)
addappid(771720)