-- generated by KeySteam
-- update time: 
-- app_name: The Secret Of Hildegards

addappid(283470)

addappid(283471,0,"7db9a17277eb7d843188aab4801878fa7b451c30817620c996d4fc999a856cf6")
addappid(283476,0,"5430f7a3ea1343ec7303da592b7c7f73edd57c148a7c4c1d2d3705fe1ef6a807")
