-- generated by KeySteam
-- update time: 
-- app_name: Steed Prototype

addappid(285270)

addtoken(285270,"15907709670304219742")

addappid(285271,0,"a81990505a89afd58921f5a848904f6a33e2947f307ee4fd552aeeac1c0be8ba")
