-- generated by KeySteam
-- update time: 2019-05-13
-- app_name: Actual Sunlight

addappid(288040)

addappid(288041,0,"510afdd9bbb4875a080ee830dbc89e3405145d6770b6dcb3342886bb7a595a7b")
addappid(288042,0,"272c62975c782f715a3fdf6266810eb2d893d90534e3140c17bf76c59e507611")
