-- generated by KeySteam
-- update time: 2023-10-31
-- app_name: Black Rainbow Mystery: Amazon Escape

addappid(288500)

addappid(288502,0,"daa338219c1d0f4f07b516b33a4f2ab8fc66cb6e3019a5003c134c3bc45dc068")
