-- generated by KeySteam
-- update time: 2021-12-30
-- app_name: My Lands

addappid(290730)

addappid(290731,0,"df3b5f4ec9c0d85e6af86c2e0dfbf20a959cbc950d310ef5b88689817d5dfa3f")

-- DLC: 12/12

addappid(313300)
addappid(313310)
addappid(313311)
addappid(316500)
addappid(316510)
addappid(316520)
addappid(316530)
addappid(316540)
addappid(316541)
addappid(316542)
addappid(326690)
addappid(326691)