-- generated by KeySteam
-- update time: 2016-11-17
-- app_name: The Journey Of Forgotten Memories

addappid(520590)

addappid(520591,0,"7175b52559935cd1cfe5578914e4699b3aba1bd7b1f51d15301cc16cfc7d5f5a")
