-- generated by KeySteam
-- update time: 2017-10-28
-- app_name: Impulse of War

addappid(520860)

addappid(520861,0,"c02167eaee405a71a93d00684fbe65e12747e433123b87267431dcc6f237c27a")
addappid(520862,0,"ed8d0070fdd68b77240060d89196b9d43ebb10ea56e40bacc7c2c3e73b879dc3")
