-- generated by KeySteam
-- update time: 2025-09-05
-- app_name: Another Brick in The Mall

addappid(521150,0,"be348164f4877511d3c7bd058dfe4c734eb225db1dbbbf13aec0bbf86be8a2b5")

addappid(521151,0,"e8ca0dc6e6ea0ee4f21367724434d17cbe78b4a4d7a6ba1c12d93297c1fba5da")
