-- generated by KeySteam
-- update time: 2016-08-28
-- app_name: 522050

addappid(522050)

addtoken(522050,"4640492143507397600")

addappid(522051,0,"7fdaeac2f54594df4e2d6414764980543d963fd968cc3bb77d6213d00ec10d5d")
