-- generated by KeySteam
-- update time: 2016-10-03
-- app_name: Polywings

addappid(522300)

addappid(522302,0,"5793199485c3caece63cf26e34bae712b432593223147876ae8ecdb9b48fc0dd")
addappid(522303,0,"d4628bdc479a9b44c4adc5756275c1608945f6eb46d656771a0dc42d38ea1f86")
