-- generated by KeySteam
-- update time: 2018-06-03
-- app_name: MY FIGHT

addappid(526290)

addappid(526291,0,"8f51f6022586a9b066a6170babb250dbbc77a6bb9df91e8cab70332abf2a6444")

-- DLC: 2/2

addappid(876400)
addappid(876401)