-- generated by KeySteam
-- update time: 2016-12-03
-- app_name: The Gleam: VR Escape the Room

addappid(526750)

addappid(526751,0,"2bbe3f2918677c8afed84fada58c4e2abb4ebed63d6a01cd70eb4200ae95ceb3")
