-- generated by KeySteam
-- update time: 2016-09-07
-- app_name: Shop-n-Spree: Shopping Paradise

addappid(527890)

addappid(527891,0,"79276c1857c5d2640ac0edafde6598a571902c648c0fbb561aaa6eb7c36a0586")
