-- generated by KeySteam
-- update time: 2019-06-30
-- app_name: Rugby Union Team Manager 2017

addappid(528640)

addappid(528641,0,"a6115cfe64c9267923dc1c47cc3848c2c7df434349c10d6bbbcad2de94f64e28")
addappid(528643,0,"905f4a79db50ea394be73d9b64ded8ad3e1fc13e2bd0cc500413211fd15d9dfa")
addappid(723801,0,"fca05f446b662f1737f600a8932e3b358e9300dcc3672a40337a499cb0ed106d")
addappid(723803,0,"9e577fbae47c78cc8b29524f75c9ce189f3ecfc222f5dec26ca96404d6781f1f")
addappid(723805,0,"53ec3d56e2fc9e0e5c2b47079923db2585439a9b07080bcdbe3bfbf0f2ecf332")
addappid(723807,0,"d8d6c8f0f161331aecfc1d9da7ad9b90147a7ee190f6d7dcd9b2c42f6fc9b9e3")

addappid(723800)
addappid(1051480)