-- generated by KeySteam
-- update time: 2017-11-06
-- app_name: Rogue Trooper Redux

addappid(529490)

addappid(529491,0,"d0f0670c9f1da596eb578bb109b38b25f562809e6ce027a48dc4248473e0ddfa")
addappid(710410,0,"0f290550b39f6a42c4fc022fcfa0b44aa167a88de30fda6c6a0cc8791d4a669d")

addappid(710410)