-- generated by KeySteam
-- update time: 2016-09-25
-- app_name: The Rosefinch Curse（Ning's Wing 1）

addappid(530500)

addappid(530501,0,"4ec4b23d8ad7f77b529750e6eb546f31dca437a0cb99804f839984eb5dee3f2d")
