-- generated by KeySteam
-- update time: 2019-10-14
-- app_name: Non-Linear Text Quests

addappid(531630)

addappid(531631,0,"e30592786f314f0c01f17a8a3c6877a532ed9ebace966d283880d701704cd3ce")
addappid(531632,0,"5fb9fbd6c9079bfb8d97125f6d1bdc2961cedb9391c57c87b6a97d42cab744af")
