-- generated by KeySteam
-- update time: 2026-03-11
-- app_name: The Revenge of Johnny Bonasera: Episode 1

addappid(536430)

addappid(536431,0,"c54ad8b99b043a8191cbb5f8bfbccc63c9d6940bee56b14757b98794001779c5")
