-- generated by KeySteam
-- update time: 2018-12-20
-- app_name: Guts and Glory

addappid(537340,0,"1b1e75652d752c2eb42202dac0a7d4360bc19afa6ed0a11f7e353a3472aa4a82")

addappid(537341,0,"9666002b803cda0f99f93e3397766e9c6c0cb883c255707baf99c801e84a0925")

-- DLC: 4/4

addappid(646860)
addappid(646920)
addappid(646921)
addappid(646922)