-- generated by KeySteam
-- update time: 2022-04-12
-- app_name: HyperFleet

addappid(1720960)

addappid(1720961,0,"9ef9df3996c1c146116acfd005462f37c91baf73c027ae517bfcb36eb87b9b02")
addappid(1720963,0,"e168dadfc6eb9a8ab0e2d0d91a68ca0bdd4c1e8f66d63cae56632870c638cb6e")
