-- generated by KeySteam
-- update time: 2022-05-11
-- app_name: Ari's Journey

addappid(1721240)

addappid(1721241,0,"7e1112892ce1b45b15c26bc23abceac510a914de870153e631f20e5468169a9a")
addappid(1721244,0,"1f346602ecd3477199d563d51114611cbeba18700426901580d82279e0006fb3")
