-- generated by KeySteam
-- update time: 2023-10-20
-- app_name: Epic Fantasy Battle Simulator

addappid(1724440,0,"33031aafd1905c9ab38f5566d7c6f91130b2b414ab76f0b5137ec5515022bc17")

addappid(1724441,0,"207e7b731dced4d692e0248fb7a8242e609154bfa2c91060cd2686f88391274a")
