-- generated by KeySteam
-- update time: 2021-08-13
-- app_name: Surface: Virtual Detective Collector's Edition

addappid(1726790)

addappid(1726791,0,"3105917a3ec09b03564ccdc2e49880522108230c828f5797003dd991db2c2d1e")
