-- generated by KeySteam
-- update time: 2025-11-18
-- app_name: 69 Summon Succubus

addappid(1727100)

addappid(1727101,0,"bbc64f9f1c11d5cb35672da8c63a43d2dd64fb3cb0dc2edfa5d19cddf74ee8c2")

-- DLC: 1/1

addappid(1982740)