-- generated by KeySteam
-- update time: 2025-06-30
-- app_name: Tentacle Prawn: (Actually) A Cthulhu Dating Sim

addappid(1727790)

addappid(1727791,0,"045083A6602C89AE24480B8A0C988C9BDEBFE398E8FF33BEE17FF49033B5C701")

addappid(1923550)
addappid(1923551)
addappid(2246430)
addappid(3245540)