-- generated by KeySteam
-- update time: 2021-12-18
-- app_name: Dirty Fighter: Hollow Point City

addappid(1728320)

addappid(1728322,0,"dc84ebebe72ab710cc5b2f99e0384210f0317cb85e11ebd7cdcb6ec34955ff13")
