-- generated by KeySteam
-- update time: 2024-05-26
-- app_name: Ark Mobius:Censored Edition

addappid(1731520)

addappid(1731521,0,"0c2c9221d2a8e58e8b2ae8079623f5c69d688da1a2ca58aed99858e6515a8379")
addappid(1773960,0,"955479afe31def0baa71e23895bd5353dfc59f3483e9cbceab006bce19a578d9")
addappid(2990130,0,"850ca1e1ff7a527e4d754df51bf28f8d3753d65faffaa8d7edd7e402f97a972e")

-- DLC: 2/2

addappid(1773960)
addappid(2990130)