-- generated by KeySteam
-- update time: 2022-03-08
-- app_name: 1739600

addappid(1739600)

addtoken(1739600,"6317881440600414258")

addappid(1739601,0,"23dbd11cfe3b3c6cc88cc5f48052a3935e1d9da9a582f32f5660b292177b1bce")
