-- generated by KeySteam
-- update time: 2026-03-23
-- app_name: 紅蜘蛛/Red Spider リマスター版 制作応援 ver.

addappid(3582340)

addappid(3582341,0,"2e2b4b8ff059ea269d012cfb16be7fa46b006526287137d282827416d1f9bc12")
addappid(3582342,0,"4b945c5332d4bba253fbcd426442c299f2d0a1fa5047bce97e3a5737893cbf0a")
