-- generated by KeySteam
-- update time: 2026-01-29
-- app_name: 《使命召唤®：现代战争® III 2023》

addappid(3595270,0,"defe8c09251c5dc5e626379a70a191334758cbc97509c5aafe0a3970a1bdd36c")

addappid(3603450,0,"729168405a0d1171f42a3d94541d9e17a0c4f42fbac19df315ec777e49c1b239")
addappid(3603460,0,"9d1af2a2772c7609f565db8dafd7b69bab4852bb988208cdb670e6a52729fd80")

addappid(3603450)
addappid(3603460)
addappid(3603470)