-- generated by KeySteam
-- update time: 2018-03-14
-- app_name: Red Comrades 3: Return of Alaska. Reloaded

addappid(546220)

addappid(546221,0,"b744d30c693041db167dd73f04fabc67e93fdef5dc8ab2bccc9c8ded271d9888")
