-- generated by KeySteam
-- update time: 2017-04-07
-- app_name: 554900

addappid(554900)

addtoken(554900,"18044158263994370651")

addappid(554901,0,"e7d969db130415d2a6b536b8d33832fd36c088ad40f14e654ff6de61cfe756d8")
