-- generated by KeySteam
-- update time: 2023-09-25
-- app_name: War Robots Shooting Simulator

addappid(2621400)

addappid(2621401,0,"72fcf7c00a8bbc1cc99e45adef7cda764e8e57aeac34529061dc3864d19cf68c")
