-- generated by KeySteam
-- update time: 2025-03-28
-- app_name: Touhou Meijinka ~ Song of Divine Tempest

addappid(2630380)

addappid(2630381,0,"519ee0341ff3bd486edb3d8cabfd5a1c1f354c551437971bd412a59af3e56847")
