-- generated by KeySteam
-- update time: 2025-01-09
-- app_name: 禁忌幻想

addappid(2638560,0,"fe82f3abc5e4fc5365f12736cd84fa57ee9383080d8abbcf848ed3a5456d43b7")

addappid(2638561,0,"f0fcb277caeac4df05b154149667a45ac064ebc4cf5ee5eb394f1bf36e40e77d")
addappid(3292860,0,"274f28ccaba743b804db693e544e7da180fd554f51d64dec4b8829e206ffc64b")

-- DLC: 1/1

addappid(3292860)