-- generated by KeySteam
-- update time: 2020-11-19
-- app_name: Covid Tale: Ignorance

addappid(1304390)

addappid(1304391,0,"f2b9ea56682534f529729546c677d557e160c0b8b10e1bca2370e4a98f8c2ac6")
addappid(1304393,0,"8b5a289b2a5597b239554d39b150195a3534f1ccc4dc7a3392c07252c084626f")
