-- generated by KeySteam
-- update time: 2020-04-24
-- app_name: Fantasy Mosaics 34: Zen Garden

addappid(1304300)

addappid(1304301,0,"1f802f83d99a13072953f0dc3b574dc1aa8c3fc41ce17fdf140bd3fb724b0274")
