-- generated by KeySteam
-- update time: 2020-04-26
-- app_name: The End of Labyronia: Nerubis

addappid(1304220)

addappid(1304221,0,"0630b8abc1f89f5789411206e68631e8a7b78d92d206a40ad350ecbe8518c247")
