-- generated by KeySteam
-- update time: 2020-10-30
-- app_name: 黑色花与红山羊 / Black Datura & Red Goat

addappid(1306750)

addappid(1306751,0,"2e9021ae1c27bb8103dab2083d00812ba99bf7a46308a967caf5913f9616ae01")
