-- generated by KeySteam
-- update time: 2020-05-05
-- app_name: Adventure mosaics. Small Islanders

addappid(1314270)

addappid(1314271,0,"ea2c608a3dd0a7ad83e9bb8aa751c70a1a7b438aebab576737114209080a2ab7")
addappid(1314274,0,"2fc18c0e7d561bbdd02956c58821e5b472123ae066ad4ad73c2fcb9356e8a730")
