-- generated by KeySteam
-- update time: 2020-05-11
-- app_name: Big City Rigs: Garbage Truck Driver

addappid(1315890)

addappid(1315891,0,"182341d7524979135195fc764ca5e1826cfbb66db9a222c3cba0166233c893f7")
