-- generated by KeySteam
-- update time: 2021-05-12
-- app_name: Otaku's Rage: Waifu Strikes Back

addappid(1316560)

addappid(1316561,0,"d38d5e226bb3b24ed6b221131543747b7a67d99ac8cb7e6f43c3312071ecc6cb")
addappid(1545980,0,"868c7c85a880684f3719f5836238ace0e060bd3a8b55529e4b9f4028377fa160")

-- DLC: 1/1

addappid(1545980)