-- generated by KeySteam
-- update time: 2020-07-31
-- app_name: Cupcake: an Apartment Adventure

addappid(1319880)

addappid(1319881,0,"0f23a41950426f5e273e917f7c275e89f551fa22b9f1632ab8be1e0a997392b8")
