-- generated by KeySteam
-- update time: 2025-06-23
-- app_name: 异形工厂2

addappid(2162800,0,"615a243c485abe945a4ff4a2a3e6a1663325ef15432b30f2f772d747cb1a0d2f")

addtoken(2162800,"18007773361721752868")

addappid(2162802,0,"163ae6ae731b47cb94170aee0ed8a4d4ecc62c6082bc319cc270e20c5eb0f759")

-- DLC: 1/1

addappid(3075620)