-- generated by KeySteam
-- update time: 2026-01-08
-- app_name: 魔灵召唤: 克罗尼柯战记

addappid(2167580)

addappid(2167581,0,"07bd2df5442b7d2faf3290d37c5faa84da8fdcad286d5eec8339b3a61d1226c6")

-- DLC: 4/4

addappid(2660190)
addappid(2660200)
addappid(2742120)
addappid(2886840)