-- generated by KeySteam
-- update time: 2022-10-04
-- app_name: Saturn Quest: R. U. N. E. 3000

addappid(2170760)

addappid(2170761,0,"c3c0bdeb7244eb0f54ed183b78c31de2c3074b011bbbb0c8214d0d2d7ca3bcc9")
