-- generated by KeySteam
-- update time: 2022-10-18
-- app_name: - Mischief Dungeon Life - 转生到异世界的我的胡闹地城生活 ClaraEdition

addappid(2177160)

addappid(2177161,0,"c91b525e4461fb24321d61edcf38d6c2449b0fffc76308e9c5a82a9f908b682f")
