-- generated by KeySteam
-- update time: 2022-06-06
-- app_name: Reventure

addappid(900270,0,"1df82fd5f8c785cf1a2c5a16caa609e0553be16ba6f3e2b21e86a714ac5e6224")

addappid(900271,0,"b3a07f5334cf36332eab9aa6d8147c4d509e7f5f15ccceb638a830a5d8597a23")
