-- generated by KeySteam
-- update time: 2018-08-14
-- app_name: 906340

addappid(906340)

addtoken(906340,"10716867824532717751")

addappid(906341,0,"cc03e3a3920c0bcb8c79a24fe0805e7e34b7991997e6fb6eeb3cf5267fd3481a")
