-- generated by KeySteam
-- update time: 2020-04-27
-- app_name: Mystic Vale

addappid(908070)

addappid(908071,0,"618ab1194178f93f4c24a60a52a53f5873e6a83400b2fa6a91d8dccc200f4c76")
addappid(908072,0,"cd87296a64c66616c28eae5a63a759bd6e5121d1e02f3ec8708e9ccc1b4cf424")

-- DLC: 4/4

addappid(1003220)
addappid(1015970)
addappid(1032290)
addappid(1097510)