-- generated by KeySteam
-- update time: 2026-03-23
-- app_name: Talisman: Digital 5th Edition

addappid(908060)

addappid(908063,0,"36a7fa47189041fa5c63860d80a86158ab15b553a67e198216c38cd09e2a0c9f")

-- DLC: 8/8

addappid(3387810)
addappid(3496590)
addappid(3640140)
addappid(3653350)
addappid(3653360)
addappid(3653370)
addappid(3970170)
addappid(4331630)