-- generated by KeySteam
-- update time: 2018-12-23
-- app_name: Cube Escape: Paradox

addappid(909080)

addappid(909081,0,"00224e202fcfed0867c920a785db94c65b076130d63da904985a107d52404546")

addappid(909150)