-- generated by KeySteam
-- update time: 2018-09-05
-- app_name: CRACKPOT DESPOT: TRUMP WARFARE

addappid(910290)

addappid(910291,0,"8c47ce0149266c53c3e5e12390767427e981add33650a50edcf012447d978dba")
