-- generated by KeySteam
-- update time: 2018-07-30
-- app_name: 913300

addappid(913300)

addtoken(913300,"1921083604761041867")

addappid(913301,0,"92a2ae3ffb99cfc10ff835565611e417288068d1bbcc3e750a5e0e000ad37d37")
