-- generated by KeySteam
-- update time: 2018-08-10
-- app_name: Slime Age: Parody MMORPG Clicker

addappid(913830)

addappid(913831,0,"1f74a6b902384998be6883dde926f9b34e0ff945fb620139d3a3b382adcf66a1")
