-- generated by KeySteam
-- update time: 2023-11-14
-- app_name: Coffee Talk

addappid(914800,0,"58a54e796ec4491e887446e3c87eceb9acaa5c7ff3b0aed8ef185dcad4a1b1e3")

addappid(914801,0,"f44c7c8d89df72bdd72122a3271719e26eb0f559c9ced165b22be5bb4d4f07c9")
addappid(1231690,0,"484366106eceb9ee1e09ff7e6294729cbfaa9f5acc58f9face07a8659b2bc4cc")

-- DLC: 1/1

addappid(1231690)