-- generated by KeySteam
-- update time: 2019-01-21
-- app_name: The Other Half

addappid(917920)

addappid(917921,0,"55241f70ed9c06087771b7563f145b192e49dde01dc1024209d1be66d6a3d9ae")

-- DLC: 0/1
-- missing DLC: 976650
