-- generated by KeySteam
-- update time: 2018-09-16
-- app_name: Help Me Escape! The Puzzle Maker's Office

addappid(918720)

addappid(918721,0,"a040bf7c0eee7de40d4d8a34f7a1897fbedb004792fd432a28b584dcfa865eef")
