-- generated by KeySteam
-- update time: 2026-01-14
-- app_name: Bloodface

addappid(3403870)

addappid(3403871,0,"f33171571e3562e356854fa1d108196cb8392691fcb5b9afc24de71c033c37c3")

addappid(4159660)
addappid(4162810)
addappid(4266150)