-- generated by KeySteam
-- update time: 2026-03-24
-- app_name: 无尽帝国 2 ENDLESS™ Legend 2

addappid(3407390)

addappid(3407391,0,"5c0d8a9608dff91b54b7ad2d588e18d229a20929f21793eb8378891a5c2ba08c")
addappid(3760760,0,"614897b8c50b33cc9e7562e23baa936bb897634e132a53a89fd2f0f815c0b60e")

addappid(3760760)