-- generated by KeySteam
-- update time: 2025-01-24
-- app_name: Millionaire Loong

addappid(3410950,0,"c3df4ff81eedaa744e81ce5dc963c480f6874051e801f17062ff2f54e4a26d6f")

addtoken(3410950,"3357774430551500628")

addappid(3410950,0,"c3df4ff81eedaa744e81ce5dc963c480f6874051e801f17062ff2f54e4a26d6f")
