-- generated by KeySteam
-- update time: 2025-11-27
-- app_name: A Pizza Delivery

addappid(3415450)

addappid(3415451,0,"ba68448bfff021217379231ecace69bc848bf6d060c3a81c03cb12a5658cab63")

addappid(4177150)