-- generated by KeySteam
-- update time: 2025-08-23
-- app_name: Overdrive Warfare

addappid(2748600)

addappid(2748601,0,"D0953BDF637F24B958B2B175D3656088830E6C7BCAB0FC90B63E87364D2E8302")

-- DLC: 1/1

addappid(2914770)