-- generated by KeySteam
-- update time: 2023-12-20
-- app_name: 吞食拜天地：三国刘蓓传（The legend of Liu Bei of the Three Kingdoms）

addappid(2751490)

addappid(2751491,0,"ad6aae81c910eb203775072a8cb9ab6d23237ade1990bdf3769e0762dcce19f9")
