-- generated by KeySteam
-- update time: 2024-05-23
-- app_name: 球跳塔

addappid(2751330)

addappid(2751331,0,"9311d12434a65f0fb1089412277bde4cefb56f9e38dc9ba441a43cde71fee310")
addappid(2828070,0,"14b9748f87964b5959dd2ce2442da85eb843e4bd246ed584a55c0d7926f6ef60")
addappid(2828080,0,"b60fcba88966bfc3ec84dd5a5d9a31a38e55530263d92733eae88262779fa09d")

-- DLC: 2/2

addappid(2828070)
addappid(2828080)