-- generated by KeySteam
-- update time: 2024-01-15
-- app_name: ぐうたら娘更生計画～Neet Girl Rehabilitation Plan～

addappid(2753810)

addappid(2753811,0,"bef98a0747cb03d48cbf16dcb3d8273ba9ef4d3e94ae61afc4d57a1f5035ec95")
