-- generated by KeySteam
-- update time: 2026-03-17
-- app_name: 鲁特里一家死了（The Roottrees are Dead）

addappid(2754380,0,"36f2a533bd44ae7ba2f5776fe764026bff6d177d28fff60cd38a3af11815dee3")

addappid(2754381,0,"a144e003752b9be3b56e1699fd3513b52775d8de366af34cd9464bf289edc3b0")
