-- generated by KeySteam
-- update time: 2024-10-14
-- app_name: Lonely Knight - Idle Roguelike RPG

addappid(2757630)

addappid(2757631,0,"1514a7f1e48c09d3988add6efcc5a3d0965115375bb230b36986fa603518bda2")

-- DLC: 16/16

addappid(2790040)
addappid(2796300)
addappid(2796310)
addappid(2796320)
addappid(2872050)
addappid(2872060)
addappid(2883810)
addappid(2883820)
addappid(2883830)
addappid(2883840)
addappid(2883850)
addappid(2883860)
addappid(2883870)
addappid(2883880)
addappid(2956240)
addappid(2956270)