-- generated by KeySteam
-- update time: 2022-06-07
-- app_name: 我的心很美丽吗？ - Am I kind-hearted? -

addappid(2050840)

addappid(2050841,0,"6d0c0454442651e7060c9b22e5fb39ca268ecd0065614e6dfc570fa0f54daf03")
