-- generated by KeySteam
-- update time: 2022-07-08
-- app_name: Kokoro's Gensokyo Journey: The Lost Masks

addappid(2057980)

addappid(2057981,0,"07d31dd9f39ae33af0363589814dc4439bbd583049e8ac36142a60106a463c44")
