-- generated by KeySteam
-- update time: 2025-10-04
-- app_name: 胡闹搬家2

addappid(1641700)

addappid(1641701,0,"87425c1557b863d4091a52a61a146d1634d5de17464e6e2107c05b2806ffd4ce")
addappid(2502500,0,"4f8bd8296b8af0d840f53c6d1f93d57613db76ade437a0105e5c4fabc4475410")

-- DLC: 2/2

addappid(2410580)
addappid(2502500)