-- generated by KeySteam
-- update time: 2022-07-01
-- app_name: 临渊觉醒

addappid(1641670)

addappid(1641671,0,"7d23d7b7fa7c560cdf18bbfa635fdb400f8fa2456a2c613003c78643fd3514ef")
addappid(1870081,0,"4b90fa6100a2a27ae237d83f6c9c78b3f3ba9e218efb1d1d6383f76ce4f71e5a")
addappid(1880261,0,"8b9c3ca33b8b73208f6d00b6923ac2ab21ea55f99ea3a79acb9d60045a55ded8")
addappid(1927011,0,"44501a0bad186c90fe69daa210ad8dc4ff3b737fa61f15695c3cbab7ffd6347e")

-- DLC: 3/3

addappid(1870080)
addappid(1880260)
addappid(1927010)