-- generated by KeySteam
-- update time: 2021-05-24
-- app_name: 1644630

addappid(1644630)

addtoken(1644630,"2688109312957829379")

addappid(1644631,0,"1348346a603c8cb3035e552c94bed7161aee8a04cde94540d033c598b61e13ec")
