-- generated by KeySteam
-- update time: 2021-07-20
-- app_name: Church of the Midnight Sailor

addappid(1645990)

addappid(1645991,0,"3b1d36881ec333f9fdda0dcada897811038706e1563aa2ba4db7f6bb0e88a8f0")
addappid(1645992,0,"2fbbeea497453ebf55581e7c723324b4e6b91a7595530271ae479601c0528e4c")
