-- generated by KeySteam
-- update time: 2023-04-25
-- app_name: Returnal™

addappid(1649240,0,"dbd6d9acfed0fc39a2f95c2fea977ef53fc3714544156834c6d4fba1794f6c38")

addappid(1649241,0,"56c7a929e028152a464e8015e2e697cbcbf5313232cc82ccc1c312e6d5d76929")

-- DLC: 1/1

addappid(2127200)