-- generated by KeySteam
-- update time: 2023-01-11
-- app_name: 冒险者莉兹和情色迷宫

addappid(1652220)

addappid(1652221,0,"f30885c22f648ef8af161d5a7520c5b750d327c3bdbc973d3da7fc26dcde702a")
addappid(2260810,0,"b06f0d451c9b6b7810cc1a40204bacf7f887bdd3943731c46cda74bb8c00b9f4")

addappid(2260810)