-- generated by KeySteam
-- update time: 2026-03-05
-- app_name: Jigsaw Puzzle Dreams

addappid(1653970,0,"d39b5bc86fd0800f569c6af53cdd07a578ea096f730ad2c5a4240eb288cbd78d")

addappid(1653971,0,"9b8650952b2b934a8243f4e6e7696f6699a925d391b34dde30b5b921d625335f")

addappid(1832730)
addappid(1832731)
addappid(1832732)
addappid(1832733)
addappid(1832734)
addappid(2763190)