-- generated by KeySteam
-- update time: 2022-03-11
-- app_name: 闪红的艾丽丝

addappid(1658930)

addappid(1658931,0,"9e6463643ff527efca390c2853c4985d4c3aaab05aece1e21fd0e13007a38ef8")
addappid(1658932,0,"36ea4f2a91165126a8c1b40e76b44cbe6ee83d077195071e718d662d289ed13a")
addappid(1658933,0,"84f793fd4abad624eeba98b6688638a9b588e6fde666a028d16c5a69d4042c5f")
