-- generated by KeySteam
-- update time: 2026-04-13
-- app_name: 编程农场

addappid(2060160)

addappid(2060162,0,"18be2e81f67839803b107115cde05b35e14fc9b9bb4b71bb9f21a79503cda2b6")

-- DLC: 1/1

addappid(4521700)