-- generated by KeySteam
-- update time: 2023-01-12
-- app_name: Silver Nornir

addappid(2065570)

addappid(2065571,0,"5BC56CAB8E2FE2E712B4B468FE8E2A21F411C2831D7128BD15525AEECB74CD83")

-- DLC: 5/5

addappid(2081440)
addappid(2081441)
addappid(2081442)
addappid(2081443)
addappid(2081444)