-- generated by KeySteam
-- update time: 2017-12-19
-- app_name: Deponia Doomsday

addappid(421050)

addappid(421051,0,"b550b3076c1e35339a45742ff70d41bd9e7d6141a6abb893dcd83031712cec63")
addappid(421052,0,"d19e6041aebf0f6a102015321efa02acb9514a62aaa7a9c558bdd217bd772d27")
addappid(421057,0,"16c43121a02873c1da01a6cc7f9f30c3519b9a13648a76998c4e0be596a371bd")
