-- generated by KeySteam
-- update time: 2017-05-09
-- app_name: ZHEROS

addappid(423270)

addappid(423271,0,"8d137f52161c9886557e0e9c8a8d0dcdcadf2b888d7e73f89d5c8a87f88db857")
addappid(444540,0,"a2a8a3d783af6b86a292d92be7d6a2400ce651318fd6058fe1db27de7da38530")

addappid(444540)
addappid(628280)