-- generated by KeySteam
-- update time: 2016-12-12
-- app_name: Astervoid 2000

addappid(423870)

addappid(423871,0,"aa24962644b316359ec6cd876f347a32c09356b3e5806a5cc4c2941608388c4b")
addappid(563590,0,"f79fbd3f0f1920ef7b80ddd5ece5f41984e069b7e8a983929bd2c370510e9b0e")

addappid(563590)