-- generated by KeySteam
-- update time: 2016-12-02
-- app_name: WinKings

addappid(428920)

addappid(428921,0,"29b1d837cf8e52a5df8869d07521e0a5eb0371565af904bf7ea40ef83a2b2366")
addappid(428922,0,"1ec3747b1fe66c15103008d05e7797baef1b2348d514ee6a32e4b47565ea4c71")
