-- generated by KeySteam
-- update time: 2025-10-03
-- app_name: 友尽高尔夫

addappid(431240,0,"15623194ea6b4889952c9c6a65015dab9d45fc56d4b0bed9786034dfdbca2e24")

addappid(431241,0,"16cd47114e4065cbc0a73cdeb4ea975256bf4ab9ac9e6306e112f94c5522f12d")
addappid(564170,0,"fc920161bc70827e127a30a447ae4d0d47e9ace5c4190050fc3ba76950d107a8")

-- DLC: 18/18

addappid(564170)
addappid(1277570)
addappid(1901920)
addappid(1901921)
addappid(1901922)
addappid(2073740)
addappid(2130860)
addappid(2246730)
addappid(2366470)
addappid(2456990)
addappid(2456991)
addappid(2591390)
addappid(2710860)
addappid(2710870)
addappid(2863570)
addappid(3041140)
addappid(3041150)
addappid(3265830)