-- generated by KeySteam
-- update time: 2018-05-26
-- app_name: Mystic Destinies: Serendipity of Aeons

addappid(431510)

addappid(431511,0,"866fa17909b023eff78ce378c52695f36d01460fa80fd0f729f6456401bd9e02")

-- DLC: 0/11
-- missing DLC: 440130, 455530, 466710, 483790, 484840, 508160, 508161, 508162, 508163, 508165, 649160
