-- generated by KeySteam
-- update time: 
-- app_name: Hubert's Island Adventure: Mouse o' War

addappid(431610)

addappid(431611,0,"73e568f8988d697806480df738d57643673620ac8c89b5e89cd499c2fe892e2d")
addappid(431612,0,"4035d71b8ea5cedafd93640a144b48a06f5937ab8873adde031453333ce19f51")
