-- generated by KeySteam
-- update time: 2017-04-20
-- app_name: A Legend of Luca

addappid(433600)

addappid(433601,0,"930500de6149307cd295f9ff0ac121df5878d329f996ab27a329ec9e3a699eda")

addappid(457100)