-- generated by KeySteam
-- update time: 2024-10-14
-- app_name: The Jackbox Party Pack 3

addappid(434170)

addappid(434174,0,"132527bd962b8c4f6acd145352cd7ea300cce21bd63cfcc886d27f3377fa6b91")
addappid(434175,0,"671c941331e7d0399a82ec24a445329d45e41936635502b531ad22be5c9ffd0d")
addappid(2828508,0,"86a8e078c58ea7fbf57bdf1b2611116fe069f5e590cfa11058ca6610e0961700")
