-- generated by KeySteam
-- update time: 2023-07-26
-- app_name: Masked Shooters 2

addappid(434250)

addappid(434251,0,"56a81d95bbde0edab27f1cb833876eb72fd833886da3521b13fe8b3086509abf")
addappid(909050,0,"4bd1e39001ff31a35b2ce9276c0b8293675afa558d788821cb88d19247e194a1")

-- DLC: 1/1

addappid(909050)