-- generated by KeySteam
-- update time: 2018-09-06
-- app_name: Medusa's Labyrinth

addappid(436110)

addappid(436111,0,"ef98010defc935cf39aa927f69978ba9f473409f144898331606909bd2a0ff79")

-- DLC: 0/1
-- missing DLC: 443400
