-- generated by KeySteam
-- update time: 2025-10-18
-- app_name: 性感可爱的淫妻们：紫色

addappid(3783090)

addtoken(3783090,"10093652871749631995")

addappid(3783091,0,"f730b31efb60144645ef62f7f6ee12801a995033efdd3a0944a123e13eb63684")
