-- generated by KeySteam
-- update time: 2026-03-31
-- app_name: 英雄立志传：三国志

addappid(3020510,0,"532f81ac5c609577203b243849af2a39d38c00f6a29344ee31dea0fcc812beb0")

addappid(3020511,0,"139eea24aed3d56dc572b215fc4ea1845c3238d246a98ccef727f3eec863f528")
