-- generated by KeySteam
-- update time: 2024-07-05
-- app_name: Criminal Archives: Blade of Deceit Collector's Edition

addappid(3036760)

addappid(3036761,0,"c2cbecf8d578fa4767f77153ecbf5135c77ca90d295d614c3b78cb67f7705db4")

-- DLC: 0/1
-- missing DLC: 3036920
