-- generated by KeySteam
-- update time: 2025-02-13
-- app_name: Turtle Champs

addappid(3036380)

addappid(3036381,0,"19C9D9D00855A3726D3F37AB2D5562D38ED32A6A729615487AC68A904383C3CB")

-- DLC: 1/1

addappid(3040660)