-- generated by KeySteam
-- update time: 2017-12-10
-- app_name: 760450

addappid(760450)

addtoken(760450,"12814860907172491252")

addappid(760451,0,"b3d657f7acf35e8dcffffbda80366899667266e446e41a8cff128312a780f98a")
