-- generated by KeySteam
-- update time: 2018-06-04
-- app_name: Thunder Chase

addappid(762270)

addappid(762272,0,"c34013bae5c6c7cae0860d4d3d96054842d80514400fd0687a969d2a4a6d5a05")
addappid(762273,0,"a1a7b0f739261762dbc97c58ca10fbcc2edc4e0c3bb9497219cbb485cac00358")
