-- generated by KeySteam
-- update time: 2018-03-05
-- app_name: 762460

addappid(762460)

addtoken(762460,"17597975187693958736")

addappid(762461,0,"7e8f0245d29b15029a97e46d55ffb3fdad06249a10c6de3a0688c3e99541e30c")
