-- generated by KeySteam
-- update time: 2017-12-13
-- app_name: 764060

addappid(764060)

addtoken(764060,"5480559945583710230")

addappid(764061,0,"b4c46af0abf27f5a13164652f64230556d30e3b12ff5499b19df6df5d17eb2d0")
addappid(764062,0,"f31fd62064c1b89badb5355a6f2f0250385d7fbb830c5a942fe78dc022dedeae")
