-- generated by KeySteam
-- update time: 2019-01-28
-- app_name: Fairy of the treasures

addappid(770400)

addappid(770401,0,"78980056981f05a60956d6716402f8d6941b3762dc4b8bb564eef13db67bf84c")
addappid(816050,0,"0e1ea4539b985f9ce22fd5eda10dacba5fc039e78b3ec698a6df564cce834acf")
addappid(973490,0,"251014b3b8c20d5692b89b6833708de16c07043c7388fde7427565e1a4c4d95d")
addappid(997740,0,"f0b1b757d2704b6b82557c4bedfaa3fb0fbb9de17ff18f82667c30fe028d0d10")

addappid(792360)
addappid(816050)
addappid(973490)
addappid(997740)