-- generated by KeySteam
-- update time: 2018-01-16
-- app_name: 775890

addappid(775890)

addtoken(775890,"3167141769221662638")

addappid(775891,0,"7b819fbac8a0cca3374862d423fad5292f2f607a84265101e4804151becf7cfc")
