-- generated by KeySteam
-- update time: 2018-01-04
-- app_name: 778450

addappid(778450)

addtoken(778450,"3670926293280221094")

addappid(778451,0,"cec1734fe21d12d8c0604b5dc6d4d1b1358b461e3bea12e1b35ed07e8da3438f")
