-- generated by KeySteam
-- update time: 2018-01-10
-- app_name: The Rising of the Rose Ocelot

addappid(779550)

addappid(779551,0,"dad6e03ed509b2cfd16fd37390fbb6a9a84bcdab5b4ae68a310c5e38d432168c")
