-- generated by KeySteam
-- update time: 2023-07-31
-- app_name: 斩毒：罪与罚（Narcotics Police:Crime And Punish)

addappid(2442970)

addappid(2442971,0,"451446021f5dd8ce4581700e7dfc2ec1074f90f41ddf3522c55447581fdba3a9")
