-- generated by KeySteam
-- update time: 2026-04-06
-- app_name: 爱与生活：幸运老师

addappid(2445340)

addappid(2445341,0,"abd0d78162f8690db2b855ea021f3a15eef0d8150644b9a529e5fb3aaa21d326")
addappid(2662040,0,"05bccd13c2e9ac418a3d2959dfba61c733103631f4feac706c3b1ece5bdebe5d")
addappid(3216840,0,"a21b3b1006ac0dd168b788865ae03cfc0b9cca83e1a78d5f539306d8beea10db")

-- DLC: 2/2

addappid(2662040)
addappid(3216840)