-- generated by KeySteam
-- update time: 2023-07-03
-- app_name: Strip President of Tendoryu / Kinetic Strip Party

addappid(2450660)

addappid(2450661,0,"4d48633ae1724d1f16aee2fb4e7e018aa8e3139e24cf5f6c86d320e1b7527cfc")
