-- generated by KeySteam
-- update time: 2025-08-18
-- app_name: 球球大塔防

addappid(2453610)

addappid(2453611,0,"1d9ef26f27e93e0c8d38abf685a9c354625f81fc6bcae79d9383b35b2346c7cb")

-- DLC: 1/1

addappid(3334720)