-- generated by KeySteam
-- update time: 2025-10-24
-- app_name: Light Bearers 2

addappid(2459530)

addappid(2459531,0,"1A16884C602BF5C7FFA502F4E7F312A7B82CA2663C0A264B94D07058411458F5")

-- DLC: 1/1

addappid(3491020)