-- generated by KeySteam
-- update time: 2024-05-24
-- app_name: Short Sad Stories

addappid(1983880)

addappid(1983882,0,"e08637c402f4109053c758a7ba684607d00bd1ee95150433808413cd6b5b24c7")
addappid(2983640,0,"c3dc8a3f66b3a69cdd102511d6875defb8b054d8f47e27a69061d3208940b6fe")

-- DLC: 1/1

addappid(2983640)