-- generated by KeySteam
-- update time: 2022-05-07
-- app_name: 公会前台接待员 菲利斯

addappid(1989840)

addappid(1989841,0,"aa6ab526a5885714926c95a98c202d71d2ea39780410634b8be712b4e5d419c0")
addappid(2323460,0,"4e1740a64fab86a73f5b8a83985b6379024a91b9114d5451b6dab0ba2da43324")

addappid(2323460)