-- generated by KeySteam
-- update time: 2022-07-19
-- app_name: 2D Brick Breaker Game | REMASTERED

addappid(1994630)

addappid(1994631,0,"ef95fca219b8d01144cc1ded727a233f7fe1e3ac8ce165a301691ff79d57babc")
