-- generated by KeySteam
-- update time: 2020-11-29
-- app_name: ∀kashicverse-Malicious Wake-

addappid(1225610)

addappid(1225611,0,"7bf8e4a6fcbb9ff254db0cddf61bbc74580d2b5eab01ff820a1573ad2e8958cb")
