-- generated by KeySteam
-- update time: 2026-01-06
-- app_name: Zip! Speedster of Valiant City

addappid(1227760)

addappid(1227761,0,"5ba0ffbbef4e519cb5a93aae32c0f2646e9dd96cdd867fccebdcb90de5350b4f")
