-- generated by KeySteam
-- update time: 2024-10-15
-- app_name: 尘封大陆

addappid(1230530,0,"765589e898db8d78eaa1193794c5334ed1ebca3fd93c0bace3596ea7dd3ddb0a")

addappid(1230531,0,"25f3af482734dc6c7e43a9a45c3c959c4c9988a764396d7dace988ef9622b312")
addappid(1230532,0,"063151f238f826db2cc0391307ffd1970c31dcba8bdea7d34043f17023d27725")

-- DLC: 2/2

addappid(1933030)
addappid(2863890)