-- generated by KeySteam
-- update time: 2020-01-21
-- app_name: Classic Card Game Poker Pack

addappid(1231820)

addappid(1231821,0,"8f5080ef4a5f86f6944dfed24bab6ff9389f0e4d22f09fd0925d4a556285625c")
