-- generated by KeySteam
-- update time: 2021-10-18
-- app_name: Evil Cult

addappid(1237260)

addappid(1237261,0,"b7eeecafa726efb92cf625d02684ad51920417731a8c10d6e0eaa95b495695af")
addappid(1237263,0,"abda7c2bdef43b5d59eca5213f4432d722ac6e141d169f5afd917fdb8e124e33")
