-- generated by KeySteam
-- update time: 2025-05-11
-- app_name: Frostbite Frenzy

addappid(3605490)

addappid(3605491,0,"5B20858CEC209FFDAC61215A7A07CF8F9A777391B264D431B9C447EE98FD182F")

-- DLC: 28/28

addappid(3605590)
addappid(3605600)
addappid(3605610)
addappid(3605620)
addappid(3605630)
addappid(3605640)
addappid(3605650)
addappid(3605660)
addappid(3605670)
addappid(3605680)
addappid(3605720)
addappid(3605730)
addappid(3605740)
addappid(3605750)
addappid(3605760)
addappid(3605770)
addappid(3605780)
addappid(3605790)
addappid(3605800)
addappid(3605810)
addappid(3605820)
addappid(3605830)
addappid(3605840)
addappid(3605850)
addappid(3605860)
addappid(3605870)
addappid(3605880)
addappid(3605890)