-- generated by KeySteam
-- update time: 2021-12-06
-- app_name: Altwaldheim: Town in Turmoil

addappid(1363140)

addappid(1363141,0,"e8309b4d7422300fa40fc7c02a57dfc4f12a9545b65273063fdc456f472f0db1")
