-- generated by KeySteam
-- update time: 2025-12-16
-- app_name: City Bus Manager

addappid(1364210,0,"a2f63ad9fdb4aad94b825ce27fa4b82ea6327ee0eb2fb35cd62da5406b738ae3")

addappid(1364211,0,"3748007409a9ce4382259fe6320aff7ea846f18eba5a9c4a9ec7bab1a6864761")

-- DLC: 14/14

addappid(1899720)
addappid(1901800)
addappid(1901840)
addappid(1901850)
addappid(1903250)
addappid(1903920)
addappid(1903930)
addappid(1904020)
addappid(1904840)
addappid(1904870)
addappid(2700180)
addappid(3218520)
addappid(3358770)
addappid(4196890)