-- generated by KeySteam
-- update time: 2020-08-05
-- app_name: Zodiac Girls

addappid(1370620)

addappid(1370621,0,"c79542921325dfecba698dea564baf1c72d99833cae6d19998bf0aba733b0029")
addappid(1377910,0,"3d058f6398a38fc7268fe291fed234439e93f759342ed7372dbd30194b659f77")

-- DLC: 1/1

addappid(1377910)