-- generated by KeySteam
-- update time: 2020-08-06
-- app_name: Sport Girls

addappid(1370630)

addappid(1370631,0,"243f3666afa81d7c935abaac5c20bf01d7c869478e87ec5ab0ba69827210d167")
addappid(1378610,0,"bf8dd34ec617a0db9a29386244f386c5f741c3787c672d09b5654d08245463f1")

addappid(1378610)