-- generated by KeySteam
-- update time: 2024-08-13
-- app_name: Teamfight Manager

addappid(1372810)

addappid(1372811,0,"df6596100d8c79e5b47567902f61ab4351ac02aefa8fdccc6382ce0b44684423")

-- DLC: 3/3

addappid(1565920)
addappid(1565921)
addappid(1565922)