-- generated by KeySteam
-- update time: 2026-01-20
-- app_name: 养鱼模拟器

addappid(1372150)

addappid(1372151,0,"efb8b3757e6c420a126256c4a626da290ffc10e1e96099b695be927020130fb6")

addappid(3213040)
addappid(3459300)
addappid(3537170)
addappid(3537180)
addappid(3794510)
addappid(3925080)