-- generated by KeySteam
-- update time: 2024-10-21
-- app_name: 印蒂卡

addappid(1373960)

addappid(1373961,0,"fa22d6df0c690d7d4a42377918c6b733be2f835f4372e79c8a021fee6df68849")
addappid(1373962,0,"49d9fff6a7534e18846a8583110a2c9cc33c2fc63091fb91673af0bfcecfbc57")
addappid(2789960,0,"7349caf1f5147ec22fdb7f3051c9edc2e16ccef2ac6c31946a64686b46ea7410")

addappid(2789960)