-- generated by KeySteam
-- update time: 2026-04-16
-- app_name: 废墟国度：符文之门

addappid(1375750)

addappid(1375752,0,"af95fcca9c379f1d71fd424952bb1692e14f1214d52a3c25e85d4a4b60b7b61a")

-- DLC: 1/1

addappid(4446470)