-- generated by KeySteam
-- update time: 2024-01-19
-- app_name: The Scam

addappid(1375780)

addappid(1375781,0,"8dc7f12e91019ff92540079972e26941d18dff2c75f99a04819535ead62e30af")

addappid(1916130)
addappid(1917340)
addappid(1917341)