-- generated by KeySteam
-- update time: 2025-04-28
-- app_name: Professor Rubik’s Brain Fitness

addappid(1377890)

addappid(1377891,0,"2082f6a53aa6762efcc45e90eb1b197095012baf1ed321a22c9711949cf23c26")
