-- generated by KeySteam
-- update time: 2025-06-01
-- app_name: Nemithia - Tale of the Legendary Saviors

addappid(1621210)

addappid(1621211,0,"e6b21c222e5ce9af05eee87eadc79762568f90213ed67464096a13d7cd3fa6b4")
