-- generated by KeySteam
-- update time: 2026-02-24
-- app_name: Black One Blood Brothers

addappid(1621560,0,"260c2a76e98dab65de625846b00395dec5601324a426235accb781cb081c8b1e")

addappid(1621561,0,"28de5a653d01514649d6e16ec7b28d6ee5ac2897abc4609b507964835bfab62d")
