-- generated by KeySteam
-- update time: 2021-06-30
-- app_name: 1001 Jigsaw Legends of Mystery 2

addappid(1624880)

addappid(1624881,0,"341ec12f3bd5615cac026c1b199ca0984b07f5f872f889a24c08a7cd5dbcca42")
addappid(1624884,0,"08e976fd19134a9db915739a2ce390ac1f51e12b247c55c6d11775b098ec8444")
