-- generated by KeySteam
-- update time: 2022-03-17
-- app_name: Gnomes Solitaire

addappid(1624970)

addappid(1624971,0,"7150ce8f0671aec6ffb78f6b516d78c6ac0a26ea092d7faa32ac707a805d22e8")
addappid(1624974,0,"2566d1bbdde7bc6ffce4bb15ee677787c8984cd63739e487fac30f9e14ddbba0")
