-- generated by KeySteam
-- update time: 2021-05-01
-- app_name: 1625070

addappid(1625070)

addtoken(1625070,"13529325040781847164")

addappid(1625071,0,"c11128764dc30ec97e76d7c3414f27f63fbee712cf43aa445a61b07133a791b9")
