-- generated by KeySteam
-- update time: 2025-10-04
-- app_name: Bub Block

addappid(1625610)

addappid(1625611,0,"54a427ee72dd843df906d24beb5f5bb1c48d88d956b61219f39b7dfe7e2bd29e")

-- DLC: 1/1

addappid(3382510)