-- generated by KeySteam
-- update time: 2023-02-22
-- app_name: The Hero Journey in Yggdrasil

addappid(1630440)

addappid(1630441,0,"81827495e38e4d5faa779ad222be3318040bafb45a10b5aab2d343700311eece")
