-- generated by KeySteam
-- update time: 2021-05-27
-- app_name: The Shape On The Ground (Steam Edition)

addappid(1633830)

addappid(1633831,0,"6e333dc63745db845ca96ac4f075b61a3f812c3675c1152efb29e3afccd53e7c")
