-- generated by KeySteam
-- update time: 2022-10-12
-- app_name: 兽耳少女才不会背叛呢

addappid(1413970)

addappid(1413971,0,"c26ddad2f9073684a5b0e7e44a99e49f11dd4562451a98a80df4f756a0359b81")
addappid(1413972,0,"43c0d633fff76254892032fa3ef630eaf95fba5059fef30c0c1165d686877bde")
addappid(1413973,0,"7fbff9e053a91028c2ba0f6390071193dbd142cca9d29c8d3eefa7084403c181")
