-- generated by KeySteam
-- update time: 2025-07-15
-- app_name: Everafter Falls

addappid(1416960)

addappid(1416961,0,"2257e99decaf0453ec32df3a6762cc771e6ad768998a6dab444a236f02315163")
addappid(3024910,0,"05aa9c5a57a13895ecc6ecdabb1854879c7a1c9de9089ed3247f37683c38e9be")

-- DLC: 1/1

addappid(3024910)