-- generated by KeySteam
-- update time: 2023-03-12
-- app_name: Apocalyptic Vibes

addappid(1840610)

addappid(1840611,0,"33101ad41def159019c7fe11f3ef701889ca17731ab751b3eb03801c6ed68e2f")
addappid(1840612,0,"0d89b87a696618ec71169d8f138865263bad5e0184af04a4520459384b18db36")
