-- generated by KeySteam
-- update time: 2022-06-14
-- app_name: Brigandine The Legend of Runersia

addappid(1843940)

addappid(1843941,0,"81263a8e970eb65704838f4ab3a37a4bd64796f185e5efeebdc968c9774402dc")
