-- generated by KeySteam
-- update time: 2022-02-28
-- app_name: Jigsaw Puzzle Beach Season

addappid(1859060)

addappid(1859061,0,"68fcf2c2cdc6b3ad8af2914cc89b6eed8f8ebf9f4785d7dd30436f0dec8c1319")
addappid(1859064,0,"f2b259b25a26a235907ab9c37cec58c740fd4c430fa2590bbc275d783f5292b7")
