-- generated by KeySteam
-- update time: 2022-03-10
-- app_name: Pirate's Solitaire

addappid(1859140)

addappid(1859141,0,"33f715db3e7026a7c92651afb729a57058d964e82f1e891dc408c31dab2b6fd1")
addappid(1859144,0,"18f8d58177eb1a0c934e425afac39b446a732804b6c2876ecdca7b775b0dca30")
