-- generated by KeySteam
-- update time: 2022-02-28
-- app_name: Royal Jigsaw

addappid(1859100)

addappid(1859101,0,"14a3c463baf1964476d9bd8085237fa6426cf537d4ea933c2c398025176641b3")
addappid(1859104,0,"aac7aa387999621f6603dce576c61cc3a7ebe04474aa901a7a5a3de082ccc129")
