-- generated by KeySteam
-- update time: 2018-07-04
-- app_name: Mahjong Pretty Manga Girls

addappid(885190)

addappid(885191,0,"2e2016e9b99dfc71171949a5798a5019ccd39f2fa2bf4df72c195c6a374bb934")
addappid(885192,0,"a2745581b3bc1878f0cffde87f3a06e84ee38729d0a222c13641c8a9a53af867")
