-- generated by KeySteam
-- update time: 2019-12-09
-- app_name: Nelke & the Legendary Alchemists ~Ateliers of the New World~

addappid(886820)

addappid(886821,0,"b9c8320a7f7362895e67bb2cb7f0be55f88eca43961d84596a0ce2a2bebdd024")
addappid(1055072,0,"25272ea41175a2d2f1d473b945ef79906f2d23b810260c128e3bc6841fc9547d")

-- DLC: 16/18
-- missing DLC: 1013990, 1014000

addappid(1015850)
addappid(1016550)
addappid(1016560)
addappid(1047070)
addappid(1055060)
addappid(1055061)
addappid(1055062)
addappid(1055063)
addappid(1055064)
addappid(1055065)
addappid(1055066)
addappid(1055067)
addappid(1055070)
addappid(1055071)
addappid(1055072)
addappid(1055073)