-- generated by KeySteam
-- update time: 2026-01-27
-- app_name: Glassbreakers: Champions of Moss

addappid(887330)

addappid(887331,0,"C8A4F9EADE1083BA25D19E6C8320B8915056CC1092D93D7B00A922394EE59B6F")

addappid(4063610)
addappid(4095910)
addappid(4114710)
addappid(4114730)
addappid(4114760)
addappid(4114780)
addappid(4114800)
addappid(4114830)
addappid(4117000)
addappid(4117470)
addappid(4117480)
addappid(4117490)
addappid(4150000)
addappid(4150010)
addappid(4150020)
addappid(4163550)
addappid(4163560)