-- generated by KeySteam
-- update time: 2023-01-16
-- app_name: ATONE: Heart of the Elder Tree

addappid(894620)

addappid(894621,0,"3e93b0c93c855f931dd181fb75d3c66d5b50f79da7d881de0cf6cc4e7787c9ad")
