-- generated by KeySteam
-- update time: 2025-11-14
-- app_name: Spellcaster University

addappid(895620)

addappid(895621,0,"d43ff0db940ddcaaaf10a88d20286ea7f48a0eee9e62ba33b350860ccffc8e26")
addappid(3394370,0,"80aa14b15eaf1eaffce54fbaf112d0d0dd39f41bab9e166c56516cb8b0670f1d")

-- DLC: 2/2

addappid(3350300)
addappid(3394370)