-- generated by KeySteam
-- update time: 2021-06-23
-- app_name: 《古斯塔奥：帝国重生》Gustavo Kingdom Rebirth

addappid(895980)

addappid(895981,0,"4b37df43fb4e8f6412b8401d37bc2fd17894e7326ef480039b34fc6f1638f350")
