-- generated by KeySteam
-- update time: 2026-01-12
-- app_name: Boeckham's Football Manager

addappid(3523140)

addappid(3523141,0,"8B59CD4A8D69AE8611DEF83B780124751FCF95043CCA951EE9D1D24798403734")
