-- generated by KeySteam
-- update time: 2026-01-14
-- app_name: Pioneers of the Coast

addappid(3531790)

addappid(3531791,0,"2E84EDD37A32E3139C9F8A4FC71CF81B7E2E7D72492AA2F0316CEBC61525A4EA")

-- DLC: 1/1

addappid(3578330)