-- generated by KeySteam
-- update time: 2025-10-23
-- app_name: Warhammer 40,000: Boltgun - Words of Vengeance

addappid(3533730)

addappid(3533731,0,"1180e2ce90b77b8faffadeac719cb2d71c9e0fb99c90a3c0b672cc1c3cfa129c")
