-- generated by KeySteam
-- update time: 2026-02-21
-- app_name: 银河模拟器2：星门

addappid(3538820)

addappid(3538821,0,"8d7b7aec10b106b3f6c26881c29ee2297db00ee0e2dcd0df7c519c5b1a8a4ae6")

-- DLC: 2/2

addappid(3680030)
addappid(4450140)