-- generated by KeySteam
-- update time: 2025-06-13
-- app_name: I Got Hired To Guard The Button That Destroys The Earth

addappid(3539870)

addappid(3539871,0,"41EA78BAC64E469CC696948185407308954ADADFD0C0D9FC69892146146C9FD2")
