-- generated by KeySteam
-- update time: 2025-12-22
-- app_name: Starlight Re:Volver

addappid(3201010)

addappid(3201011,0,"d1d08539c276061ca3555b2aab801c92cf7791cc7dd48861a8d92a1a5217b0cb")
addappid(3201012,0,"751e4bb432fc4bc3ad95b25303eaaeab8c958a2a7f5743d83cd1122a17fb45ce")
