-- generated by KeySteam
-- update time: 2023-09-27
-- app_name: Crimson Tactics: The Rise of The White Banner

addappid(1480810)

addappid(1480811,0,"974035922672bd925e24cffc31d21707f1640d99065c94afb119d6e3e14258f0")

-- DLC: 0/1
-- missing DLC: 1886180
