-- generated by KeySteam
-- update time: 2021-05-03
-- app_name: Survival RPG: The lost treasure

addappid(1480050)

addappid(1480051,0,"05fb8b65c4617d8006a4db5950783a4be4908a7687ac8f988df4e2e55af25667")
