-- generated by KeySteam
-- update time: 2025-08-23
-- app_name: BOT.vinnik Chess: Opening Traps

addappid(1493840)

addappid(1493841,0,"d044136d78395d80ef5c981e3dc8a23c4aed9f430bfe73c5d7780bbeda5ef32d")
