-- generated by KeySteam
-- update time: 2021-01-19
-- app_name: Detective Solitaire: Inspector Magic And The Forbidden Magic

addappid(1495100)

addappid(1495101,0,"deccb41f7f2b3932a6564aebf65b58151cf5f560a0f07f00fbf9896bec39dd5f")
addappid(1495104,0,"8abdd1b2d7e0817730e40dda35563e89476ec249d331c2c9f91c1331d03b0602")
