-- generated by KeySteam
-- update time: 2022-03-17
-- app_name: 1560960

addappid(1560960)

addtoken(1560960,"11731838967354308956")

addappid(1560961,0,"0a94af2df11be6481d5e145e1277ab3a88f4938dc3524614d84cf3924a76492a")
