-- generated by KeySteam
-- update time: 2025-07-28
-- app_name: Galaxy Drift

addappid(1563520)

addappid(1563521,0,"1d0982e6e41fc5a1342ca79948b290b34840747c6fb144b308cb7d93aa536527")
addappid(1563523,0,"483e1d364472a94a32c8c4f08a147621a6496c8fb4ca4b90ff502d81c6803676")
