-- generated by KeySteam
-- update time: 2022-04-24
-- app_name: 1567030

addappid(1567030)

addtoken(1567030,"16379415347840617222")

addappid(1567031,0,"c56e3ad183d6ee9e9008562baad562670c9f7852219ccaf0ca2a3a8728585565")
