-- generated by KeySteam
-- update time: 2021-03-10
-- app_name: USA Truck Simulator

addappid(1568180)

addtoken(1568180,"15489923063861312718")

addappid(1568181,0,"48a1a62c6c35c37c688fb6c31f88a4fc3598c332c97463db0359f71265e08adb")
