-- generated by KeySteam
-- update time: 2022-06-20
-- app_name: OnlyFuck - RuRu's Adventures

addappid(1569590)

addappid(1569591,0,"8adcaa1363a964a85d1846a2ca15c7ce9a469aff61de0cab529374981243db2e")

-- DLC: 1/1

addappid(1665100)