-- generated by KeySteam
-- update time: 2026-02-22
-- app_name: Shades Of Rayna

addappid(1569820)

addappid(1569821,0,"44e9977c512cd957fd4451b094c2fc877f56636793140ca9e9003ad35445c129")

-- DLC: 15/15

addappid(1625560)
addappid(1625590)
addappid(1638900)
addappid(1677760)
addappid(1721040)
addappid(1797620)
addappid(1798370)
addappid(1848760)
addappid(1942220)
addappid(2075520)
addappid(2368290)
addappid(2523680)
addappid(2714570)
addappid(3567500)
addappid(4046290)