-- generated by KeySteam
-- update time: 2026-02-16
-- app_name: 西部对决 (West Hunt)

addappid(1570330)

addappid(1570331,0,"5ac859676f89d9398ad7cdf2bc000881eb620df56012ebc9ace954e66a34dbc2")

addappid(1690310)
addappid(2004020)
addappid(2177400)
addappid(2643070)