-- generated by KeySteam
-- update time: 2022-03-01
-- app_name: Physics World

addappid(1571010,0,"7a4ba45f23660f06134568854760403b8f59e38b737363c8e3de12f11e255b26")

addappid(1571011,0,"cffb068345213c2a9472478516b34a74af9bc5394d8bb5d8c9c67d59c81b0c73")
