-- generated by KeySteam
-- update time: 2021-04-27
-- app_name: Dark Romance: Sleepy Hollow Collector's Edition

addappid(1571600)

addappid(1571601,0,"81f68541dd77462b8dc9d0e8ebef0a862017f0e6e7f3d24e187e84684c74764a")
