-- generated by KeySteam
-- update time: 2022-03-15
-- app_name: Helicopter Simulator VR 2021 - Rescue Missions

addappid(1573730)

addappid(1573731,0,"3ac75aa561f51df3e7cf20572587a862d0ffa997666a6ada9d8e5964b402ab31")

addappid(1644420)