-- generated by KeySteam
-- update time: 2021-03-09
-- app_name: Allura: The Three Realms

addappid(1573250)

addappid(1573251,0,"dbf56cdeb56501366f17350ee993ae1e62d7b85b9cd79d2e9f238c20e44c65fc")
addappid(1573252,0,"b970ea2a212c824dbd340c449017571dfa864d288fd8dad14ed4e85908467bf8")
