-- generated by KeySteam
-- update time: 2024-02-19
-- app_name: Technicity

addappid(781180,0,"aa6a6922e07026f9fc8e09031fc46cf0139d451c45541863c7e34da21925691e")

addappid(781181,0,"b0c880f01d4dda1d522028ce42ea7834124f6e31b6076c0cbdf32302d01154a8")
