-- generated by KeySteam
-- update time: 2018-01-10
-- app_name: 783920

addappid(783920)

addtoken(783920,"3226836460777066354")

addappid(783921,0,"7bfed75024577f2df254fe4710edffe482c61586be2123c4a0c7cec69c20cdfe")
