-- generated by KeySteam
-- update time: 2018-01-10
-- app_name: 783970

addappid(783970)

addtoken(783970,"11163314120608538343")

addappid(783971,0,"706d1d82ed6bd252e7f376435ff24313d504a95ca31ee5807fab3a0fa67d774e")
