-- generated by KeySteam
-- update time: 2018-03-08
-- app_name: Annotation of Love

addappid(787220)

addappid(787221,0,"e410b9dfd9e2bc6b99c9c33ebbd64e28534f122af5324e43c0b0cff11a6bdb07")
addappid(787222,0,"41e0ee85c392bcb5eb09b8e08bd32373a893cb5383242bd55ea5326de4a34110")

-- DLC: 1/1

addappid(801830)