-- generated by KeySteam
-- update time: 2021-02-04
-- app_name: Futanari Quest

addappid(790410)

addappid(790412,0,"a44beef7da2241a385cc9b63964b0a672750f2c6b304e7979dfcf8e31d9d73c6")
addappid(847840,0,"9e8464a6b2d112dcae75a1211ce177340b85c34966a782d05718b36028270d97")

-- DLC: 1/1

addappid(847840)