-- generated by KeySteam
-- update time: 2018-01-22
-- app_name: 790660

addappid(790660)

addtoken(790660,"8727835385156618667")

addappid(790661,0,"92ffbca88bd7f0353b42ca662ccde5be47d911ab16bdd38ddfb17c3d9e2a8021")
