-- generated by KeySteam
-- update time: 2018-02-26
-- app_name: !4RC4N01D! 2: Retro Edition

addappid(791550)

addtoken(791550,"9444569563081214164")

addappid(791551,0,"475200863fefe8ecacbf62c0928bc212078f75df21c0524cb619de8d2ff37ebc")
