-- generated by KeySteam
-- update time: 2018-01-26
-- app_name: The Cathedral: Allison's Diary

addappid(793210)

addappid(793211,0,"22b288127b23080c96f8c1f5806d6a8490852a2650819ea306989fe345cb8a4d")
