-- generated by KeySteam
-- update time: 2022-07-28
-- app_name: Movavi Video Suite 17

addappid(795630)

addtoken(795630,"14772329572879083236")

addappid(795631,0,"d3dc3dc8d22d7471a7e172547dce280d35de7360a061c19b2783820cbea89f7f")
