-- generated by KeySteam
-- update time: 2018-01-29
-- app_name: Fantasy Mosaics 27: Secret Colors

addappid(797450)

addappid(797451,0,"e9b4129a1f1394584191d9db08a3193e64f2e4e599d8db2d5885def09995b63f")
