-- generated by KeySteam
-- update time: 2025-12-22
-- app_name: 弃种：叮叮与圣剑

addappid(3433940,0,"91089b1e650dd0d350adcbca30f47fec8578ccc455f6ea95a1845f46641aea5f")

addappid(3433941,0,"2ec926e55b8265b698b2a2b93f83398445d75bf7b3012a55fb0175dd86bd2840")
addappid(3433942,0,"4a85f803f58e56c87a3ec3804d1e7f8f5785e215df3af7cd41b574f0dabc0b33")
