-- generated by KeySteam
-- update time: 2021-05-06
-- app_name: Solitaire Jack Frost Winter Adventures 2

addappid(1600200)

addappid(1600201,0,"6bcab1e8652b6a2699c9891e453e4e73710f6ebaa117f4377f4bc2a00afa4545")
addappid(1600204,0,"e2b8707d072da1c124a0ea97024ee6e39ac6ea6d2e9ba2f8657c0a90635660f4")
