-- generated by KeySteam
-- update time: 2021-09-27
-- app_name: The Marauder Chronicles - Curse over Valdria

addappid(1601380)

addappid(1601381,0,"922fac52d4052d80af37f4c470dea1c60d2a9a794465ae3a95a14269c957d77a")
