-- generated by KeySteam
-- update time: 2021-07-21
-- app_name: Eternia: Pet Whisperer

addappid(1605720)

addappid(1605721,0,"9283ed58a79032fdd752577ff4ee8dbeae3652498c14dc6925acbb47544d16f8")
addappid(1605722,0,"d68b9414fe690a6645967ebd5715c502460e3d1f7c9f1f4838aa83baaab5df3d")
