-- generated by KeySteam
-- update time: 2025-11-21
-- app_name: 《Warhammer 40,000：混沌之门 - 恶魔猎人》

addappid(1611910)

addappid(1611911,0,"86237e0895ee119ad5f6adfe0435ea25f199a14eb12f10f69cd84330b6d22720")

addappid(1804350)
addappid(1883510)
addappid(2126610)
addappid(2421890)