-- generated by KeySteam
-- update time: 2021-11-12
-- app_name: The Sin Collector: Repentless

addappid(1613190)

addappid(1613191,0,"dc2b1b4a9b853c67449baf14221f3e13b6eb8c6aaabaadf08d16869df3133968")
