-- generated by KeySteam
-- update time: 2021-06-10
-- app_name: Wolfriders A Sniper Adventure

addappid(1615750)

addappid(1615751,0,"9c48d991f79e49792c23ca058a99edc283939e2a299414d6c43b4ba7204cc100")
