-- generated by KeySteam
-- update time: 2025-05-20
-- app_name: 双人成行

addappid(1426210)

addappid(1426211,0,"c450c44e032e27d0308cf864259fb2af91bcfc58401a0caf33bb8efba85bb323")

-- DLC: 1/1

addappid(1426390)