-- generated by KeySteam
-- update time: 2022-06-27
-- app_name: Re:Destiny

addappid(1426120)

addappid(1426121,0,"48239e69982b8e819cafea6116230e56fdd2060d7f601c59f8eaad9d3ae5d1e1")
addappid(1442320,0,"1df2b2a5ec44f1d3058c0e80b7f5e54c0eb09c5c7346226e7607f34c69c9d3bd")

-- DLC: 1/1

addappid(1442320)