-- generated by KeySteam
-- update time: 2025-05-28
-- app_name: 星咏之诗

addappid(1434540)

addappid(1434541,0,"418e315d0e566827ad0fe6620fb617d6a736c8854f4e9421880c94d8eeeef3ed")

-- DLC: 0/1
-- missing DLC: 2550260
