-- generated by KeySteam
-- update time: 2020-09-30
-- app_name: Angel Tears

addappid(1438110)

addtoken(1438110,"4307661166554800323")

addappid(1438111,0,"1d27327282e1984641229bd1df1a7ef0b983bd1d664ba32df87910b97ee69bae")
