-- generated by KeySteam
-- update time: 2019-12-07
-- app_name: Mouse Mayhem Shooting & Racing

addappid(1201200)

addappid(1201201,0,"3ebda08ae821c8f3a3ca0fc75b1b6054e74a6eb33c25262de55a0a7ce9f0d943")
