-- generated by KeySteam
-- update time: 2020-02-02
-- app_name: Colossals

addappid(1201770)

addappid(1201771,0,"10af987bc57f129914774f70409d50c8b7bf9105f6cc54b62d65ce4a8056fcda")

-- DLC: 0/1
-- missing DLC: 1240940
