-- generated by KeySteam
-- update time: 2023-03-03
-- app_name: Goblin Summer Camp

addappid(1206290)

addappid(1206291,0,"f55654681ca1d38bf8083c1d063db48f60d2431293a2aeead72087e63bfaae15")

addappid(1595650)
addappid(1775610)