-- generated by KeySteam
-- update time: 2021-06-16
-- app_name: Casina: A Visual Novel set in Ancient Greece

addappid(1215740)

addappid(1215741,0,"768798fd9fd162823aca34c5edfa9da95378b06e9046028e412cd4e3ca508a0f")

-- DLC: 0/1
-- missing DLC: 1643250
