-- generated by KeySteam
-- update time: 2022-01-13
-- app_name: 1218810

addappid(1218810)

addtoken(1218810,"8700912825845065578")

addappid(1218811,0,"7e04262fbdf70531d24c40d1ab08d29fcc2ddd640158714dc74f49f5e1ac5d67")
