-- generated by KeySteam
-- update time: 2017-10-23
-- app_name: 741460

addappid(741460)

addtoken(741460,"1508768272262249438")

addappid(741461,0,"c5b8b59f48a1931319f1a0c9b107467ea47249e7e837db55c9bcbf7ac4426cfe")
