-- generated by KeySteam
-- update time: 2026-03-17
-- app_name: Mega Man X Legacy Collection

addappid(743890)

addappid(743891,0,"aa7be958260862cf85f39eddd672463ecb9c606ec8bd342b786363ecd049651f")
addappid(861801,0,"88ba52fae3de69e7a39adb93fe05ace294dcdd49b3dcaa59f0f4ab42f15aa5ad")

-- DLC: 1/1

addappid(861800)