-- generated by KeySteam
-- update time: 2020-04-26
-- app_name: TAOTH - The Adventures of the Herkulez

addappid(749470)

addappid(749472,0,"e08b04c31c545c9d1a1f704d757faf7a4b4e8027de636175eb3fbc8d4021b07a")
