-- generated by KeySteam
-- update time: 2019-09-06
-- app_name: Ice Age: Scrat's Nutty Adventure

addappid(751060)

addappid(751061,0,"17d8493448d430d74652fed214e70edcf4c2b03dae9585d7486076c99f9236dd")
