-- generated by KeySteam
-- update time: 2018-09-11
-- app_name: National Rugby Manager

addappid(752640)

addappid(752641,0,"c559f2db0e29e1478d4361b08de7796e028fe6d78754a32e2414145d028cb89e")
addappid(885430,0,"d2243e72cc1103728955c33370bb7fc2294bbd27f5f2e5c5907bed91a4b3020c")
addappid(885450,0,"f93fbfaeeff66953d31e958065ce049f55b3500ceeedd1ea1b9ac8a1ec550b97")

addappid(885430)
addappid(885450)