-- generated by KeySteam
-- update time: 2018-06-07
-- app_name: Snail Trek - Chapter 2: A Snail Of Two Worlds

addappid(756320)

addappid(756321,0,"b1479fd780c1c96b5df60c32021da1b721b75209839b0273c466d9cf58a074a6")

addappid(852200)