-- generated by KeySteam
-- update time: 2017-12-23
-- app_name: 757720

addappid(757720)

addtoken(757720,"5818794061082305503")

addappid(757721,0,"c5f32d3dc6a48fe7a778cfad2d22ad3f4701709c910d0ea8eb2400b81faf67f1")
