-- generated by KeySteam
-- update time: 2025-09-17
-- app_name: 边境开拓者

addappid(2346410,0,"34b380a379a3fd70bdb1e44b0c68336c9d7e492bde9c2ea5d5c828c48b9b1e7e")

addappid(2346411,0,"d7c9d01b64ae87808d13677c8bcf87ec9c65923a7145864d396a3f5023069fad")
