-- generated by KeySteam
-- update time: 2023-07-19
-- app_name: Lost Chapter

addappid(2356470)

addappid(2356471,0,"59c36d8857255bb55a2b9511a949068fb700b404c0e53c2398fa9ff4fe047117")
addappid(2356472,0,"e8dce446e51a6744e50a17fabe1de85de72ddab031526f8b58bd5586a44f9e05")
addappid(2646640,0,"c532ffc47cda2a8b782aa6673bfff36e2a9a8384f6e2e239517b81e122da827e")

addappid(2646640)