-- generated by KeySteam
-- update time: 2021-08-30
-- app_name: Have a Blast

addappid(1181650)

addappid(1181651,0,"fe0428fa60c90339873d7cb2dbf967541cb1cc9571440ed8dc6a0e7f8b0bd497")
addappid(1181652,0,"d145871949195e3f8dbfdb96bf1307ea187fa94a9bfa89cb75500508a88845a5")
