-- generated by KeySteam
-- update time: 2022-11-14
-- app_name: Poker Quest

addappid(1184820,0,"5ea55bc26df932d00e34c22dfa5b7a2ec8d7b6d1dcdb21aec2997158982dca53")

addappid(1184821,0,"d99750b50ab3c92db290d86b11a2488433c9cc1f47b9c55c51aacc6387916b66")
