-- generated by KeySteam
-- update time: 2019-11-12
-- app_name: Lovely Hentai

addappid(1185730)

addappid(1185731,0,"56a9da546a617f3a6b5079f840cfe231519feb9ea17e8b2eb2af428f2f8a1f77")
addappid(1185760,0,"751212c4a72a8b854e6a58eeebfb0eea0c6b381966b1ffaaba818ca3d84460eb")

-- DLC: 1/1

addappid(1185760)