-- generated by KeySteam
-- update time: 2019-12-18
-- app_name: New York Mysteries: The Outbreak

addappid(1186580)

addappid(1186581,0,"33a107ed2894acbe1cc19a3cb0040b565c837020266582f30fe3129ece7556e6")
