-- generated by KeySteam
-- update time: 2019-11-20
-- app_name: Gaijin Charenji 1 : Kiss or Kill

addappid(1187950)

addappid(1187951,0,"fe27297a3370837039b9d61eeddde6d14b32effb289aad076503d6f4bbd6b93a")
