-- generated by KeySteam
-- update time: 2020-08-18
-- app_name: Is It Wrong to Try to Pick Up Girls in a Dungeon? Infinite Combate

addappid(1187940)

addappid(1187941,0,"7fff58f5d9b053749934fa69548c9b045a6c2609b51ca0b4c6850f8cdf0fb4eb")
