-- generated by KeySteam
-- update time: 2026-02-25
-- app_name: Cats are Liquid - A Better Place

addappid(1188080,0,"16abecec20298c3e3e7c9ec40966f26b3ab06938a361bd6b1a10f799cbb7693e")

addappid(1188081,0,"6a254ec53d6cd8a59910009468b122ae5ff6cc8cbb3f8a1e2632722b58315c6b")
