-- generated by KeySteam
-- update time: 2021-12-07
-- app_name: KartRider: Drift Closed Beta

addappid(1194260)

addtoken(1194260,"10662101777420242930")

addappid(1194261,0,"f9674c7beebfe60200144edc3242678a36fe7d08b0939477b7a29b9e4b261b4a")
