-- generated by KeySteam
-- update time: 2025-02-16
-- app_name: RTX Sweeper

addappid(1196300)

addappid(1196302,0,"506492dafa9d0d972c45a2700d4261b398f3f8685e117db59c7ad621cdccf03a")

addappid(2166670)