-- generated by KeySteam
-- update time: 2020-04-24
-- app_name: 驱魔道人2 BROKEN SPELL

addappid(1197440,0,"a32a2f541528475f9f41e2b489b2b937b09e86d15bc1fb41ccd2ac873db2153b")

addappid(1197441,0,"47bc0ac447dea6b9cb6a9628b9ee4851099cbee4ba7a40e1ae74933225a204b6")
