-- generated by KeySteam
-- update time: 2025-11-25
-- app_name: Cats and Seek: Kyoto

addappid(2845320)

addappid(2845321,0,"2CBCDD5D39052DB89477A2A536FED85C89B473F983749029780C0A0893ECB116")

-- DLC: 1/1

addappid(3009840)