-- generated by KeySteam
-- update time: 2025-04-24
-- app_name: 洞窟冒险团物语 (Cavern Adventurers)

addappid(2848360)

addappid(2848361,0,"8d828d87f109dc28acc3a5f02de1c95216ff76d797bc0d4bd8d37843dc20efdf")
