-- generated by KeySteam
-- update time: 2026-01-20
-- app_name: The Book of Outcasts

addappid(2849180)

addappid(2849181,0,"8be30c6cc16cc6665ec4f52ad28a6f297c8e3bf7ec677eb2c5e416ff59313ccf")
addappid(4071761,0,"21cd453fe0c9ba47b2ab5dfbb18ee017446d709d2d86bd559ca422203889dbd1")
addappid(4075121,0,"0c5da43ceb0cd46fa29809f324a2b6dcae05719cbba280ff1f4712d6fc0a26d6")

-- DLC: 2/2

addappid(4071760)
addappid(4075120)