-- generated by KeySteam
-- update time: 2026-01-20
-- app_name: The Book of Outcasts

addappid(2849180)

addappid(2849181,0,"8be30c6cc16cc6665ec4f52ad28a6f297c8e3bf7ec677eb2c5e416ff59313ccf")

addappid(4071760)
addappid(4075120)