-- generated by KeySteam
-- update time: 2024-07-01
-- app_name: Extreme Climbing Mirage City

addappid(3061880)

addappid(3061881,0,"341fb2a8e2a4eb6171627022c562fafcc4a8e015fbeab495cb8f5f7a90181ca1")
