-- generated by KeySteam
-- update time: 2026-03-17
-- app_name: Once Upon a Galaxy

addappid(3062740,0,"895a540feb8c75146a626a0a0fc40df3365b86e2879c6260efeb1578160d528f")

addappid(3062741,0,"1642c903f71eb314dffa99df6ff9b9cb04abcd252a9ea8c4a2c3305ff1d4a613")
