-- generated by KeySteam
-- update time: 2017-01-27
-- app_name: 582480

addappid(582480)

addtoken(582480,"16605759189181159700")

addappid(582481,0,"caf28fefe705c3e2161030efceee7fe592fd8ced56e552328f39995a31349640")
