-- generated by KeySteam
-- update time: 2017-02-01
-- app_name: 585790

addappid(585790)

addtoken(585790,"16678304139620788450")

addappid(585791,0,"baae6e6e769c078238317ab22881ce6fc965b3f3b156cba19b36512f8ba457f3")
