-- generated by KeySteam
-- update time: 2017-01-25
-- app_name: Surface: Reel Life Collector's Edition

addappid(586720)

addappid(586721,0,"a8edd3cc7887bbf398290a426acb135971794a2e0ae83a6fd2ca51785317db2d")
