-- generated by KeySteam
-- update time: 2017-02-25
-- app_name: Just VR Slingshot Target Practice

addappid(586990)

addappid(586991,0,"3ffa919ccbf5061ee3def763d5cec6b6d338ff02412d47c93ab2b785f51a0d7a")
