-- generated by KeySteam
-- update time: 2025-05-02
-- app_name: Grass Cutter

addappid(589420)

addappid(589421,0,"24091c04572d7bf57f301c6bb0c9507ed94a30bba3441a424af51cd253248884")

-- DLC: 15/15

addappid(864180)
addappid(864181)
addappid(864182)
addappid(864183)
addappid(864184)
addappid(864185)
addappid(864186)
addappid(864187)
addappid(864188)
addappid(864189)
addappid(882350)
addappid(886660)
addappid(886661)
addappid(993240)
addappid(993241)