-- generated by KeySteam
-- update time: 2017-05-28
-- app_name: SPACE-FRIGHT

addappid(592750)

addappid(592751,0,"e8ac64c6592fddd39e60ce7c23add88c3189c10319211a5e3be3d3ec04a0e410")
addappid(592754,0,"b5885e2fea159abb4628848f0d872db929c94a7d64e7aba1b48d94ce6d7bb7d4")
