-- generated by KeySteam
-- update time: 2017-02-18
-- app_name: Moccasin

addappid(593290)

addtoken(593290,"705677229447942914")

addappid(593291,0,"439f7e09434fd00edbd06e35c2c0e0d7583328f8e506485f6278eb3c51a7d128")
