-- generated by KeySteam
-- update time: 2020-02-23
-- app_name: Return of Red Riding Hood Enhanced Edition

addappid(594320)

addappid(594321,0,"111811c27d4aa702cdbcce2f4b86a0358a59568d3e525ce3b354ac7b66080c25")
addappid(594325,0,"019722d7430844733b303c5c6d1876c55a151a1fb15cd3032300633054c02275")
