-- generated by KeySteam
-- update time: 2023-09-22
-- app_name: Shuyan Saga

addappid(594680)

addappid(594681,0,"8a60d642150870462b5cdeadce51541531564fbab1eb85756b160e2870483cee")
addappid(678080,0,"6ab2a321fac1163c953507be28c16138cc47db751def41d7475174375255da3a")

-- DLC: 1/1

addappid(678080)