-- generated by KeySteam
-- update time: 2024-09-22
-- app_name: The Laziest Person In The World Competition

addappid(3230020)

addappid(3230021,0,"246042F086528D366CD36A7949660B59E2A738F44CED255525CD8D8BCFCAE5A6")

-- DLC: 1/1

addappid(3249820)