-- generated by KeySteam
-- update time: 2025-02-20
-- app_name: Little Lighthouse of Horror

addappid(3231960)

addappid(3231961,0,"2dd9b8fd237df5c7bf136c88fcc27cc69af3fe25983919ab9f92fa05abb7c062")
