-- generated by KeySteam
-- update time: 2019-03-04
-- app_name: Wing Pro 6

addappid(621300)

addappid(621302,0,"61dad3074b32302bff26cb848fddf5e8f6552a03c122613260b717f5a5427aba")
addappid(621304,0,"8f0178e85075bd065cca458087214ae13d03ffac442843e31cea96b1ffcd738c")

addappid(621320)