-- generated by KeySteam
-- update time: 2017-04-10
-- app_name: Haunted Legends: The Bronze Horseman Collector's Edition

addappid(623460)

addappid(623461,0,"6f60a8b8dbdccb2189a529538ed3952a716fdd0bdb7c8ca4ecbd88d7cabcc7ce")
