-- generated by KeySteam
-- update time: 2019-08-29
-- app_name: NEXT JUMP: Shmup Tactics

addappid(624690,0,"a915bd8e06576ab629860f7e16026d85f726e315e4a6459f20b6614e8465afaf")

addappid(624693,0,"3b330aa946f3b7365566fa0bd86073700b54d4c6bf5f32dd520ea59446486330")
