-- generated by KeySteam
-- update time: 2023-10-13
-- app_name: SEQUENCE STORM

addappid(630640)

addappid(630641,0,"d1a365e036daa6c304a7b9ac5382f449fe0f266f81a231134c50d537cfd36b4c")

-- DLC: 2/8
-- missing DLC: 1080140, 1340940, 1356500, 1429990, 1460190, 1669670

addappid(1496660)
addappid(1496661)