-- generated by KeySteam
-- update time: 2017-05-26
-- app_name: The Fidelio Incident

addappid(632070)

addappid(632071,0,"428b11acc3217e31cc42f70dff74f2871e899e28effaf331480d6bf9779fab32")
addappid(642540,0,"f31100d6ec013d8097e133c9078d5c6ab17fe832795b7a88befe79d14bde9046")

-- DLC: 1/1

addappid(642540)