-- generated by KeySteam
-- update time: 2022-05-05
-- app_name: Spire of Sorcery

addappid(637050)

addappid(637051,0,"a4b62b338d0017fe1b08d003de4ac2a73ace00d7a64b5041c908626f10cecd1c")

addappid(1774730)