-- generated by KeySteam
-- update time: 2017-05-11
-- app_name: Weather Lord: Hidden Realm

addappid(637930)

addappid(637931,0,"e23b697369f4ddb15459bb1984d6f05a9ce5ac229c59de83375be1b960388cee")
addappid(637932,0,"bbc8225306af25eb0d5c0c97f4c0e3c6af04b06a0382b85ae09efff3eb1f4abc")
