-- generated by KeySteam
-- update time: 2021-07-18
-- app_name: Friend ReQuest - A Playable Teaser

addappid(1662920)

addappid(1662921,0,"9aa2f337aef54dd5f1dee33859ec3ada7ce2aa794e3b6a15479df807397b7717")
