-- generated by KeySteam
-- update time: 2021-07-13
-- app_name: Griddlers TED and PET 2

addappid(1665050)

addappid(1665051,0,"bb64f5b3ac0204840ee497448982f9fcff36697fd0310853819c0c62d49b8350")
addappid(1665054,0,"7d0477093f8c0d0d79731072c61fb9a1f2aa12c0569684bbec5ec456583c2d3b")
