-- generated by KeySteam
-- update time: 2025-04-14
-- app_name: 1671450

addappid(1671450)

addtoken(1671450,"11137647787076576538")

addappid(1671451,0,"9eddc76fcd0dc898c425fc049cdbcc1395d07ab679ee6b5b607957a075feaacf")
