-- generated by KeySteam
-- update time: 2026-04-02
-- app_name: 仙侠世界2

addappid(1674340)

addappid(1674341,0,"d9685ae72013ab52c65a29b7f72c5be61cba3256ad06145dcb966431bd9f3eca")

addappid(1873680)
addappid(1873690)
addappid(1873700)
addappid(1873710)
addappid(3384790)
addappid(3384800)
addappid(3384810)
addappid(3384830)