-- generated by KeySteam
-- update time: 2026-04-13
-- app_name: Lightyear Frontier

addappid(1677110)

addappid(1677111,0,"5867f4cfbcf22c9f91f80049ace8660657651cbd62163e7e690b3644dbd98d8b")

-- DLC: 1/1

addappid(2655090)