-- generated by KeySteam
-- update time: 2017-01-02
-- app_name: Seduce Me 2: The Demon War

addappid(461700)

addappid(461701,0,"b658d2d274a0acd2941c4edf92b645e5584d0bbc3745717fabded25cbed1d08b")

-- DLC: 1/1

addappid(575610)