-- generated by KeySteam
-- update time: 2023-04-15
-- app_name: 创造历史: 第二次世界大战

addappid(462940,0,"c8805bd124f1346412ac524058de9f3017b206d26f6ef468164dbea41ea59f87")

addappid(462941,0,"b9f5ed1c991d1165b358f79dbf1e0d57a339ed9a8c5bb997d791d2daa58f52a7")
