-- generated by KeySteam
-- update time: 2025-10-02
-- app_name: Jagged Alliance: Rage!

addappid(463170)

addappid(463171,0,"9de2d49c17c98da83777f567f7abe2138a17ba9bae6b24e41d73a59158bd7d5f")
addappid(463172,0,"bf85920d811775a6a590d6a34cb60d5c6a1fbc4dce46d8c997278b9e8b431d95")
