-- generated by KeySteam
-- update time: 2016-06-21
-- app_name: Nevertales: The Beauty Within Collector's Edition

addappid(466010)

addappid(466011,0,"3a662fb24b5f68d36eed71623d8b709920fc5af5f15e22485d4a289ee45866f1")
