-- generated by KeySteam
-- update time: 2025-12-11
-- app_name: The Pedestrian

addappid(466630)

addappid(2061990,0,"af7f456baac74501925d7a3d7e320450bcfe36856fabd12ccb38098d17737ebf")

addappid(2061990)