-- generated by KeySteam
-- update time: 2017-10-06
-- app_name: C O S M

addappid(467480)

addappid(467482,0,"28d701d468125741cd99300639f3779920e3754d4c155016c97df67c9b1bc695")
addappid(467483,0,"a613b592f381b07275b1aca7593fbaa20059c8674fada8c4fed66843cf311294")
