-- generated by KeySteam
-- update time: 2017-11-16
-- app_name: Rick and Morty: Virtual Rick-ality

addappid(469610)

addappid(469611,0,"7abcef197bdb04642c4e4e7384e694c1d8e5d847888d64fdca45c9d415ebd928")
