-- generated by KeySteam
-- update time: 2024-08-01
-- app_name: Higurashi When They Cry Hou - Ch.3 Tatarigoroshi

addappid(472870)

addappid(472871,0,"3840b67289bf6bf1ff4d211ce84dfdbb312f8cb2445e94d81db7ab6c841219d2")
