-- generated by KeySteam
-- update time: 2016-05-30
-- app_name: 473490

addappid(473490)

addtoken(473490,"14516966271713694133")

addappid(473491,0,"653fe1c28edba9caef376046b0e0a36e8732c90601355916f90a2f749375cf66")
