-- generated by KeySteam
-- update time: 2016-06-22
-- app_name: 473580

addappid(473580)

addtoken(473580,"5425001503850313655")

addappid(473581,0,"b60827b74552b6610432850c520df31e9ed15d23e563b8f48facb51545ed5577")
