-- generated by KeySteam
-- update time: 2023-08-07
-- app_name: Blackout Hospital

addappid(2301510)

addappid(2301511,0,"30674f5c239dc4f37035e4edb5417eb5385cc2234aa0d14206e9ea611dabce91")

addappid(2318220)