-- generated by KeySteam
-- update time: 2023-02-24
-- app_name: G-MODEアーカイブス+ 探偵・癸生川凌介事件譚 Vol.10「永劫会事件」

addappid(2308430)

addappid(2308431,0,"651db18623298926f2195829096db889809d1d66f5b15de19414f59a77414b49")
