-- generated by KeySteam
-- update time: 2025-09-13
-- app_name: 兵团突击：现代战争

addappid(2310160)

addappid(2310161,0,"d9e66eb033b40fd60533dc60970313ca9fa354a0c6edcb559cffea6b9094d0ed")
addappid(3124490,0,"fadf8d40948c5e83ed757ed693f98ae4904f501495cbd7ca6caa558837cc2b4e")
addappid(3216920,0,"131bb568d2ac6ea3be6f1e2582df787b3f05f1a23b6461559434587b056d7aef")
addappid(3280600,0,"393c5e207b5f65ede5c5cc4b83074e5e2ddf683b5b036e90fc3c84ad3e7250b2")

addappid(3124490)
addappid(3216920)
addappid(3280600)
addappid(3280610)