-- generated by KeySteam
-- update time: 2023-02-19
-- app_name: The Very Brief and Meaningless Adventure of Hero Man

addappid(2319540)

addappid(2319541,0,"67C258EA34D8F0E47C203B9180519D12D900CDCE536AB454D1D7F8E178FCBD09")
