-- generated by KeySteam
-- update time: 2026-01-20
-- app_name: BlackForge: A Smithing Adventure

addappid(2146140)

addappid(2146141,0,"c747cfb10c3175fc0d2400592be76f7e75c7a3a701d410b2dcd72e300b0d9540")
