-- generated by KeySteam
-- update time: 2023-09-22
-- app_name: Builders of Greece: Prologue

addappid(2147110)

addappid(2147111,0,"ec38e986c6e306bf1c17abbe489fdd99abc9f37b69f7315aea785ac27a4612f6")
