-- generated by KeySteam
-- update time: 2025-08-28
-- app_name: Football Coach: College Dynasty

addappid(2151290,0,"95932fdd9d26129781d18c408c5d25a62d6f5598b0316eb55464e7f215750de4")

addappid(2151291,0,"4510fce6947cb8c25d77ebf3aa7a8883594265d1f4ed82ba98b2e062caa1687c")
