-- generated by KeySteam
-- update time: 2023-03-09
-- app_name: Chronicles of Forgotten Tears

addappid(2152540)

addappid(2152541,0,"ad3c50af4537e35f10451e24a9752724ffcf7660bc900a4b98db05d7cfebcad5")
