-- generated by KeySteam
-- update time: 
-- app_name: Snuggle Truck

addappid(111100)

addappid(111101,0,"776b5f47a73f4aa4a362151106c10a694f0a48b0a1518ad6846bbce55581253c")

addappid(203070)
addappid(203090)
addappid(203100)
addappid(203110)
addappid(203120)
addappid(203130)