-- generated by KeySteam
-- update time: 2025-09-12
-- app_name: Elven Legacy

addappid(25850)

addappid(25851,0,"59c6c23bcc9e3403f4192456ec0408beeab1fd3ebc19745a079873aba44338df")
addappid(25852,0,"b3915d4de1ac6b36070c01b2359fff39d182ca13019c1103e1d98ab366ce7338")
