-- generated by KeySteam
-- update time: 2025-03-13
-- app_name: Nancy Drew Dossier: Lights, Camera, Curses!

addappid(31870)

addappid(31871,0,"d9709246e19e9dff67ab8283e03b184113ebe4b2bcb83efdc52958b26a1dd871")
