-- generated by KeySteam
-- update time: 2021-02-06
-- app_name: 1544690

addappid(1544690)

addtoken(1544690,"15362268865769563482")

addappid(1544691,0,"c80dc5686a14e54a42b7f23f4acf0c3943f72d7b4b31b321f4566796f04ca690")
