-- generated by KeySteam
-- update time: 2025-02-28
-- app_name: The Inheritance of Crimson Manor

addappid(1553120)

addappid(1553121,0,"d2e51c927ce792457ab9cc2fcbfabae4132907ead4e91d633dbd1dd398c45d9d")

-- DLC: 0/1
-- missing DLC: 3506360
