-- generated by KeySteam
-- update time: 2026-01-21
-- app_name: 4191080

addappid(4191080)

addtoken(4191080,"9464481385394156512")

addappid(4191081,0,"6c2cd0ab4df6f6a3ac8676330dbcfa16a0c369c7f3ae2f6814aedfc8b74222d8")
